### ISSUE TITLE
analysis_url

### ISSUE THREAD

**Issue by Snippern** [plamere/spotipy#101]
Hi! 

I'm suddenly no longer able to access analysis_url and very curious to find out if I'm the only one experiencing this problem. I'm getting error status 401 with the message "No token provided". I'm using the prompt_for_user_token function to authenticate. 

Thank you in advance!
-Snippern

**Comment by plamere** [comment]
There was a change to the spotify API - you are now required to include
your auth token when you get the analysis url. This can be done easily with
the _get method like so:


from spotipy.oauth2 import SpotifyClientCredentials
import json
import spotipy
import time
import sys

client_credentials_manager = SpotifyClientCredentials()
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)
sp.trace=False

if len(sys.argv) > 1:
    artist_name = ' '.join(sys.argv[1:])
    results = sp.search(q=artist_name, limit=50)
    tids = []
    for i, t in enumerate(results['tracks']['items']):
        print(' ', i, t['name'])
        tids.append(t['uri'])

    start = time.time()
    features = sp.audio_features(tids)
    delta = time.time() - start
    for feature in features:
        print(json.dumps(feature, indent=4))
        print()
*        analysis = sp._get(feature['analysis_url'])*
        print(json.dumps(analysis, indent=4))
        print()

**Comment by Snippern** [comment]
Perfect! Thank you so much!

**Comment by patalanov** [comment]
using the same code, I get this:

    features = sp.audio_features(tids)
AttributeError: 'Spotify' object has no attribute 'audio_features'

what is wrong?
