### ISSUE TITLE
how can i get track by artist?

### ISSUE THREAD

**Issue by xgate1** [plamere/spotipy#107]
how can i get some tracks?
i use sp.search() (example: sp.search('rap god','1','0','track')  )
i want to get (rap god-eminem)
what use i query?

**Comment by stephanebruckert** [comment]
You can write a more specific `query`, see https://developer.spotify.com/documentation/web-api/reference/search/search/#writing-a-query---guidelines

```
query = 'track:"rap god"+artist:"eminem"'
sp.search(query, limit=1, type='track')
```
