### ISSUE TITLE
Run a spotipy script as cronjob on a Raspberry Pi (OAuth problem)

### ISSUE THREAD

**Issue by michael-123** [plamere/spotipy#108]
Hi, 

I tried to run my spotipy based python script on the Raspberry Pi. It won't work. 
In the logs you will find the request for a new OAuth token ("... Paste that url you were directed to to complete the authorization."). 

The spotipy cache file is also in the directory. The script works as long as I will not run it via CRON. 

I cannot see how to solve this. Can somebody help me?

Greetings, michael

**Comment by thedangler** [comment]
I'm running into the same problem, it keeps asking me to authenticate even though I have. It's as if it doesn't get the cached token.

**Comment by michael-123** [comment]
Does cron run with its own user?

**Comment by grlindburg** [comment]
I believe cron runs as root. I set this up so that I'm cd'ing to the appropriate directory within cron before executing my spotipy script. Something like:

`0 * * * * cd /env && /env/spotipy_script.py >> spotipy.log`

Seems to work just fine for me since my appkey is also within this directory.

**Comment by thedangler** [comment]
Mine is working now, I was a moron and put , in between my scopes instead of leaving a space.
However, when I provide the full callback url it never works, If I provide ?code=.... it works. But I think it a pycharm console issue.

**Comment by michael-123** [comment]
Thanks @grlindburg 
This worked for me too. My crontab task (every night at 0:24 AM)

`24 0 * * * cd /home/pi/scripts/SpotifyNotificationTweeter && python3.4 main.py > /home/pi/snt.txt`
