### ISSUE TITLE
Read timeouts

### ISSUE THREAD

**Issue by cobbs-totem** [plamere/spotipy#116]
Every once in a while, a search never returns.  It hangs, seemingly forever, until I have to kill my process and start over.

Is there a way to set a timeout value that can be passed along to the underlying requests object?

**Comment by eugenio412** [comment]
I had the same problem, at the end the problems was that I had a very high ping towards Spotify endpoint, and Spotify wasn't replying, it's weird, but that's how I solved. Try with a VPS with low ping to api.spotify.com

**Comment by jeremygrieshop** [comment]
Thanks for the feedback (again).  I'm running my app from my house, and don't have any intention of hosting it somewhere else.

Seems like the spotipy API could simply put a timeout on the 'requests' call and return if no reply comes back in sufficient time.

**Comment by eugenio412** [comment]
I know, but that's not how it works right now, I guess they are not interested in very small project, I tried contacting them but they didn't told my why

**Comment by alexey-v-paramonov** [comment]
I have created a fork and added a new option `requests_timeout`
 https://github.com/alexey-v-paramonov/spotipy
So you can add a timeout on Spotipy initialization like this:
`spotify = spotipy.Spotify(requests_timeout=10)`

After that all Spotify requests will have that timeout.

**Comment by alexey-v-paramonov** [comment]
#125
