### ISSUE TITLE
How can I get the time of release of a song or an album

### ISSUE THREAD

**Issue by RajarshiBhadra** [plamere/spotipy#117]
I was going through spotipy and its awsome. I was hoping to extract the time of release of an album or song. Any help in this regard would be greatly appreciated

**Comment by mrben** [comment]
Do you mean the release date?

It's in the Web API for an [album](https://developer.spotify.com/web-api/get-album/) and in the return from the Spotipy album call.

```
In [6]: ret = api.album('spotify:album:3j8VO8KmIeFACN1ZpEeasY')

In [7]: ret['release_date']
Out[7]: '2016-06-10'

In [8]: ret['release_date_precision']
Out[8]: 'day'
```

**Comment by RajarshiBhadra** [comment]
Yes I meant release date. However I would like to see it by track instaed of album. Is it possible?

**Comment by mrben** [comment]
Did you check the [docs](https://developer.spotify.com/web-api/get-track/)?

It's not in the track return call but you can get the album ID from the track response, and then get the album data in a separate call.

**Comment by RajarshiBhadra** [comment]
Thanks. That did it
