### ISSUE TITLE
Connection refused when trying to run a auth example.

### ISSUE THREAD

**Issue by c0nn3r** [plamere/spotipy#118]
After a night of debugging, I am convinced that something is wrong here. I am running the example that tries to get a user's shared tracks:

```python
import sys
import spotipy
import spotipy.util as util

scope = 'user-library-read'

if len(sys.argv) > 1:
    username = sys.argv[1]
else:
    print "Usage: %s username" % (sys.argv[0],)
    sys.exit()

token = util.prompt_for_user_token(username, scope)

if token:
    sp = spotipy.Spotify(auth=token)
    results = sp.current_user_saved_tracks()
    for item in results['items']:
        track = item['track']
        print track['name'] + ' - ' + track['artists'][0]['name']
else:
    print "Can't get token for", username
```
My callback URL is https://localhost:8888/callback/, when I run the program it quickly redirects me to a URL with a code attached, but when I copy it into the prompt in the program I get an error.
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='accounts.spotify.com', port=443): Max retries exceeded with url: /api/token (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10b5d8650>: Failed to establish a new connection: [Errno 61] Connection refused',))
```
I'm not sure what is going on as I directly copied my program ID, the program callback url and my program's secret right into the env variables.

Any help fixing this problem would be appreciated.

**Comment by eugenio412** [comment]
Something wrong with the token, are you using a token enabled to get user saved tracks? You must add the right ticks generating the token on Spotify web API website

**Comment by c0nn3r** [comment]
I'm not sure what you mean, I generated my client ID and my client secret on `https://developer.spotify.com/my-applications/#!/applications` is this not the right place? Thanks for the response!

**Comment by eugenio412** [comment]
I mean you need to add the right scope for the token

**Comment by tahsinac** [comment]
Wow, this is almost 2 years old now. Probably a shot in the dark, but did you manage to figure out (and remember) what it was that caused this error? I'm getting the exact same error.

**Comment by 1llusion** [comment]
Getting the same error. Seems to happen when there are repeatedly too many connections.

**Comment by deekay2310** [comment]
Anyone with a solution? Experiencing the same error

**Comment by shillshocked** [comment]
I'm getting this error too sometimes.

**Comment by deekay2310** [comment]
Refreshed the access tokens and pasted the new one. It worked for me but it is more of a makeshift solution rather than a permanent one. Also, didn't experience the same issue after having pasted the new tokens.

**Comment by psl11** [comment]
> Refreshed the access tokens and pasted the new one. It worked for me but it is more of a makeshift solution rather than a permanent one. Also, didn't experience the same issue after having pasted the new tokens.

OMG. It also worked for me, but don't know why... 🤦‍♂

**Comment by lawuysal** [comment]
How to refresh it? I'm using flutter and I stuck where it comes from a authentication http request. Just shows localhost:8888/calback/code=...... and net:ERR_CONNECTION_REFUSED
