### ISSUE TITLE
Spotify API get track info based on track name?

### ISSUE THREAD

**Issue by GeorgeHosuAdswizz** [plamere/spotipy#130]
Is there a way to query the spotify API in order to get information about a track/artist/album/playlist based on its name.

E.g. Queery for "track=I need a hero&artistName=..." and get a URI/ID and some information about the track.

I couldn't find anything like this in the documentation. Am I overlooking something

**Comment by mrben** [comment]
Take a look at the search function perhaps: https://github.com/plamere/spotipy/blob/1304ac33c06eb401f36fd25bda449f0f881b7bd3/spotipy/client.py#L313

Calls this endpoint: https://developer.spotify.com/web-api/search-item/
