### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by jsclose** [plamere/spotipy#131]
After installing the spotipy package, I am still getting an error while trying to run the sample code

File "spotipy.py", line 1, in <module>
    import spotipy
  File "/Users/jakeclose/Sites/personal/spotipy.py", line 10, in <module>
    sp = spotipy.Spotify()
AttributeError: 'module' object has no attribute 'Spotify'

**Comment by Monster-Zou** [comment]
Hi jsclose.

I got the same error. Did you fixt it?

Thanks.

**Comment by Monster-Zou** [comment]
Okay, I got the problem.
Change the name. You could not name it as spotipy.py. Otherwise, the attribute 'Spotify' will be searched within your spotipy.py file. Obviously, you don't have any object defined in your code.

**Comment by umar-farooq-khan** [comment]
i dont have

**Comment by YuxiaoLuo** [comment]
I got the same error... Did you solve it @umar-farooq-khan?

**Comment by stephanebruckert** [comment]
@YuxiaoLuo can you please share a stacktrace?
