### ISSUE TITLE
current_user_playlists() method is missing from the spotipy object

### ISSUE THREAD

**Issue by roman-ku** [plamere/spotipy#146]
The spotipy object is missing the [current_user_playlists()](http://spotipy.readthedocs.io/en/latest/#spotipy.client.Spotify.current_user_playlists) method.

When you try to do it, you get the following error:
`AttributeError: 'Spotify' object has no attribute 'current_user_playlists'`

I checked the `client.py` and it's missing from there.

**Comment by plamere** [comment]
I see it here:

https://github.com/plamere/spotipy/blob/master/spotipy/client.py#L349

**Comment by roman-ku** [comment]
Welp.

I was using version 2.3.8, just upgraded to 2.4.3 and it's in there.
