### ISSUE TITLE
Retry-After needs small additional delay to work properly

### ISSUE THREAD

**Issue by akashlevy** [plamere/spotipy#151]
The code for Retry-After doesn't work for me. I'm on a very fast computer with a very fast internet connection and the problem I'm having is that even though the request is being retried after the specified time, the server is still not ready for the request when it arrives. I fixed this problem for myself by adding an additional one second delay to the retry code. This should be fixed in a future version of this library. I'd be happy to make a pull request if anyone else is having this issue or if the authors think it would be useful.

**Comment by plamere** [comment]
I'll incorporate this change

**Comment by mrben** [comment]
Seems sensible to wait for the delay that Spotify specify. Maybe they were just a bit slow that day for some reason?

**Comment by akashlevy** [comment]
I'd say there should be some small additional timeout, perhaps a couple milliseconds?

**Comment by SirDavidDias** [comment]
Hi, I have the same problem.

Could you update the solution, please?

My best,
