### ISSUE TITLE
Problem with 'scope' in authentication

### ISSUE THREAD

**Issue by Roobxyz** [plamere/spotipy#152]
Hi,

I was trying to do some basic OAuth stuff and came across what seems to be an error regarding the cached OAuth application.

The cached json fails with the following final error:
```
File "/usr/local/bin/anaconda/lib/python2.7/site-packages/spotipy/oauth2.py", line 158, in _is_scope_subset
    needle_scope = set(needle_scope.split())
AttributeError: 'NoneType' object has no attribute 'split'
```
my json has 
``` "scope": null```
I tried removing the control from lines 137/138 of
`/usr/local/bin/anaconda/lib/python2.7/site-packages/spotipy/oauth2.py`
```python
 # if scopes don't match, then bail
                if 'scope' not in token_info or not self._is_scope_subset(self.scope, token_info['scope']):
                    return None
```
which allowed the cached json to work. Just wanted to highlight this.

Thanks

**Comment by tcarette** [comment]
I have the same problem. Why is it closed?

**Comment by Roobxyz** [comment]
Think I was using incorrectly,

	util.prompt_for_user_token(username, scope='user-library-read’)

Maybe there should be a default scope set - but specifying it fixes the call.

Cheers,
Reuben

**Comment by idofr** [comment]
Over two years later and I'm having the same problem.
Solved it by adding the following line to oauth2.py -> _is_scope_subset(....)
`
        if needle_scope is None and haystack_scope is None:
            return True
`

Not sure why the issue was close. I also have the feeling though that I'm using the scopes wrong. Could someone please provide a quick explanation?

Cheers,
