### ISSUE TITLE
_warn function not used correctly

### ISSUE THREAD

**Issue by fhennig** [plamere/spotipy#155]
The _warn function does not handle format arguments, but is used as if it would in line 849.

The function could be adapted to handle format arguments, like so:

    def _warn(self, msg, *args):
        print('warning:' + msg.format(*args), file=sys.stderr)

```
Traceback (most recent call last):
  [...]
  File "[...]/lib/python3.4/site-packages/spotipy/client.py", line 222, in track
    trid = self._get_id('track', track_id)
  File "[...]/lib/python3.4/site-packages/spotipy/client.py", line 850, in _get_id
    type, fields[-2], id)
TypeError: _warn() takes 2 positional arguments but 5 were given
```

**Comment by plamere** [comment]
thanks, will update!

**Comment by stephanebruckert** [comment]
Duplicate https://github.com/plamere/spotipy/issues/367
