### ISSUE TITLE
sp.user_playlists() does not return collaborative playlist that user is following

### ISSUE THREAD

**Issue by DanG100** [plamere/spotipy#157]
The user_playlists() does not return collaborative playlists that the current user is following. On the Spotify API console those playlists are returned.

**Comment by cmcnutt1** [comment]
The user_playlists function only pulls the playlists that the user is the owner of. If you're the owner of the collaborative playlist, it will get returned. However, to my knowledge, there is nothing in the spotipy code that allows you to pull down the playlists that a user is following. I'll mess around with the code a bit and see if there's any way to access the user's followed playlists.

**Comment by DanG100** [comment]
The problem is that the [spotify web api console](https://developer.spotify.com/web-api/console/get-current-user-playlists/) returns a different number of playlists then user_playlists(). Normal playlists that I follow show up in both.However, only collaborative playlists that I follow aren't in the playlists dict user_playlists()

**Comment by cmcnutt1** [comment]
Changing the scope to 'playlist-read-collaborative' is what did the trick for me. Had mine set on playlist-modify-private, and would not show any collaborative until I changed it. You will have to reauthorize when your program does token authentication, but should work after you make the changes and reauthorize

**Comment by DanG100** [comment]
Oh, that fixed it. Awesome.
