### ISSUE TITLE
Using Spotipy as a remote control for Spotify

### ISSUE THREAD

**Issue by ffries** [plamere/spotipy#162]
First, I would like to congratulate the author and the community for their hard work.

As far as I understand, Spotipy does not offer direct sound output. 
Can I use Spotipy as a remote control for Spotify. i.e.

Machine A : runs Spotify with a premium account.
Machine B : runs Spotipy as a remote control for machine A.

If I modify the playlist on machine A using machine B:
user_playlist_add_tracks(user, playlist_id, tracks, position=None)

Can I trigger reading the playlist remotely using machine B.

Thanks!

**Comment by stephanebruckert** [comment]
I guess you can, using the `devices` and `playback` endpoints. See https://spotipy.readthedocs.io/en/latest/#spotipy.client.Spotify.pause_playback and let us know if any endpoints are missing from the beta `Player` API https://developer.spotify.com/documentation/web-api/reference/player/
