### ISSUE TITLE
Different results using the web console and this lib

### ISSUE THREAD

**Issue by gaspaio** [plamere/spotipy#164]
I'm gettting different sets of results for the same query string when I test it via the web console (or curl) and via the spotipy search method.

For example : the query 'trick me artist:kelis' yields many more results via the web console than via the library.

Any ideas why this is so ? Looking at the source code I can't find an explanation. Could it be linked to the auth token ?

**Comment by gaspaio** [comment]
Actually, using the token I got from the web console I get the same results via spotipy. Still don't get why though. 
I guess this is not a bug after all. Closing request and thanks for the great work.

**Comment by MarvBob** [comment]
I'm facing the same issue: when using `oauth2.SpotifyClientCredentials` with my client id and secret given in my app dashboard on spotify for developers, I have a lot less results than using the web console.
I confirm I get the same results via spotipy when using the token I got from the web console but I would like to understand how can I get a token that will let me access to all results... I don't think it is a good practice to hardcode the token given in the web console.

**Comment by xmztools** [comment]
I'm having this same problem with spotipy returning many fewer results than the web console. How do I hardcode the token from the web console into my app that uses spotipy so I can check if it helps my issue though? Do I use it in place of the client credentials manager?
