### ISSUE TITLE
Is it possible to create a python code for listening to preview but without logged in ( for visitors)

### ISSUE THREAD

**Issue by tlss94** [plamere/spotipy#165]
Hi,

I would like to add a play button on my blog so that any visitors can listen to the music but I read that it request people login??
Is there any way to circumvent that?

Thanks!

Also where can I find a complete code lines for python other than github which I find it is not very easy for beginner to understand which files correspond to what and how to assemble that.

**Comment by JohannesAck** [comment]
Yes, it is!

The ["get a track" ](https://developer.spotify.com/web-api/get-track/) request has a property called "preview_url", which includes a link to a 30s MP3 preview.

**Comment by tlss94** [comment]
ok thanks!

btw is it possible to get social tags  about artist album tracks etc.. ? (provided by users on the internet  ideally)

**Comment by JohannesAck** [comment]
I'm not sure what you mean by social tags, the only thing I know of that sounds like tags to me is genre information about artists, which you can obtain with get_artist.
Otherwise feel free to consult the Spotify API documentation [here](https://developer.spotify.com/web-api/).

**Comment by stephanebruckert** [comment]
@JohannesAck seems to answer the questions, closing
