### ISSUE TITLE
Should get_playlist be adapted to download the full playlist if not stated otherwise?

### ISSUE THREAD

**Issue by JohannesAck** [plamere/spotipy#166]
As it is right now, get_playlist only sends one request which is limited 100 tracks of the playlist. 
I think it might be nice to have it request all parts and concatenate them on its own.

If you agree I'd like to send a pull-request with (currently not in a github repo) code, that adapts the method to do just that.

**Comment by stephanebruckert** [comment]
No, this is how API usually work, it's up to the developer to decide how the retrieval of the playlist is handled. You can use `offset` and `limit` to iterate over all items, or use `next`:

```
results = sp.current_user_saved_tracks()
show_tracks(results)
while results['next']:
    results = sp.next(results)
    show_tracks(results)
```
