### ISSUE TITLE
user_playlist_remove_all_occurrences_of_tracks() throws invalid track uri error

### ISSUE THREAD

**Issue by gauthamanms** [plamere/spotipy#168]
I got myself authenticated and could access and work well with other functions which requires aunthetication in spotipy. However I couldnt get user_playlist_remove_all_occurrences_of_tracks() work.
I tried Keeping the code as simple as possible by trying to pass user_playlist_remove_all_occurrences_of_tracks('<user_id>', '<playlist_id>', '<track_id>'), 
but it shows the following error:

SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/users/msgauthaman/playlists/4Sc7nWBUrNnhjSoMDyPCdE/tracks:
 JSON body contains an invalid track uri: spotify:track:5

**Comment by Artrek** [comment]
I made a GitHub account just to respond to this. Currently, my code pulls the song name, album, artist, and URI from each song in a playlist and stores it in a list called complete. Here's an example of the first two entries in the list:
```
print(complete[0])

('More Than a Feeling', 'Boston', 'Boston', 'spotify:track:1QEEqeFIZktqIpPI4jSVSF')
```
```
print(complete[1])

('Peace of Mind', 'Boston', 'Boston', 'spotify:track:1GqlvSEtMx5xbGptxOTTyk')
```
With this you can further access a specific part of each entry:
```
print(complete[0][3])

spotify:track:1QEEqeFIZktqIpPI4jSVSF
```
Here's what I was trying to do before, which is basically your code:
```
sp.user_playlist_remove_all_occurrences_of_tracks(username, '4nJyAWMGALHKx6I67Ct9x8', complete[0][3])
```
This throws the same error:
`JSON body contains an invalid track uri: spotify:track:1`

What fixed it for me was declaring a new variable tracks, which contains a list that of only complete[0][3].
```
tracks = [complete[0][3]]
sp.user_playlist_remove_all_occurrences_of_tracks(username, '4nJyAWMGALHKx6I67Ct9x8', tracks)
```
I don't know why this works, but it's how I fixed the problem.

**Comment by cameron-gagnon** [comment]
It doesn't need to be a new variable, it just needs to be within an array, such as the 's' in tracks slightly suggests.
This should work as well:
`sp.user_playlist_remove_all_occurrences_of_tracks(username, '4nJyAWMGALHKx6I67Ct9x8', [complete[0][3]])`

**Comment by stephanebruckert** [comment]
Indeed, as per the doc it should be an array of `track_ids`
