### ISSUE TITLE
Pasted callback URL is followed by Spotipy not Parsed

### ISSUE THREAD

**Issue by old-square-eyes** [plamere/spotipy#171]
I get a callback from Spotify, which contains my code in  `.../callback/?code=AQAu..." format. Yet when I paste this into Spotipy (raw_input) the url is opened instead of being parsed as a string.

Maybe it's my interpreter. But if I remove enough of the first part of the URL (so it's not recognisable as a URL) I can carry on with the execution (i.e. parse the string).

I'm using Pycharm FYI.

**Comment by stephanebruckert** [comment]
Looks related https://github.com/plamere/spotipy/issues/276
