### ISSUE TITLE
Swap print for logging

### ISSUE THREAD

**Issue by znorris** [plamere/spotipy#172]
While it is nice to have some debug output when my requests are retrying, I find it to be a bit verbose. It would be nice if these [print statements](https://github.com/plamere/spotipy/blob/7499d8e511ce3f5588a16702c9533233ec716cab/spotipy/client.py#L158) were adjustable via log level by using `logging`.

Really useful library, thank you!

**Comment by skvoter** [comment]
+1
really'd like to have that feature, cause making curses app then begins a pain

**Comment by stephanebruckert** [comment]
Duplicate, please discuss in https://github.com/plamere/spotipy/issues/172
