### ISSUE TITLE
Incorrectly Causes Returns when Artist or Title has Japanese Characters

### ISSUE THREAD

**Issue by Chris-Perkins** [plamere/spotipy#178]
A bit of a weird one. I have Dream Sweet in Sea Major in my playlist by "ミラクルミュージカル". I was having problems with my program due to what I thought was my own programming logic.

I then put in the example function on Spotipy's own website for getting all tracks off a playlist. Here are the raw results:

CODE:

>                 for i, item in enumerate(tracks['items']):
>                     track = item['track']
>                     print("Attempting to add %s" % track['name'])
>                     print("   %d %32.32s %s" % (i, track['artists'][0]['name'],
>                                                                   track['name']))
>                     print('Doesn\'t get here on Japanese artist')

OUTPUT:

> Attempting to add Bohemian Purgatory Part. 1
>    0           World's End Girlfriend Bohemian Purgatory Part. 1
> Doesn't get here on Japanese artist
> Attempting to add Bohemian Purgatory Part. 2
>    1           World's End Girlfriend Bohemian Purgatory Part. 2
> Doesn't get here on Japanese artist
> Attempting to add Just You
>    2                    Pierce Fulton Just You
> Doesn't get here on Japanese artist
> .... more output
> Attempting to add Me and Your Mama
>    7                 Childish Gambino Me and Your Mama
> Doesn't get here on Japanese artist
> Attempting to add Dream Sweet in Sea Major

After attempting to add the artist with Japanese characters, my function returns despite the above code being in an infinite loop with no way to escape but user input.

I should also note that there are 20 songs in this playlist.

I'm also guessing this doesn't necessarily have to do with Japanese characters, but non-latin or ascii characters in general.

**Comment by 622michael** [comment]
I fixed this issue by adding ensure_ascii=false to the json.dumps in the client.py file.

**Comment by stephanebruckert** [comment]
I can't find the exact same playlist you are talking about and can't reproduce it with japanese artists, track names or playlist names. Please let me know if you still have this issue and feel free to re-open with a complete and minimal code sample.
