### ISSUE TITLE
Add support for the currently playing endpoint

### ISSUE THREAD

**Issue by mdbraber** [plamere/spotipy#180]
https://developer.spotify.com/web-api/get-the-users-currently-playing-track/

**Comment by mdbraber** [comment]
https://github.com/plamere/spotipy/pull/181

**Comment by mdbraber** [comment]
More info here:
https://developer.spotify.com/web-api/get-the-users-currently-playing-track/

**Comment by Bluscream** [comment]
Fixed with #191
