### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by Freso** [plamere/spotipy#186]
Hello!

It would be nice if the releases got git tagged so it'd be possible to use git to say `git diff v1.4.3..v1.4.4` etc., and would also allow packages such as https://aur.archlinux.org/packages/python-spotipy-git to automatically update their version string to the latest release.

**Comment by stephanebruckert** [comment]
Just created a 2.5.0 release + tag https://github.com/plamere/spotipy/releases
