### ISSUE TITLE
simple way to download mp3 from spotify preview URL?

### ISSUE THREAD

**Issue by gmaijoe** [plamere/spotipy#192]
Hi all, I have the previewURL currently and I want a simple way to download the mp3 from the url.

Anyone have a good idea? thanks in advance

**Comment by lohriialo** [comment]
I don't think that's possible, Spotify stores/download offline tracks in encrypted binary format that is later decrypted by the application during playback time.

**Comment by ritiek** [comment]
One could just use any of the available HTTP libraries to download stuff.
https://stackoverflow.com/questions/16694907/how-to-download-large-file-in-python-with-requests-py

**Comment by stephanebruckert** [comment]
@ritiek's answer is useful but closing as unrelated to spotipy.

**Comment by prakashclt** [comment]
Use the wget module in python.
It is easy to use.

import wget
file = wget.download(url)

**Comment by Rsalganik1123** [comment]
hi! for posterity, tried the ones above and they didn't really work for me. So, I found an easier way. 

Just use : 
```
import urllib.request
example_url = 'https://p.scdn.co/mp3preview/c1d518645f20aecb3c6d2b5b93af4a96af57c35fcid=157d02760f23471aa57b6a700a78c863'
urllib.request.urlretrieve(example_url, 'test.mp3')
```
that will create a file called test.mp3 with the audio contained in that url
