### ISSUE TITLE
Authorization documentation changes

### ISSUE THREAD

**Issue by kotutuloro** [plamere/spotipy#194]
It seems like Spotify has changed the authorization requirements for the [API's endpoints](https://developer.spotify.com/web-api/endpoint-reference/).

All endpoints now require authorization, so things like searching and fetching tracks need an access token. The Spotipy docs has an example of a Non-Authorized request, but those no longer work.

**Comment by woutor** [comment]
I succeeded searching for items using the [Client Credentials Flow](http://spotipy.readthedocs.io/en/latest/#client-credentials-flow)

**Comment by kotutuloro** [comment]
Yup! I think Spotipy's docs should be changed to reflect that.

**Comment by fhopp** [comment]
If you want the examples to work with updated authorisations, here's what you need to do: 

1.) Get a CLIENT ID and CLIENT SECRET (https://developer.spotify.com/web-api/tutorial/)
2.) According to the Client Credentials Flow, modify the example scripts in the following manner: 

Line 3: from spotipy.oauth2 import SpotifyClientCredentials
Line 4: client_credentials_manager = SpotifyClientCredentials(client_id='YOUR ID', client_secret='YOUR SECRET ID')

At the end of a script, modify the sp = spotipy.Spotify() to 
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

Then it /should/ work.

**Comment by ritiek** [comment]
Just wanted to say that one can also authorize API calls without going through the headache of verifying the redirect url after every while. Just add something like this to your script:

```
import spotipy
import spotipy.oauth2 as oauth2

credentials = oauth2.SpotifyClientCredentials(
        client_id=client_id,
        client_secret=client_secret)

token = credentials.get_access_token()
spotify = spotipy.Spotify(auth=token)
```

**Comment by JessicaMartini212887** [comment]
Thank you very much

**Comment by JeanPaiva42** [comment]
> First of all create an app on https://beta.developer.spotify.com/dashboard/ and note down your _Client ID_, _Client Secret_ and _Redirect URI_.
> 
> To authorize your API calls without going through the headache of verifying the redirect URL. Just make use of the `oauth2` method:
> 
> ```python
> import spotipy
> import spotipy.oauth2 as oauth2
> 
> credentials = oauth2.SpotifyClientCredentials(
>         client_id=client_id,
>         client_secret=client_secret)
> 
> token = credentials.get_access_token()
> spotify = spotipy.Spotify(auth=token)
> ```
> 
> Note that this method does not need any scope/redirect url and will only allow access to publicly available information.
> 
> To gain access to user's personal information, you need to use the old school `util` method (requires verifying of redirect URL):
> 
> ```python
> import spotipy
> import spotipy.util as util
> 
> token = util.prompt_for_user_token(
>         username=your_username,
>         scope=scope,
>         client_id=client_id,
>         client_secret=client_secret,
>         redirect_uri=redirect_uri)
> 
> spotify = spotipy.Spotify(auth=token)
> ```
> 
> Learn more about using scopes from the [official docs](https://developer.spotify.com/web-api/using-scopes).

Damn, I'm late to the party but is there a way I can get the user private info without pasting the URL? I'm trying to buiild an app but this is killing me, lol.

**Comment by n-ivanov** [comment]
> Damn, I'm late to the party but is there a way I can get the user private info without pasting the URL? I'm trying to buiild an app but this is killing me, lol.

@JeanPaiva42 There's a PR (#243) that handles this by using a local http server to listen to the redirect and get the access code. I took a similar approach in my application to handle this issue before noticing the PR and it works very well.

**Comment by aced125** [comment]
> If you want the examples to work with updated authorisations, here's what you need to do:
> 
> 1.) Get a CLIENT ID and CLIENT SECRET (https://developer.spotify.com/web-api/tutorial/)
> 2.) According to the Client Credentials Flow, modify the example scripts in the following manner:
> 
> Line 3: from spotipy.oauth2 import SpotifyClientCredentials
> Line 4: client_credentials_manager = SpotifyClientCredentials(client_id='YOUR ID', client_secret='YOUR SECRET ID')
> 
> At the end of a script, modify the sp = spotipy.Spotify() to
> sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)
> 
> Then it /should/ work.

Thank you very much, this worked for me.
