### ISSUE TITLE
get Url of any particular request

### ISSUE THREAD

**Issue by VictorXLR** [plamere/spotipy#200]
Hi,
I noticed that you cant get the specific url from a search input. not the spotify url
```spotify:artist:3jOstUTkEu2JkjvRdBA5Gu``` but the http url. I am very new to this so this might also be from my end.
I mean like if i could get the spotify url for any song, playlist or album.
Thanks

**Comment by steinitzu** [comment]
HTTP URL is under `external_urls` on all objects that support it (artists, playlists, tracks, albums, etc)  
e.g.  
```python
artist = spotify.artist('3jOstUTkEu2JkjvRdBA5G)
url = artist['external_urls']['spotify']
print(url)
# https://open.spotify.com/artist/3jOstUTkEu2JkjvRdBA5G
```

https://developer.spotify.com/web-api/object-model/#artist-object-simplified
