### ISSUE TITLE
Track limit in user_playlists?

### ISSUE THREAD

**Issue by DylanMeeus** [plamere/spotipy#203]
Hello,

It seems like I only get 100 tracks from playlists of a user when using the following line:
`self.spotify.user_playlist(self.username, playlist['id'],fields="tracks,next")`

The API does not mention setting a limit. Is that something that could limit that request?

(if you want to see the full code, it is here: [full code](https://github.com/DylanMeeus/Spotify_Playlist_Analyser))

EDIT:

It seems like there is a method `user_playlist_tracks` which should do what I want to. I was following an example from the 'readthedocs' page though. Which misguided me a bit. 

Nontheless, it is interesting that it is capped at 100 and that you can not change that. Maybe worth looking into anyway.

**Comment by wesleybratt** [comment]
I know inserting into playlists is capped at 100, I'll try and verify this.

**Comment by wesleybratt** [comment]
nope your totally right, only brings back 100.

**Comment by gwynnebaer** [comment]
Spotify itself sets the 100 track limit for input/output. It's not easy to find this information, but it's listed here: https://developer.spotify.com/web-api/get-playlists-tracks/ (look for the "limit" field).

To get a full listing of tracks in a playlist, one must loop through the list using the "next" set of tracks. The file in the distribution named "[user_playlists_contents.py](https://github.com/plamere/spotipy/blob/master/examples/user_playlists_contents.py)" has an example of how to do this.

**Comment by stephanebruckert** [comment]
Thanks @gwynnebaer
