### ISSUE TITLE
Write Authorization (Public Playlists)

### ISSUE THREAD

**Issue by danielgwilson** [plamere/spotipy#208]
Still having issues from the May 29 change over; anyone figure out how to amend this library to auth correctly? 401 error.

**Comment by sot-iris** [comment]
let me know if this helps: https://sotiriskakanos.com/2017/08/05/using-spotifys-web-api-with-python/

**Comment by danielgwilson** [comment]
Hi Sotiris—thanks for the link, very clear post. I've got search and public read working through the client credentials flow, but I need write access to playlists. That requires the auth flow which I haven't gotten to work (401 error). Any thoughts?

**Comment by sot-iris** [comment]
I'll write another post and link it here by end of play :)

**Comment by sot-iris** [comment]
let me know how you get on https://sotiriskakanos.com/2017/08/09/getting-started-with-authorisation-code-flow-and-spotipy/
