### ISSUE TITLE
AttributeError: 'SpotifyClientCredentials' object has no attribute 'is_token_expired'

### ISSUE THREAD

**Issue by ritiek** [plamere/spotipy#209]
I successfully authenticated via `spotipy.oauth2.SpotifyClientCredentials()`. The docs say [calling method ](http://spotipy.readthedocs.io/en/latest/#spotipy.oauth2.SpotifyClientCredentials.is_token_expired) `is_token_expired()` on it should be valid but it gives:

> AttributeError: 'SpotifyClientCredentials' object has no attribute 'is_token_expired'

However, calling ` get_access_token()` works fine.

What is wrong with `is_token_expired()`?

**Comment by RoblesCoulter** [comment]
Hello, I'm having the same issue. Were you able to solve it @ritiek ?

**Comment by ritiek** [comment]
I am using a `try` `except` block as an alternative to know if the token expired while the code is running and generate a new one if it did.

```
try:
    # usual code involving spotipy
except spotipy.oauth2.SpotifyOauthError:
    token = new_token()
    spotify = spotipy.Spotify(auth=token)
```

**Comment by ritiek** [comment]
As a matter of fact, I just noticed that `is_token_expired()` is available only when using `spotipy` directly from the master branch.

It can be used with:

```
import spotipy.oauth2 as oauth2

creds = oauth2.SpotifyClientCredentials(client_id, client_secret)
token = creds.get_access_token()
oauth2.is_token_expired(creds.token_info)
```

As an alternative for old versions on pip, just make a small function (copying this from the master branch):

```
import spotipy.oauth2 as oauth2
import time

def is_token_expired(token_info):
    now = int(time.time())
    return token_info['expires_at'] - now < 60

creds = oauth2.SpotifyClientCredentials(client_id, client_secret)
token = creds.get_access_token()
is_token_expired(creds.token_info)
```

Closing this issue.
