### ISSUE TITLE
Old version on pip/easy_install installation

### ISSUE THREAD

**Issue by dransho1** [plamere/spotipy#211]
I believe there is an issue with spotipy `pip` and `easy_install` installation. I installed the library today through both install methods, but both came with old versions of the source code. I noticed some lines in `spotipy/oauth2.py` that were different from the most current version. The discrepancy is from a change made in a Jan 2017 [commit](https://github.com/plamere/spotipy/commit/4f15a6f07ef3abad386eb81db09c539e25011b70#diff-6199691643e8741165f15d90d5e4e6c8) that fixed a scope issue. My installation versions with `pip` and `easy_install` both did not have this fix.

This could easily just be me and my own mistakes, but I wanted to see if others were having a similar issue. Other than this I've been loving the API wrapper :)

**Comment by seelengut** [comment]
I'm seeing the same discrepancies on my end. For instance, the API devices() from client.py is not present when using pip. pip states that version is 2.4.4, which would be the most recent one.

**Comment by tonyravioli** [comment]
+1 on this. Spent a while trying to debug why a simple function wasn't working... Turns out it doesn't exist in my version of the code. I ran `pip3 install spotipy` to install it.

**Comment by hypecycle** [comment]
Same here. `pip3 install spotipy` echoes `Successfully installed spotipy-2.4.4`. Anyway, `spotipy.VERSION` in python3.5 produces `2.0.1`.

**Comment by nicolewagoner** [comment]
Ah! This just bit me too.. Glad I'm not alone. Would be super awesome to get a more up-to-date version 😄 

These are the steps that I took:
- Go to https://pypi.python.org/pypi/spotipy/2.4.4 
- Download and untar package and navigate to location in conosole
- `cat Downloads/spotipy-2.4.4/spotipy/__init__.py`  gives output `VERSION='2.0.1'`
- Also note oauth2.get_authorize_url() doesn't support state or show_dialog parameters in this version, though they are listed in the repo

**Comment by Kalaborative** [comment]
+1 on this. It seems a lot of the newer functions are missing, too. Keep running into `AttributeError`s because of this. Will install this manually.

**Comment by tiosolid** [comment]
+1. Some playlist function prototypes are missing some newer parameters (like description) but the repository code already have them

**Comment by wbolster** [comment]
it would be great if @plamere could tag a new release (no git tags currently?) and upload a new version to pypi so that other can enjoy the goodies from the latest version of the code.

**Comment by tgurr** [comment]
I second that request, right now distributions have to add various patches to have a proper spotipy package. Please do a new release on pypi that we can package.

**Comment by fuzzwell** [comment]
+1 here.

**Comment by poiley** [comment]
+1

**Comment by AKShaw** [comment]
+1, both pip and a manual install from the tar.gz on pypi install 2.0.1, even though the pypi version is called "spotipy-2.4.4". Keep getting AttributeErrors as a result.

**Comment by acmiyaguchi** [comment]
If you're running into issues still, you can install the package directly from the github repo. 

`pip install git+https://github.com/plamere/spotipy.git --upgrade`

**Comment by hmhrex** [comment]
+1 - Would love a new version to pull from pypi!

@acmiyaguchi - Thanks for the work around! That will work for me for the time being.

**Comment by R3vpanda** [comment]
Bump would like to see this working let me know if i can help!

**Comment by JessicaMartini212887** [comment]
I, I read this issue and I have tried to solve the problem.  Running !pip freeze it results that the spotipy version is 2.4.4, so why it doens't recognize the new functions as current_user_recently_played ???? Help me please!

**Comment by xuewill** [comment]
+1 ! I have the 2.4.4 verison but it still does not work for me 👎

**Comment by migel210** [comment]
+1, I had the same issue. [This](https://stackoverflow.com/questions/47028093/attributeerror-spotify-object-has-no-attribute-current-user-saved-tracks) fix worked for me

**Comment by zhammer** [comment]
@plamere Hey plamere. What's the best way to push the current spotipy repo to pypi? Even if there's no future maintenance, it'd be great to update the pypi package!

**Comment by rperkett-r7** [comment]
@zhammer Do you know how to solve these above issues by any chance?

I still get the following - 

 File "testing.py", line 50, in <module>
    devices = sp.devices()
AttributeError: 'Spotify' object has no attribute 'devices'

**Comment by jorgeikens** [comment]
This issue isn't fixed, still getting the wrong version on pip. Any chance this will ever get fixed?

**Comment by shillshocked** [comment]
Can't change descriptions anymore.

**Comment by alhockly** [comment]
pypi package is still outdated ;(

**Comment by felix-hilden** [comment]
As this is a fairly popular thread as well, it might be worth mentioning that several updated / rewritten versions of Spotipy are [brewing](https://github.com/plamere/spotipy/issues/387#issuecomment-522219646).

**Comment by stephanebruckert** [comment]
Just released [2.5.0](https://github.com/plamere/spotipy/releases/tag/2.5.0) which contains everything from 2.4.4 as well as everything that was merged to master but never released

    pip install spotipy --upgrade

If doing so, also make sure to remove `git+https://github.com/plamere/spotipy.git` from your `requirements.txt`
