### ISSUE TITLE
Can't remove a track from a playlist

### ISSUE THREAD

**Issue by drsm79** [plamere/spotipy#22]
It seems there's no way to remove a track from a playlist (https://developer.spotify.com/web-api/remove-tracks-playlist/) which is unfortunate, though maybe I missed a call.  Will try to implement this weekend...

**Comment by MatthiasHerp** [comment]
I'm currently writing a code to delete specific tracks out of a Spotify Playlist I created, and thus that I own. But somehow I am having Issues with the token, although I am using the 'playlist-modify-public' token which should allow me to delete tracks in my own playlists.
Would greatly appreciate your help :)

I get this error message by the link in the error code:
{
"error": {
"status": 401,
"message": "No token provided"
}
}

My Code:
[Spotipy_delete_tracks.txt](https://github.com/plamere/spotipy/files/4431170/Spotipy_delete_tracks.txt)


Spotipy Authorization Scopes overview:
https://developer.spotify.com/documentation/general/guides/scopes/#playlist-modify-public

**Comment by stephanebruckert** [comment]
@MatthiasHerp if your playlist is private, use the scope `playlist-modify-private`

**Comment by MatthiasHerp** [comment]
> @MatthiasHerp if your playlist is private, use the scope `playlist-modify-private`

Yes, I checked that, I put it privat and changed the scope as you suggested, and put it back public and used the public scope

**Comment by stephanebruckert** [comment]
Hmm the error is not a 401 but an 403 and says "You cannot remove tracks from a playlist you don't own.".

Can you make sure your token has the same owner as your playlist? 

Ideally please feel free to create a new issue so other people can see it and potentially help you

**Comment by MatthiasHerp** [comment]
Okay, I checked it but somehow it doesn't work.
I made the playlist private and I am able to get the track names so the token should be valid.
I'll make a new issue
