### ISSUE TITLE
Authentication Issues

### ISSUE THREAD

**Issue by mbabatunde** [plamere/spotipy#221]
Hi,

I'm currently experiencing issues of how to authenticate my app on Spotify with Spotipy? Any suggestions on how to get authentication working?

**Comment by ritiek** [comment]
#194 might be of some help.

**Comment by Hurstwood** [comment]
There is a typo in the documents.

`util.prompt_for_user_token(username,scope,client_id='your-app-redirect-url',client_secret='your-app-redirect-url',redirect_uri='your-app-redirect-url')`

Should be...

`util.prompt_for_user_token(username,scope,client_id='your-app-client-id',client_secret='your-app-client-secret',redirect_uri='your-app-redirect-url')`

**Comment by stephanebruckert** [comment]
Typo is fixed, closing
