### ISSUE TITLE
Authorisation Code Flow Issues

### ISSUE THREAD

**Issue by stingrai24** [plamere/spotipy#225]
I have been following the documentation at http://spotipy.readthedocs.io/en/latest/ and I have managed to get Client Credentials Flow to work, meaning that I can write code which accesses public areas of Spotify. However, when trying to authorise personal accounts through Authorisation Code Flow, I keep getting the same error: "spotipy.oauth2.SpotifyOauthError: Bad Request" .
I have followed the instructions exactly, so I do not know what I have done wrong. Could someone please help?

**Comment by ritiek** [comment]
It would be much more easier to debug if you were to share your code snippet (of course removing any sensitive data). :smile:

**Comment by stingrai24** [comment]
This is the code and the error I get:

```
import sys
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import spotipy.util as util

username = input("Username: ")
scope = 'user-library-read'

token = util.prompt_for_user_token(username,scope,client_id='b91421647d9c49e99bf256519c223dfa',client_secret='42c39c8bf6b9429daee5935915ed0ff8',redirect_uri='http://localhost/')

if token:
    sp = spotipy.Spotify(auth=token)
    results = sp.current_user_saved_tracks()
    for item in results['items']:
        track = item['track']
        print (track['name'] + ' - ' + track['artists'][0]['name'])
else:
    print ("Can't get token for", username)
```


The error is: 
`spotipy.oauth2.SpotifyOauthError: Bad Request`

**Comment by ritiek** [comment]
Please edit your post to remove your client id and client secret. Be sure to revoke them too.

**Comment by stingrai24** [comment]
Thanks, didn't notice I'd left that in aha! 

Any idea what's causing the error?

**Comment by stingrai24** [comment]
Never mind, found the error! It was to do with my terminal being configured to open a link once its pasted. If I typed the first part of the link then paste the rest, it doesn't recognise it as a link and everything works fine!
