### ISSUE TITLE
Now playing example

### ISSUE THREAD

**Issue by Bluscream** [plamere/spotipy#226]
Could you provide a example py script how to obtain infos about the song currently played by the user?

**Comment by ritiek** [comment]
Here is a quick one:

```
import spotipy
import spotipy.util as util
 
scope = 'user-read-playback-state'
token = util.prompt_for_user_token(username, scope, client_id=client_id, client_secret=client_secret, redirect_uri=redirect_uri)

spotify = spotipy.Spotify(auth=token)
current_track = spotify.current_user_playing_track()

print(current_track)
```

**Comment by Bluscream** [comment]
Does this use the local client? It should be compatible with the native windows/linux/mac app and the windows store version

**Comment by joeborrello** [comment]
I just tried running that same script with my own credentials added and I got an error returned: 'Spotify' object has no attribute 'current_user_playing_track'

Any ideas why that might be happening?

**Comment by adrian-szczepanski** [comment]
It's probably because of issue https://github.com/plamere/spotipy/issues/211

**Comment by mitchellpalermo** [comment]
This is still happening to me even with 2.4.4 installed. Funny enough when I compile in my text editor(Atom) it works fine. But when I run this from the terminal, it gives me that  same error that @joeborrello got.

**Comment by migel210** [comment]
@mitchellpalermo if you run the code spotipy.VERSION does it return 2.0.1 or 2.4.4? I think the code here isn't up to date. [This]https://stackoverflow.com/questions/47028093/attributeerror-spotify-object-has-no-attribute-current-user-saved-tracks) is what fixed it for me

**Comment by Bluscream** [comment]
I just got spotify from https://github.com/plamere/spotipy/archive/master.zip but

```
>>> import spotipy 
>>> spotipy.VERSION 
'2.0.1'
```

**Comment by stephanebruckert** [comment]
Closing as everything looks answered or depends on another issue
