### ISSUE TITLE
Getting started "non-auth" example requires auth

### ISSUE THREAD

**Issue by BryanDiLaura** [plamere/spotipy#227]
The example in the [getting started documentation](http://spotipy.readthedocs.io/en/latest/#getting-started) is claimed to not require authentication. When running that code, however, I receive a 401 (no token provided).

Looking at [Spotify's web api](https://developer.spotify.com/web-api/search-item/) it looks like an authentication token is indeed required to search. 

I would suggest using a different code snippet for the getting started section in the documentation.

**Comment by kotutuloro** [comment]
( Linking this to related issue #194 )
