### ISSUE TITLE
Friend's feed

### ISSUE THREAD

**Issue by goldmouse** [plamere/spotipy#228]
Is it possible to capture a list of songs played by a user from the friend feed?

**Comment by ritiek** [comment]
AFAIK, the authorized user can only know his currently playing song. So, I don't think this is possible due to security reasons.

**Comment by goldmouse** [comment]
Thanks, I agree but when using a desktop app a user can see what his friends are listening to. So in theory the authorized user should be able to create this from **his friends only**?.

**Comment by stephanebruckert** [comment]
Indeed it's not available on the web API side
