### ISSUE TITLE
Spotify Token Not Found

### ISSUE THREAD

**Issue by haroldcrow2001** [plamere/spotipy#236]
Hello! I can't seem to be able to find my Spotify token anywhere. I don't even know where to look.
I've read the docs, and I can't understand where the token is located. I've created an application, and I have a client secret and client id, but no token. Please Help!!!

**Comment by ritiek** [comment]
Your temporary token (valid for one hour) is generated when you authenticate yourself using your client id and client secret. Check out #194 to learn more about authentication.
