### ISSUE TITLE
How do I get every track of a playlist?

### ISSUE THREAD

**Issue by CiniqueL** [plamere/spotipy#246]
There are no code samples for this action, and I tried using an example for writing track names to a text file, but I noticed I am sometimes missing tracks if the playlist is over 100 tracks.

i.e. one playlist said the total was 106 tracks, but I only returned 100. But, I was able to get one playlist of over 800 tracks.

**Comment by ritiek** [comment]
Not sure about your code but I've been using this for a long time and has been working fine for me so far:

<details>

```python
import spotipy
import spotipy.oauth2 as oauth2

def generate_token():
    """ Generate the token. Please respect these credentials :) """
    credentials = oauth2.SpotifyClientCredentials(
        client_id=client_id,
        client_secret=client_secret)
    token = credentials.get_access_token()
    return token


def write_tracks(text_file, tracks):
    with open(text_file, 'a') as file_out:
        while True:
            for item in tracks['items']:
                if 'track' in item:
                    track = item['track']
                else:
                    track = item
                try:
                    track_url = track['external_urls']['spotify']
                    file_out.write(track_url + '\n')
                except KeyError:
                    print(u'Skipping track {0} by {1} (local only?)'.format(
                            track['name'], track['artists'][0]['name']))
            # 1 page = 50 results
            # check if there are more pages
            if tracks['next']:
                tracks = spotify.next(tracks)
            else:
                break


def write_playlist(username, playlist_id):
    results = spotify.user_playlist(username, playlist_id,
                                    fields='tracks,next,name')
    text_file = u'{0}.txt'.format(results['name'], ok='-_()[]{}')
    print(u'Writing {0} tracks to {1}'.format(
            results['tracks']['total'], text_file))
    tracks = results['tracks']
    write_tracks(text_file, tracks)


token = generate_token()
spotify = spotipy.Spotify(auth=token)

# example playlist
write_playlist('doldher', '0B4jhlB6QUGHzY8i3rEwTt')
```

</details>

**Comment by gawaineo** [comment]
@CiniqueL 

I believe the limit for the amount of tracks to be returned is 100 (check out the min and max track limit at the link below).  
Source: https://developer.spotify.com/web-api/get-playlists-tracks/

I just wrote some code related to you question, below is an example:
```
spot = Spotify()
playlist_tracks = spot.user_playlist_tracks(user_id, playlist_id, fields='items,uri,name,id,total', market='fr')
```
Here's the link to the above method being called: http://spotipy.readthedocs.io/en/latest/#spotipy.client.Spotify.user_playlist_tracks

**Comment by CiniqueL** [comment]
Thank you both for your answers. 

I was able to find what I needed on StackOverflow. I'm still working out some other bugs in my script, but the code I'm using is:

 ```
       for uri in pl_ids:

            results = self.sp.user_playlist_tracks(uri.split(':')[2], uri.split(':')[4])
            tracks = results['items']

            # Loops to ensure I get every track of the playlist
            while results['next']:
                results = self.sp.next(results)
                tracks.extend(results['items'])

        return tracks
```

I think the problem was that I was appending my list instead of extending it.

**Comment by AtomicNess123** [comment]
>       for uri in pl_ids:
> 
>            results = self.sp.user_playlist_tracks(uri.split(':')[2], uri.split(':')[4])
>            tracks = results['items']
> 
>            # Loops to ensure I get every track of the playlist
>            while results['next']:
>                results = self.sp.next(results)
>                tracks.extend(results['items'])
> 
>        return tracks
> ```
> 
> I think the problem was that I was appending my list instead of extending it.

Thank you! How to modify this to just get the id of the tracks?
I tried  `tracks = results['items'][0]['track']['id'] `unsuccessfully.

**Comment by marcdubois71450** [comment]
>`def get_playlist_ids(username,playlist_id):
    r = sp.user_playlist_tracks(username,playlist_id)
    t = r['items']
    ids = []
    while r['next']:
        r = sp.next(r)
        t.extend(r['items'])
    for s in t: ids.append(s["track"]["id"])
    return ids`

**Comment by kunal-jangid** [comment]
> With that no limit!
> 
> username => user id, in profile link playlist id => in playlist link
> 
> ```
> def get_playlist_ids(username,playlist_id):
>     r = sp.user_playlist_tracks(username,playlist_id)
>     t = r['items']
>     ids = []
>     while r['next']:
>         r = sp.next(r)
>         t.extend(r['items'])
>     for s in t: ids.append(s["track"]["id"])
>     return ids
> ```

I got a doubt, what's username here? Like let's say I want to use random playlist as playlist id. Then what would I use as a username? Would it be mine or would it the creator of the playlist?

**Comment by stephanebruckert** [comment]
`user_playlist_tracks` is deprecated, you need to use `playlist_tracks` (without username)
