### ISSUE TITLE
Login/Logout

### ISSUE THREAD

**Issue by MoeMixMC** [plamere/spotipy#249]
How do I log the user out and/or bring up the dialogue box to login as a different user than the cached one? The docs show that the parameter is in the SpotifyOAuth#get_authorize_url method but when I set the parameter to True I get an unexpected keyword argument error...

**Comment by daks** [comment]
When you get your authorization token it's stored in .cache-<username>.
Remove this file and you should get the dialogue box.

**Comment by stephanebruckert** [comment]
@daks's answer seems correct. Closing for now as the issue is old, but feel free to reopen if needed.
