### ISSUE TITLE
read current volume?

### ISSUE THREAD

**Issue by tatoosh** [plamere/spotipy#252]
With the help of the docu i can set my spotify volume right now in percentage.
```   results = sp.volume(volume) ```
but i did not get an result - is there also a get method for reading the current volume?
Thx Tatoosh

**Comment by ritiek** [comment]
I don't think this is currently possible. There is no mention of anything related in [official docs](https://developer.spotify.com/web-api/endpoint-reference/) either.

**Comment by tatoosh** [comment]
THX @ritiek for linking. I think i can solve it by the devices command: https://developer.spotify.com/web-api/get-a-users-available-devices/

**Comment by ritiek** [comment]
Ah yes. You're right.

**Comment by gawaineo** [comment]
@tatoosh you can also get the current playback info `http://spotipy.readthedocs.io/en/latest/#spotipy.client.Spotify.current_playback`

Here's the doc reference: https://developer.spotify.com/web-api/get-information-about-the-users-current-playback/

You can look at the "device" key in the dict that's returned.

**Comment by tatoosh** [comment]
THX @gawaineo, good solution and the device key delivers good information!
