### ISSUE TITLE
rspotify, a Rust implementation heavily inspired by spotipy 

### ISSUE THREAD

**Issue by ramsayleung** [plamere/spotipy#258]
Hey Paul, first of all, thanks for your awesome work,  with inspiration of spotipy, I create another Spotify API wrapper implemented in Rust -- [rspotify](https://github.com/samrayleung/rspotify). I open this issue just to express my appreciation and ask for your permission that may I use your document about Spotify API wrapper :)

**Comment by stephanebruckert** [comment]
This is MIT licensed so feel free to re-use everything you want from this repo
