### ISSUE TITLE
 How can I get the authorization? I'm a beginner

### ISSUE THREAD

**Issue by JessicaMartini212887** [plamere/spotipy#267]
Hi, I'm Jessica and I'm using Spotipy for my graduation. I have a question. After downloading spotipy and requests-master, I have created my Spotify App on Developer. I have ma Client ID and my secret key. Now how can I get the authorization?

**Comment by ritiek** [comment]
Check out #194.

**Comment by JessicaMartini212887** [comment]
Ok I think that I've done it! I'm using Python on Anaconda Tool, version 2.7. The console has returned me this output: 

> User authentication requires interaction with your
            web browser. Once you enter your credentials and
            give authorization, you will be redirected to
            a url.  Paste that url you were directed to to
            complete the authorization.
               Enter the URL you were redirected to:

I've matched my app with my account and then the console return a white line...

Now Can I have access to Spotify user data???

**Comment by smoreface** [comment]
@JessicaMartini212887 you might be running into this issue: https://stackoverflow.com/questions/32956443/invalid-redirect-uri-on-spotify-auth

you have to specify a redirect URL (it can just be http://localhost/) but you also have to whitelist it with your app. good luck!

**Comment by Plopkonijn** [comment]
![image](https://user-images.githubusercontent.com/2047097/41190724-64bdd03c-6be4-11e8-98c0-6c283cc844f7.png)
the localhost thing is not working...
URL just to show you its not right
https://accounts.spotify.com/authorize?client_id=3bc077932594438db9329051e4a86392&response_type=code&redirect_uri=+http%3A%2F%2Flocalhost%2F&scope=playlist-modify-private

**Comment by sanchitcop19** [comment]
Is there a way to avoid having to copy the redirect uri? Not sure how this works 😅

**Comment by stephanebruckert** [comment]
@smoreface seems correct

@Plopkonijn see https://github.com/plamere/spotipy/issues/298
