### ISSUE TITLE
Search doesn't appear to support field filters

### ISSUE THREAD

**Issue by InconsolableCellist** [plamere/spotipy#268]
The Spotify query API permits for field filters, which allow you to key a search down to return more specific results:

>Field filters: By default, results are returned when a match is found in any field of the target object type. Searches can be made more specific by specifying an album, artist or track field filter. For example: The query q=album:gold%20artist:abba&type=album returns only albums with the text “gold” in the album name and the text “abba” in the artist name.

https://beta.developer.spotify.com/documentation/web-api/reference/search/search/

If you try to construct a query to the generic search() function and pass in a filter as part of your q parameter, the call to request() will URI encode it rather than treat it as additional parameters, mangling the query.

**Comment by InconsolableCellist** [comment]
I found a workaround that I didn't think previously worked, due to a typo. You can use the q parameter in the generic search() function to compose the filter yourself. For example:

q set to "steambreather artist:mastodon" will work.

I previously ruled this out by trying to compose it like "steambreather&artist:mastdon"

Functions could be added to support this so that the end user doesn't have to compose the filter himself, however, as currently this workaround makes the consumer responsible for making some Spotify-API-specific code himself.

**Comment by stephanebruckert** [comment]
Yes everyone is free to build custom queries. A first step could be to document how to write a query in the spotipy doc.
