### ISSUE TITLE
Timeline for new version

### ISSUE THREAD

**Issue by hmhrex** [plamere/spotipy#270]
There hasn't been a new release of spotipy in over a year despite there being many commits since, including new methods such as `user_follow_users` and `user_follow_artists` (#250). At what point will a new version be released that includes these changes? Or is there possibly a new installation method (in place of pip) that needs documented?

**Comment by ritiek** [comment]
+1. Same as #211 though.

**Comment by hmhrex** [comment]
@ritiek Thanks for referencing that! I figured someone might have already brought this up at some point.

**Comment by stephanebruckert** [comment]
Marking as duplicate, let's discuss here https://github.com/plamere/spotipy/issues/293
