### ISSUE TITLE
Spotipy: User_create_playlist - Method Not Allowed for url

### ISSUE THREAD

**Issue by jfaul** [plamere/spotipy#273]
I'm trying to figure out why the user_create_playlist method is not allowed for my url.

Here is part of my code showing how I'm authenticating my app and code I'm using to run the method:

    username = 'my-username'
    token = util.prompt_for_user_token(username = username,
                                        scope = 'playlist-modify-public'
                                        client_id='my-spotify-client-id',
                                        client_secret='my-spotify-client-secret-id',
                                        redirect_uri='https://developer.spotify.com/')
    spotifyObject = spotipy.Spotify(auth=token)    
    playlist_name = "Test Playlist"
    playlist_description = "This is a test playlist."
    playlists = spotifyObject.user_playlist_create(username, playlist_name, playlist_description)
    pprint.pprint(playlists)

Do you know why I am getting the following error message?

(Traceback (most recent call last):
  File "C:\Users\....\spotipy\client.py", line 121, in _internal_call
    r.raise_for_status()
  File "C:\Users\....requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://api.spotify.com/v1/users/'username'/playlists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\....\SpotifyTest.py", line 108, in <module>
    main()
  File "C:\Users\....\SpotifyTest.py", line 53, in main
    playlists = spotifyObject.user_playlist_create(username, playlist_name, playlist_description)
  File "C:\Users\....\spotipy\client.py", line 415, in user_playlist_create
    return self._post("users/%s/playlists" % (user,), payload=data)
  File "C:\Users\.....\spotipy\client.py", line 180, in _post
    return self._internal_call('POST', url, payload, kwargs)
  File "C:\Users\....\spotipy\client.py", line 129, in _internal_call
    -1, '%s:\n %s' % (r.url, 'error'), headers=r.headers)
spotipy.client.SpotifyException: http status: 405, code:-1 - https://api.spotify.com/v1/users/'username'/playlists:
 error)

**Comment by ritiek** [comment]
Check out https://github.com/plamere/spotipy/issues/242#issuecomment-354764118.

**Comment by mmasque** [comment]
Getting the same exact issue. Any updates?

**Comment by stephanebruckert** [comment]
This should be fixed with version 2.5.0, just do:

    pip install spotipy --upgrade
