### ISSUE TITLE
current_user_playing_track(), current_playback() and currently_playing(): Cannot iterate through response: Data structure issue potentially?

### ISSUE THREAD

**Issue by Dextroz** [plamere/spotipy#275]
When using current_user_playing_track(), current_playback() and currently_playing() all 3 responses return a dict which is fine. However, the issue lies when I try to pull information about the artist.
Example response:
![screen shot 2018-04-15 at 15 55 36](https://user-images.githubusercontent.com/25749668/38779816-8f48a3e4-40c5-11e8-840b-38fe2f46f2b5.png)

For each function response, when I pull the 'artists' key. It is a list data structure; even though it also has dictionary syntax inside of it. So my question is, why is it a list and not just a nested dictionary like the rest of the response. The list data structure makes it extremely difficult to pull information, as the 'list' cannot be iterated through as it is seen by Python as being one large list entry.

I can pull the album name and track name easily as they are not inside a list within the response however, I cannot get the artist name due to this problem.

I am using the latest version of Spotipy. Downloaded and unpacked from repo download.

**Comment by ritiek** [comment]
Is there a problem with indexing the artists list `['artists'][0]['name']`?

**Comment by Dextroz** [comment]
Oh for goodness sake, very noob mistake by me. You're solution works. Even more noob mistake is that I have used that indexing in my project before; this solution completely slipped my mind. Thank you @ritiek. Shows how I should have looked at my previous work to find a solution first before opening an issue. Many Thanks. Closed.

The code:
![screen shot 2018-04-16 at 15 49 06](https://user-images.githubusercontent.com/25749668/38816322-bbec3ae6-418d-11e8-8f1d-05f9d930c375.png)

**Comment by ritiek** [comment]
@Dextroz No problem! Glad you figured out!

**Comment by migel210** [comment]
when I use currently_playing it says "Spotify has no attribute currently_playing". What am I doing wrong?

**Comment by ritiek** [comment]
@migel210 Hi, you're probably using the older version on PyPi. You can install the latest development version as mentioned here https://github.com/plamere/spotipy/issues/211#issuecomment-369863112. You should then be able to use newer unreleased methods like `currently_playing` and many more!

**Comment by migel210** [comment]
@ritiek yup, that was the problem, thanks!

**Comment by migel210** [comment]
@ritiek sorry, where exactly can you get the development version from?
