### ISSUE TITLE
prompt_for_user_token parses url incorrectly

### ISSUE THREAD

**Issue by legosail** [plamere/spotipy#276]
When I run this:
`import spotipy.util as util`

`token = util.prompt_for_user_token('MU_USERNAME', scope='user-library-read', client_id='MY_CLIENT_ID',
                                   client_secret='MY_CLIENT_SECRET', redirect_uri='http://localhost/')`

and insert the url from the browser into the prompt, it incorrectly parses it. The url only had the code value, and not whatever is supposed to come after the `&`. It worked after I added an `&` to the end of my url, and I am not sure if this is unique to me, but it seems like this is an error.

I found the url is parsed in `oauth2.py` line 188, and this is caused because it tries remove everything before the code, and everything after the `&` (including it), but there was no `&`.

**Comment by 76MPaul** [comment]
Idem for me, will try to find another way.

**Comment by mattcole19** [comment]
Have the same issue
