### ISSUE TITLE
Issue with search() method

### ISSUE THREAD

**Issue by JulianFM** [plamere/spotipy#281]
We have had a problem with Spotipy's search() method for a few hours now. It continually returns a 404 error even though it previously returned correct results. What could have happened?

Thanks

**Comment by ritiek** [comment]
Same here. I can't get it to work from [official docs](https://beta.developer.spotify.com/console/get-search-item/?q=tania+bowra&type=artist) either. Maybe we should open a ticket on their repository  https://github.com/spotify/web-api/issues.

**Comment by JulianFM** [comment]
@ritiek 
https://github.com/spotify/web-api/issues/847

**Comment by ritiek** [comment]
Looks like it is now fixed, thanks to their quick response! This can be closed now hopefully.
