### ISSUE TITLE
hide the Request-Response Information printed out, while wanted

### ISSUE THREAD

**Issue by smyrbdr** [plamere/spotipy#282]
Hi,
I asked [this question](https://stackoverflow.com/questions/50142357/how-to-hide-the-request-response-cycle-information-from-the-outputs-in-ipynb-s?) on StackOverflow, and not sure it is an issue related to requests package or another general .ipynb setting. If this is so, excuse me.

So the issue is while I call any function from Spotipy, I first get the long outputs as below printed out each time;

```headers {' #some info here```

```http status 200```

```GET https://api. ... # GET request link here```

```RESP { ... # a lot of (sometimes undesired) output printed here```

This info is sometimes useful. But sometimes we may want to clear them from the outputs.
Something like setting a parameter to silent. Is it possible to hide the above outputs by requests?

**Comment by smyrbdr** [comment]
It is suddenly solved I don't know why and how, after running the kernel multiple times

**Comment by shillshocked** [comment]
Ah, got it to go away with:

`sp.trace = False`
