### ISSUE TITLE
sp.user_playlist_create and user_playlist_change_details has no argument 'description'

### ISSUE THREAD

**Issue by smyrbdr** [plamere/spotipy#283]
Here is what I get after inspecting these functions;

In[ ] `inspect.getargspec(sp.user_playlist_create)`
Out[ ] `ArgSpec(args=['self', 'user', 'name', 'public'], varargs=None, keywords=None, defaults=(True,))`

In[ ] `inspect.getargspec(sp.user_playlist_change_details)`
Out[ ] `ArgSpec(args=['self', 'user', 'playlist_id', 'name', 'public', 'collaborative'], varargs=None, keywords=None, defaults=(None, None, None))`

So it seems not possible to create a playlist with description yet or add a description afterward either.

**Comment by ritiek** [comment]
@zhammer Geez #211. :smile:

**Comment by shillshocked** [comment]
Still not working. Can't update descriptions of playlists anymore.

**Comment by stephanebruckert** [comment]
This should be fixed with version 2.5.0, just do:

    pip install spotipy --upgrade
