### ISSUE TITLE
Problem with current_user_recently_played function

### ISSUE THREAD

**Issue by JessicaMartini212887** [plamere/spotipy#284]
Hi, I write here because I'm working at my thesis and I have a problem with the function current_user_recently_played. I want to create an extension to Spotify which creates personalized playlists on the basis of the timestamp and the features of tracks, so I need to use this function but the response is this:
`AttributeError: 'Spotify' object has no attribute 'current_user_recently_played'`. I have watched client.py and it seems ok, so I can't understand the problem.

How can I solve this? 
Thank you very much

**Comment by gil** [comment]
Check this -> #211

**Comment by conorhennessy** [comment]
I believe this issue should be closed as solution is linked to
