### ISSUE TITLE
Spotipy installation from pip is unupdated?

### ISSUE THREAD

**Issue by stavlocker** [plamere/spotipy#293]
Hello. I've installed spotipy from pip (`pip install spotipy`, as simple as it gets) and for some reason the `spotipy.util.prompt_for_user_token` doesn't have the `cache_path` keyword argument, even though it's there here in the [source code](https://github.com/plamere/spotipy/blob/4c2c1d763a3653aa225c4af848409ec31286a6bf/spotipy/util.py#L22). The [pull request](https://github.com/plamere/spotipy/pull/169) for this was already merged in September 2017. What is the reason for this?

**Comment by ritiek** [comment]
Similar issues with #284, #283, #270, #231, #211. There seems to have been [no release on PyPi since Jan, 2017](https://pypi.org/project/spotipy/#history).

**Comment by stephanebruckert** [comment]
This should be fixed with version 2.5.0, just do:

    pip install spotipy --upgrade
