### ISSUE TITLE
'Spotify' object has no attribute 'devices'

### ISSUE THREAD

**Issue by VrajPatel10** [plamere/spotipy#294]
import spotipy
sp = spotipy.Spotify(auth=token)
devices = sp.devices()
print(devices)

**Comment by stavlocker** [comment]
It's because spotipy isn't updated on pip. Similar issues with #293, #284, #283, #270, #231, #211. 
 > There seems to have been no release on PyPi since Jan, 2017.

Here's an easy [solution](https://github.com/plamere/spotipy/issues/211#issuecomment-369863112) to update it manually.

**Comment by conorhennessy** [comment]
Anyone else coming across this issue in the future, the solution found [here ](https://github.com/plamere/spotipy/issues/211#issuecomment-369863112) gives a solution - posted on the issue #211
