### ISSUE TITLE
'Spotify' object has no attribute 'current_playback'

### ISSUE THREAD

**Issue by rtbishop** [plamere/spotipy#295]
It seems that certain methods are not working. I read other issues and I see that it's a common problem with pip using an outdated version of Spotipy. However, it shows my package version as spotipy-2.4.4 (most recent).

Anyone have any ideas on how I can fix this?

EDIT: It appears I am using the January 2.4.4 which is outdated. Is there a way to force install the most recent version? Sorry if this is a basic question, I haven’t used Python in a very long time..

**Comment by ritiek** [comment]
> It appears I am using the January 2.4.4 which is outdated. Is there a way to force install the most recent version?

You can directly install from latest version on GitHub. Check out https://github.com/plamere/spotipy/issues/211#issuecomment-369863112.
