### ISSUE TITLE
Spotify Api Localhost refusing the connection

### ISSUE THREAD

**Issue by brkaltinn** [plamere/spotipy#296]
I try to connect spotify api but i have some problem.
![adsiz](https://user-images.githubusercontent.com/39861299/40878704-71f891e8-669d-11e8-9897-98bc5907d191.png)  after pressing button i receive an error like this
![adsiz1](https://user-images.githubusercontent.com/39861299/40878710-a03d101a-669d-11e8-847c-7eeb25be3421.png)

How can i solve this problem?
(I am sorry error page is in Turkish but i guess you can understand)

**Comment by stephanebruckert** [comment]
This is good. Copy the URL from the browser (looks like `localhost:8888/callback/?code=....`) and paste it into your terminal.
