### ISSUE TITLE
Authentications simply not working...

### ISSUE THREAD

**Issue by Plopkonijn** [plamere/spotipy#298]
Trying to get it to work. I've done:
SET SPOTIPY_CLIENT_ID=3bc077932594438db9329051e4a86392
SET SPOTIPY_CLIENT_SECRET= "SECRET DUH"
SET SPOTIPY_REDIRECT_URI= http://localhost/

got the following url

https://accounts.spotify.com/authorize?client_id=3bc077932594438db9329051e4a86392&response_type=code&redirect_uri=+http%3A%2F%2Flocalhost%2F&scope=playlist-modify-public

but this returns a "Bad Request" error on running

add_tracks_to_playlist.py plopkonijn 7qOO1XgvujpSNcgGoZNOV1 1eYY6nY4KiKXAT7QIQKyl5

![image](https://user-images.githubusercontent.com/2047097/41190788-31d01b98-6be5-11e8-809f-5b56b1b66bba.png)

**Comment by stephanebruckert** [comment]
Check if https://github.com/plamere/spotipy/issues/194#issuecomment-317192954 or https://github.com/plamere/spotipy/issues/402#issuecomment-573890067 helps
