### ISSUE TITLE
I can't get no device id on Spotify API (even if I have a token)

### ISSUE THREAD

**Issue by OueOue** [plamere/spotipy#308]
Hi, i'm just trying to start a song on Spotify, I found the way to have a token, but now that I ask for my list of devices, it tells me that the Permission is missing
So here is my code : 
_______________________________________________________________________________________________________________
import sys
import spotipy
import spotipy.util as util
username = 'OueOue'
token = util.prompt_for_user_token(username, scope = 'user-modify-playback-state', client_id='MyClientID', client_secret='MySecretID', redirect_uri = 'https://open.spotify.com/browse/featured')
if token:
        print("Token OK")
	sp = spotipy.Spotify(auth=token)
	print("Authentication OK")
	sp.start_playback(device_id = sp.devices(), context_uri = 'spotify:track:7MywASx2OFZngfoORjo1yy', uris = None, offset = None)
	print("SMAH")
else:
	print("Can't get token for %s" % username)
_______________________________________________________________________________________________________________
![errors](https://user-images.githubusercontent.com/41620395/43130362-d59a4dc4-8f36-11e8-8460-213810c1b5de.PNG)
Thank you for your time :)

**Comment by rperkett-r7** [comment]
I doubt it, but tell me if you find the answer to this. Thanks.

**Comment by danitico** [comment]
Same problem

**Comment by OueOue** [comment]
I GOT THE SOLUTION ! 
First connect on spotify on all the devices you would like to use (for example your laptop, mobile phone, and your desktop pc), go here : https://developer.spotify.com/console/get-users-available-devices/

Then ask for a token, do Win+cmd , copy the curl request and paste it in cmd : 
You'll normally get the list of all the devices currently connected to your spotify account.
Now do an array of string (bi-dimensional array of characters {let's call it Dvcs[3][40]}) and fill it with the IDs of your devices, then just do a function in your program that allows you to choose on which device to play the track (like choosing i = 1 or 2 or 3 and then select Dvcs[i][]).
I hope it has been helpful to you guys ! 😄

**Comment by rperkett-r7** [comment]
I wish there was some way to have the token not have to be manually updated every time :<

**Comment by Birath** [comment]
You need to add  `user-read-playback-state` to your scope to read the device id (and other device information).  You can find more information about scopes here: https://developer.spotify.com/documentation/general/guides/scopes/

**Comment by stephanebruckert** [comment]
Looks like it was a scope problem, closing
