### ISSUE TITLE
Documentation: running into "No token provided"

### ISSUE THREAD

**Issue by StefanRickli** [plamere/spotipy#315]
When I try out (copy/paste) the first examples of the [documentation](http://spotipy.readthedocs.io), I run into a "No token provided" error.

I know that Spotify [doesn't allow unauthorized connections anymore](https://developer.spotify.com/community/news/2017/01/27/removing-unauthenticated-calls-to-the-web-api/) so I should be able to get it working very soonish, but it would be nice to see that reflected in your documentation as well - so that a new, curious user like me doesn't hit a python error upon running of the first examples.

Cheers!

**Comment by Jackbaude** [comment]
i have the same issue

**Comment by ritiek** [comment]
The creator of this repo hasn't been active on GitHub lately. #194 contains info to authorize yourself.

**Comment by stephanebruckert** [comment]
Duplicate, closing in favour of https://github.com/plamere/spotipy/issues/194
