### ISSUE TITLE
Best way to prompt_for_user_token if the user's login method is Facebook?

### ISSUE THREAD

**Issue by whoisjuan** [plamere/spotipy#32]
What's the best way to prompt the user to authorize the app and get the user token if the user's preferred method of authorization is Facebook Login. 

I went over the examples and only saw references explaining this for simple, old fashion login but nothing with Facebook login.

Best,

Juan

**Comment by stephanebruckert** [comment]
`prompt_for_user_token` now opens a browser window that allows a Facebook login
