### ISSUE TITLE
After the enter redirected URL, no effects from code

### ISSUE THREAD

**Issue by AlessandroMinervini** [plamere/spotipy#325]
Hi!
I followed the instructions of https://spotipy.readthedocs.io/en/latest/# and i think the authentication was successful.
After the enter of redirected URL i want to try to search an artist and print the results but i have no effects in output, and don't show any error

the code:
```
import spotipy
import spotipy.util as util

#Set token, username
token = util.prompt_for_user_token('xxxxxx', client_id='xxxxxx', client_secret='xxxxxx', redirect_uri='https://www.google.it')

sp = spotipy.Spotify(auth=token)

results = sp.search(q='Arctic Monkeys', limit=20)
for i, t in enumerate(results['tracks']['items']):
    print(' ', i, t['name'])
```

**Comment by Omnitenebris** [comment]
Someone correct me if I'm wrong, this may be because you don't have the scope, this is for the token:

`token = util.prompt_for_user_token('username', 'scope', cient_id...)`

https://developer.spotify.com/documentation/general/guides/scopes/

**Comment by AlessandroMinervini** [comment]
Thanks!
