### ISSUE TITLE
sp.next_track() :  Not available for the current user

### ISSUE THREAD

**Issue by AlessandroMinervini** [plamere/spotipy#328]
Hi everyone,
i'm implementing a simple application with spotipy.
I want skip to the next track or pause, but i've this error in output:

spotipy.client.SpotifyException: http status: 403, code:-1 - https://api.spotify.com/v1/me/player/next:
 Not available for the current user

My code is here:

`import os
import spotipy
import spotipy.util as util
from json.decoder import JSONDecodeError

username = 'myUserCode'
client_id = 'xxxxxxxxxxxx'
client_secret = 'xxxxxxxxxxxxx'
redirect_uri = 'https://www.xxxx.com/'
scope = 'user-modify-playback-state'

try:
    token = util.prompt_for_user_token(username, scope, client_id, client_secret, redirect_uri)
except (AttributeError, JSONDecodeError):
    os.remove(f".cache-{username}")
    token = util.prompt_for_user_token(username, scope, client_id, client_secret, redirect_uri)

sp = spotipy.Spotify(auth=token)
current = sp.next_track()`

**Comment by qqrs** [comment]
@AlessandroMinervini 

One thing you might check:

https://developer.spotify.com/documentation/web-api/reference/player/skip-users-playback-to-next-track/

> If the user making the request is non-premium, a 403 FORBIDDEN response code will be returned.
