### ISSUE TITLE
Can't search with > 1 query field

### ISSUE THREAD

**Issue by acannon828** [plamere/spotipy#33]
```
In [11]: sp.search('track:Unbelievers+artist:Vampire Weekend', type='track', limit=1)
Out[11]:
{u'tracks': {u'href': u'https://api.spotify.com/v1/search?query=track%3AUnbelievers%2Bartist%3AVampire+Weekend&offset=0&limit=1&type=track',
  u'items': [],
  u'limit': 1,
  u'next': None,
  u'offset': 0,
  u'previous': None,
  u'total': 0}}
```

Pointing a browser to the above link in the `'href'` field and replacing the `%2B` with a `+` [returns a populated track object](https://api.spotify.com/v1/search?query=track%3AUnbelievers+artist%3AVampire+Weekend&offset=0&limit=1&type=track), so I don't think the conversion from `+` to `%2B` that's happening somewhere along the `Spotipy.search` call stack should be happening...can it be avoided?

I also noticed there were no search calls in the examples that specified > 1 field.

**Comment by nicangeli** [comment]
:+1: this
Looks like you can work around it with:
```
sp.search(q='track:Unbelievers AND artist:Vampire Weekend', type='track', limit=1)
```
