### ISSUE TITLE
Invalid access token even with prompted token 

### ISSUE THREAD

**Issue by belinhacbr** [plamere/spotipy#332]
I'm using spotipy to fetch albums but I keep having:
` spotipy.client.SpotifyException: http status: 401, code:-1 - https://api.spotify.com/v1/album/1zCNrbPpz5OLSr6mSpPdKm: Invalid access token `

Installing the package from the master branch, I already:
- have my `spotipy_client_id` and `spotipy_client_secret` as env var
- added my callback url to my apps dashboard and set the same url as a `redirect_uri`
- called  `prompt_for_user_token` with my callback url, user and scope
- on my callbback, retrieved the `code` and instanciated the spotify client object with it

Any clue what I missed?
Does it still work with the current state of the api or is no longer maintained?

**Comment by rashad** [comment]
@belinhacbr did you eventually managed to make it work ?

**Comment by stephanebruckert** [comment]
Hi @belinhacbr, @rashad,

The repo is maintained again and a fresh version has just been released:

    pip install spotipy --upgrade

Can you still reproduce this? If yes, please do provide some code
