### ISSUE TITLE
Add support for new API endpoints

### ISSUE THREAD

**Issue by ritiek** [plamere/spotipy#335]
I just noticed that Spotify web-api does not require a username parameter any more when fetching a playlist or playlist tracks.

On the master branch currently, these functions require a `user` parameter which isn't needed any more:

----------

[get-playlist](https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlist/)
https://github.com/plamere/spotipy/blob/4c2c1d763a3653aa225c4af848409ec31286a6bf/spotipy/client.py#L373

----------

[get-playlist-tracks](https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlists-tracks/)
https://github.com/plamere/spotipy/blob/4c2c1d763a3653aa225c4af848409ec31286a6bf/spotipy/client.py#L385-L386

----------

Seems like Spotify also supports the old way of fetching playlist (with `user` parameter) but we should probably change the functions to not accept user parameter any more and change the API calls to appropriate endpoints.

**Comment by ritiek** [comment]
The full list of changes can be found here: https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/.

**Comment by hajilekwah** [comment]
Looks like they rolled the changes back for the time being:
"Update: Due to technical issues, we have rolled back the change originally scheduled for 11th September 2018. We will communicate a new date for the change as soon as we have one."
The above quote is in italics at the top of the article that was shared.

**Comment by kingosticks** [comment]
Hey guys, I guess this change to playlist URIs will be happening (again) in a couple of days (28th February 2019). Spotify's original announcement did say they'd leave the old endpoints 'until further notice' but maybe it's worth assuming their usual incompetence and merge https://github.com/plamere/spotipy/pull/320 ?
