### ISSUE TITLE
Get users id

### ISSUE THREAD

**Issue by AlessandroMinervini** [plamere/spotipy#336]
Hi everyone, my question:
is possible get a user id in any way? I would search a user from his name and print his recently artist played

Thanks

**Comment by Pizza-slice** [comment]
ya using the me function 
`token = util.prompt_for_user_token(username, scop, SPOTIPY_CLIENT_ID, SPOTIPY_CLIENT_SECRET, SPOTIPY_REDIRECT_URI)
    if token:
        sp = spotipy.client.Spotify(auth=token)
        results = sp.me()`
the return will be a dictionary(the python to equivalent to JSON)
in the dictionary there is more info just then user id (email , Birth-Day,profile photo etc... ) i think it depend on your scop you ask with your token

**Comment by AlessandroMinervini** [comment]
Ok thank you for my current user,
but if i want the id of my friend?

Thank you

**Comment by mckinly** [comment]
@AlessandroMinervini If you know the username of your friend you can pass that as a string into this method. https://github.com/plamere/spotipy/blob/4c2c1d763a3653aa225c4af848409ec31286a6bf/spotipy/client.py#L346

Also see the Web Api docs for more information [Get user's profile](https://developer.spotify.com/documentation/web-api/reference/users-profile/get-users-profile/)

**Comment by stephanebruckert** [comment]
It's unclear what you are really asking but if you are looking to search a user by display name in order to get the ID, it doesn't seem possible. Probably this is for security/privacy reasons. As @mckinly suggested, you need the user ID to find a user.
