### ISSUE TITLE
Pip claims to download version 2.4.4 but the files are actually from version 2.0.1

### ISSUE THREAD

**Issue by SimonCadge** [plamere/spotipy#337]
When installing spotipy over pip I didn't get the latest version, so I checked what was wrong.
I uninstalled spotipy and reinstalled it again, specifying that I wanted version 2.4.4. The terminal says 'successfully installed spotipy-2.4.4' but still the init file states that it is in version 2.0.1 and the code is old such that it doesn't support descriptions.
I can't even use pip to update it to the latest version because as far as pip is concerned it has installed version 2.4.4.
<img width="1343" alt="screenshot 2018-11-03 at 16 33 32" src="https://user-images.githubusercontent.com/11338764/47954779-4c173080-df86-11e8-93fb-4028af64d9ce.png">
Looking deeper it seems that the init file shows the incorrect version even when I download the correct files from GitHub, but it's still true that the actual code is up to date in the version downloaded from GitHub and is incorrect in the version from pip. For example, the user_playlist_create() function doesn't take a description parameter in the pip version, and the oauth is_token_expired() function has an underscore at the very beginning.

**Comment by shivasiddharth** [comment]
do not install using the pip install command. Instead try this:
`pip install git+https://github.com/plamere/spotipy.git --upgrade`

**Comment by txoof** [comment]
It would be a good idea if the maintainers either updated or deprecated the pypi version.  This cost me an hour to figure out why my code was failing after migrating it to a newly created virtual environment and it appeared that I had the latest and correct versions installed. 

Fortunately I found @shivasiddharth and @SimonCadge's comments to put me on the right track

**Comment by onhernandes** [comment]
So, I've an application that uses spotipy, but since it's out of date at PyPi, how can I set as dependency on `setup.py`?

Sorry for the dumb question, but I'm kinda of newbie with Python and its env.

**Comment by onhernandes** [comment]
@etedor this worked for me.

Thanks everyone =)

**Comment by gesanderson** [comment]
I also hit this issue today and spent some time before realizing the code in the installed package wasn't the same than what was on github. I agree with @txoof that updating the package on PyPI would be appreciated. 

Adding git tags would also be nice, like that we can install a specific version with `pip install git+https://github.com/plamere/spotipy.git@$VERSION`.

**Comment by stephanebruckert** [comment]
Just released [2.5.0](https://github.com/plamere/spotipy/releases/tag/2.5.0) which contains everything from 2.4.4 as well as everything that was merged to master but never released

    pip install spotipy --upgrade
