### ISSUE TITLE
[PYTHON3]Can't even import spotipy

### ISSUE THREAD

**Issue by maniexx** [plamere/spotipy#34]
I've installed spotipy using pip, no errors.
When I run python 3 and do `import spotipy` here's what I get:

`
 File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/spotipy/__init__.py", line 2, in <module>
    from client import Spotify, SpotifyException
ImportError: No module named 'client'
`

OS: Ubuntu 14.04,
Python: 3.4.0

**Comment by lylia** [comment]
i've the same issue , how did you fix it?

**Comment by lylia** [comment]
you may install python 2 only, and unistall python3. it'll be fixed ;)

**Comment by maximd** [comment]
Hi, could you maybe change the title of the issue to indicate that the problem appears with python 3?

I am really looking forward to an official python 3 support @plamere! Even if @joohoi support of python 3 is really great, maybe its work can be merged?

**Comment by joohoi** [comment]
My fork has been merged to the latest state, and pull request against it is created in PR #55

**Comment by maximd** [comment]
Let's hope it gets approved!

**Comment by joohoi** [comment]
Python 3 support has been merged to master @maniexx this issue should be solved.

**Comment by urda** [comment]
I can't seem to import this myself, unless the Python 3 support has not made it to the pip channels yet.

Version Information:

```bash
Python 3.4.3

spotipy 2.3.6
```

**Comment by joohoi** [comment]
Pip serves 2.3.6 which was released a week before the Python 3 support merge. So for the time being you're better off installing from github.

**Comment by urda** [comment]
@joohoi ok Just wanted to make sure! Saw this was still open but also saw the merge :smile:

**Comment by brki** [comment]
This issue could be closed now, no?  I just did a ``pip install spotipy`` and spotipy 2.3.7 is installed.

**Comment by yash2code** [comment]
same issue

`Traceback (most recent call last):
  File "/home/yash/MusicBot/musicbot.py", line 8, in <module>
    import spotipy
ImportError: No module named spotipy`

**Comment by ritiek** [comment]
@yash2code Try using `python3 -m pip install spotipy`.

**Comment by posterberg** [comment]
C:\Users\poe\Documents\Kod\Tidal>python -m pip install spotipy
Requirement already satisfied: spotipy in c:\users\poe\appdata\local\programs\python\python37\lib\site-packages (2.4.4)
Requirement already satisfied: requests>=1.0 in c:\users\poe\appdata\local\programs\python\python37\lib\site-packages (from spotipy) (2.21.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\poe\appdata\local\programs\python\python37\lib\site-packages (from requests>=1.0->spotipy) (2019.3.9)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\poe\appdata\local\programs\python\python37\lib\site-packages (from requests>=1.0->spotipy) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\poe\appdata\local\programs\python\python37\lib\site-packages (from requests>=1.0->spotipy) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\poe\appdata\local\programs\python\python37\lib\site-packages (from requests>=1.0->spotipy) (1.24.2)

C:\Users\poe\Documents\Kod\Tidal>python spotipy.py
Traceback (most recent call last):
  File "spotipy.py", line 4, in <module>
    import spotipy
  File "C:\Users\poe\Documents\Kod\Tidal\spotipy.py", line 5, in <module>
    import spotipy.util as util
ModuleNotFoundError: No module named 'spotipy.util'; 'spotipy' is not a package

**Comment by posterberg** [comment]
C:\Users\poe\Documents\Kod\Tidal>python -m pip install spotipy
Requirement already satisfied: spotipy in c:\users\poe\appdata\local\programs\python\python37\lib\site-packages (2.4.4)
Requirement already satisfied: requests>=1.0 in c:\users\poe\appdata\local\programs\python\python37\lib\site-packages (from spotipy) (2.21.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\poe\appdata\local\programs\python\python37\lib\site-packages (from requests>=1.0->spotipy) (1.24.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\poe\appdata\local\programs\python\python37\lib\site-packages (from requests>=1.0->spotipy) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\poe\appdata\local\programs\python\python37\lib\site-packages (from requests>=1.0->spotipy) (2019.3.9)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\poe\appdata\local\programs\python\python37\lib\site-packages (from requests>=1.0->spotipy) (2.8)

C:\Users\poe\Documents\Kod\Tidal>python spotipy.py
Traceback (most recent call last):
  File "spotipy.py", line 1, in <module>
    import spotipy
  File "C:\Users\poe\Documents\Kod\Tidal\spotipy.py", line 4, in <module>
    spotify = spotipy.Spotify()
AttributeError: module 'spotipy' has no attribute 'Spotify'
