### ISSUE TITLE
Modify volume stop playback

### ISSUE THREAD

**Issue by AlessandroMinervini** [plamere/spotipy#343]
hi!
when i use the method sp.volume(), for example sp.volume(30), spotify stop the playback,
Why? Any ideas?

my scope= 'user-modify-playback-state user-library-read'

Thanks

**Comment by ritiek** [comment]
Do you get the same behaviour if you try out the web API online at https://developer.spotify.com/console/put-volume/ ? Or does it stop playback when specifically using spotipy library?

**Comment by stephanebruckert** [comment]
Closing, this works well on my side!
