### ISSUE TITLE
util.prompt_for_user_token() doesn't pass redirect URI correctly

### ISSUE THREAD

**Issue by alphaCodeo** [plamere/spotipy#344]
Ran the example code to get the user's saved tracks. The environment variables for client id, secret and redirect URI were set, but the Spotify authorisation website had None as the redirect URI. The function did not get the contents of SPOTIPY_REDIRECT_URI or did not set it in the query parameters properly?

**Comment by alphaCodeo** [comment]
I have tried the same code, but passing the client ID, secret and redirect URI directly to the function arguments. It works when passed like that. This points to a problem in the parsing of the environment variables.

**Comment by DackJempsey** [comment]
When exporting keys in my environment I keep getting a 550, credentials not set. Have you tried setting in environment lately or just hardcoding?

**Comment by stephanebruckert** [comment]
There was a typo in the doc. Please see https://github.com/plamere/spotipy/issues/402#issuecomment-573890067 for a fix
