### ISSUE TITLE
Seach for track_ids and add to queue

### ISSUE THREAD

**Issue by Alex301298** [plamere/spotipy#345]
Hello dear spotipy-community,

Currently I´m working on a little skipt and i would like to **add a track**, wich I entered before, to my spotify **queue** (or spotifyplaylist). 

My problem is that I don´t get the **track_ids**.
The input should be very easy, sth like this:

`trackName = str(input("Song?"))
artistName = str(input("Artist?"))`

For example:
Song? -> "Power"
Artist? -> "Hardwell"
=> Output track_ids

I tried to get a result with spotify.seach(), but what ever I wrote for "q", was wrong.
It works when I seach for an artist, but I dont get the track ids...

`sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)
sp.search()`

I hope someone can help me 
Thx in advance 

Alex

**Comment by stephanebruckert** [comment]
You need to search for results with type "tracks" and use a custom query, see https://github.com/plamere/spotipy/issues/107#issuecomment-570078689
