### ISSUE TITLE
Can I play songs from python?

### ISSUE THREAD

**Issue by fraregom** [plamere/spotipy#35]
Hello Spotipy's people i have an question, i can play music from a python app using your libraries?

**Comment by kellogsgit** [comment]
Thanks, but pyspotify is using a deprecated API. 

The idea with new API would be to lauch a Spotify player somewhere (i.e. an Android connected to a HIFI) and use Spotipy as a remote control using playlist.

Is it possible today?

**Comment by FiletZitas** [comment]
Hi kellogsgit,

Did you manage to solve your problem? Would be great if someone could share a solution.
Thanks.

**Comment by Ritiek** [comment]
It is possible to play music from 3rd parties like YouTube using python.

One way I can think of is using spotipy wrapper to get the name of the song by its spotipy http link. Then play that song by looking up on YouTube programatically. I think I'll spend some time building something like this really soon :)

**Comment by stephanebruckert** [comment]
Looks like you could do that using preview mp3s (30 seconds) https://github.com/plamere/spotipy/issues/165
