### ISSUE TITLE
SpotifyException: http status: 500

### ISSUE THREAD

**Issue by cbaudouinjr** [plamere/spotipy#353]
Hey there,

My program cycles through and adds a random song to my playlist every couple minutes or so. After a few songs I seem to be getting a 500 from Spotify. Below is my error:

> Traceback (most recent call last):
>   File "/Users/{user}/Documents/GitHub/spotiserver/venv/lib/python3.7/site-packages/spotipy/client.py", line 119, in _internal_call
>     r.raise_for_status()
>   File "/Users/{user}/Documents/GitHub/spotiserver/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.spotify.com/v1/users/chrisbaudouinjr/playlists/48U3GHZBTjhPeoDSRQojjF/tracks

During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Users/{user}/Documents/GitHub/spotiserver/app.py", line 290, in playlist_manager
>     sp.user_playlist_add_tracks(username, playlist, [track_to_add['id']])
>   File "/Users/{user}/Documents/GitHub/spotiserver/venv/lib/python3.7/site-packages/spotipy/client.py", line 457, in user_playlist_add_tracks
>     payload=ftracks, position=position)
>   File "/Users/{user}/Documents/GitHub/spotiserver/venv/lib/python3.7/site-packages/spotipy/client.py", line 178, in _post
>     return self._internal_call('POST', url, payload, kwargs)
>   File "/Users/{user}/Documents/GitHub/spotiserver/venv/lib/python3.7/site-packages/spotipy/client.py", line 124, in _internal_call
>     headers=r.headers)
> spotipy.client.SpotifyException: http status: 500, code:-1 - https://api.spotify.com/v1/users/{user}/playlists/48U3GHZBTjhPeoDSRQojjF/tracks:
>  Server error.

**Comment by stephanebruckert** [comment]
Hi @cbaudouinjr, do you still have this issue?

Can you confirm that you are passing a valid track_id `track_to_add['id']` just before you get a 500?

Please also try to provide more code so we can check if the logic is correct.

**Comment by stephanebruckert** [comment]
Closing due to issue being inactive and 500 status code being internal errors that depend on the web API directly https://github.com/spotify/web-api/
