### ISSUE TITLE
current_user_saved_albums_delete() and current_user_saved_albums_contains() are missing

### ISSUE THREAD

**Issue by MrWhammy** [plamere/spotipy#355]
There is an endpoint to [delete an album from the library](https://developer.spotify.com/documentation/web-api/reference/library/remove-albums-user/) and one to [check if an album exists](https://developer.spotify.com/documentation/web-api/reference/library/check-users-saved-albums/).

These methods are analogous to current_user_saved_tracks_delete() and current_user_saved_tracks_contains(), but are not implemented

**Comment by stephanebruckert** [comment]
Fixed as part of https://github.com/plamere/spotipy/pull/414
