### ISSUE TITLE
Streaming Data

### ISSUE THREAD

**Issue by Tim-Jackins** [plamere/spotipy#358]
Is there a way to gather streaming data? If I check a song id does the API return any data related to how popular the song is?

**Comment by NotFunnyMan** [comment]
Did you mean this?
https://developer.spotify.com/documentation/web-api/reference/tracks/get-track/

**Comment by Tim-Jackins** [comment]
Yes and no, I don't Spotify gives away what I'm looking for. Thanks anyway!
