### ISSUE TITLE
Hello everyone, beginner here! util.prompt_for_user_token

### ISSUE THREAD

**Issue by JeanPaiva42** [plamere/spotipy#359]
Is there a way I can get the redirected link automatically? Also, how can I get the user id when running? Sorry if this is a repost. Thanks for any replies.

**Comment by Craig115** [comment]
There isn't any way to get the redirect link automatically, as the user has to authorize the app's scopes. Although through using flask, I've managed to automate this slightly by using flask's request object to get the current URL and then using the oauth2 object from spotipy to recreate the other steps in util.prompt_for_user_token()

   ```
    code = sp_oauth.parse_response_code(request.url)
    token_info = sp_oauth.get_access_token(code)
    token = token_info['access_token']
```
Hope this helps.

**Comment by JeanPaiva42** [comment]
I'm going to try this, thanks!

**Comment by stephanebruckert** [comment]
> Is there a way I can get the redirected link automatically?

@JeanPaiva42's answer seems right!

> Also, how can I get the user id when running?

From the official app, go to your profile and do "Copy profile link". Your user ID is part of the link.

Hope this helps. Closing for now but feel free to reopen if needed.
