### ISSUE TITLE
How do I find Singles and EPs by an artist?

### ISSUE THREAD

**Issue by manavkulshrestha** [plamere/spotipy#360]
I've found how to get all albums given an artist, but couldn't find how to get the singles and eps anywhere on the documentation.

**Comment by CDeLeon94** [comment]
Here is a link to the info on the [documentation](https://spotipy.readthedocs.io/en/latest/#spotipy.client.Spotify.artist_albums):

> **artist_albums**(artist_id, album_type=None, country=None, limit=20, offset=0)
> Get Spotify catalog information about an artist’s albums
> 
> Parameters:
> 
> - artist_id - the artist ID, URI or URL
> - **album_type** - ‘**album**’, ‘**single**’, ‘**appears_on**’, ‘**compilation**’
> - country - limit the response to one particular country.
> - limit - the number of albums to return
> - offset - the index of the first album to return

You'd have to check how EP's are listed, but my guess is they'd be under singles.

**Comment by stephanebruckert** [comment]
Filtering by `album_type` is the way to go

**Comment by ekinig** [comment]
Is there a way to ask for more than one option in the same request? I tried with a list like  `album_type=['album', 'single']` but didn't work.

**Comment by stephanebruckert** [comment]
@ekinig https://developer.spotify.com/documentation/web-api/reference/search/search/ shows you can separate types with a comma: `album,single`

**Comment by ekinig** [comment]
Yes, I saw that also in the [get-artists-albums API page](https://developer.spotify.com/documentation/web-api/reference/artists/get-artists-albums/), but unless I am doing something wrong, in spotipy it's not working

```
sp.artist_albums('spotify:artist:3NKVm2Jedcf6ibJr6pMUVx',
                     limit=50, album_type=['album', 'single'])
```
returns two items, both of type _album_ , but that artist has many singles.

**Comment by stephanebruckert** [comment]
Did you try with a single string? 

    sp.artist_albums('spotify:artist:3NKVm2Jedcf6ibJr6pMUVx',
                     limit=50, album_type=;album,single')

**Comment by ekinig** [comment]
It worked 😶. That is definitely not a python list, but I guess the API is not just for python. Thank you
