### ISSUE TITLE
Issue with _get_access_token

### ISSUE THREAD

**Issue by amc40** [plamere/spotipy#361]
Even when provided with a valid code the response status code will still be 200, causing a spotipy.oauth2.SpotifyOauthError: Bad Request error. Using the pycharm debugger I stepped into the code and saw that the response had a valid authentication code and reason = OK, however the response code was still 200 (see attached screenshot). Unless this is a design choice I would suggest that it could possibly be fixed by checking instead that the status_code was not 'OK'.
![Spotipy Screenshot](https://user-images.githubusercontent.com/36701168/54492895-5cd79b80-48c2-11e9-9e11-29142e3fe128.png)

**Comment by FryPhilip** [comment]
Hey, I get the same error. Same 200 code and OK string as reason. How did you fix that? Nothing I tried would fix that.

I tried adding the 'enable shuffle' function but at line 76 in oath2.py 
(raise SpotifyOauthError(response.reason)
the debug triggers. error code is:
spotipy.oauth2.SpotifyOauthError: OK

and the method I added to client.py
    def player_shuffle(self, state=None):
        return self._put('me/player/shuffle', state=state)

**Comment by stephanebruckert** [comment]
> Edit: never mind, the pycharm library wasn't updated, just download it from this GitHub and replace the files in your project

Fixed by [2.5.0](https://github.com/plamere/spotipy/releases/tag/2.5.0)
