### ISSUE TITLE
Playback doesn't start when uris argument provided

### ISSUE THREAD

**Issue by Thierry-Gls** [plamere/spotipy#362]
Hi,

So I've been working on a project using spotify with python. I use spotipy for the script and spotifyd to create a spotify connect device that I can retrieve with my script.

Since then my script was working fine (start, pause playback, redirecting to my playlist when I'm currently playing a track that is not in my playlist), but now when I start the playback and redirect to my playlist, the playback just doesn't start.

Here's the code that apparently doesn't work 
`spotify_obj.start_playback(device_id=spotifyd_device, uris=tracks_list)`

An example of what contains the tracks_list
`['spotify:track:0PiwFz4yt1701RA6TcvPF5',
'spotify:track:3VmWsrEdKlcLe19RdGmwb0']`

It works when I stop the playback or when I start without providing a uris list.

Apparently Spotify made some recent changes about uris (for playlists mainly), maybe this is where the issue come from?

Thank you very much !

**Comment by wackazong** [comment]
Same here...

**Comment by wackazong** [comment]
I filed a bug with spotify: https://github.com/spotify/web-api/issues/1207

**Comment by wackazong** [comment]
Update your client to the latest librespot version, that fixes it. Its not a spotipy issue I think.

**Comment by Thierry-Gls** [comment]
> 
> 
> Update your client to the latest librespot version, that fixes it. Its not a spotipy issue I think.

I can confirm, it solved the problem. Thanks a lot !
