### ISSUE TITLE
'Premium required' even with error

### ISSUE THREAD

**Issue by FryPhilip** [plamere/spotipy#369]
I get the ' Player command failed: Premium required ' error even tho I have Premium.
I tried making a second account with the free premium but that resulted in the same error.
But what really confuses me is that the response link given with says:
'https://api.spotify.com/v1/me/player/shuffle?state=true'
}
  "error": {
    "status": 401,
    "message": "No token provided"
  }
}
Has anyone else had this?

**Comment by slow-down** [comment]
At the first sentence I already thought that you might forgot to enter you token.
Then further down I read "No token provided". 
Well, you now know what to do

**Comment by FryPhilip** [comment]
Ohh, yeah. Turns out i used the worng credentioal flow. Tried using the Client Credentials Flow but the shuffle command is user specific so you need to use the Authorization Code Flow. Now it works fine.
