### ISSUE TITLE
Issue getting albuminfo with long albums

### ISSUE THREAD

**Issue by shillshocked** [plamere/spotipy#373]
This album doesn't work when using this command:
uri = albuminfo['uri']

The album is here:
spotify:album:48euqmOgRT2WyZ2Cc51ygX

I can successfully execute the code with thousands of other albums, just not this (and perhaps others like it). Is it because the data for the album is too long? It has nearly 200 tracks, perhaps it's not fully parsable.

**Comment by SHxKM** [comment]
From my experience, these kind of issues are more on Spotify's API side than this library. Spotify's API is littered with weird bugs.

**Comment by shillshocked** [comment]
I think it might be a lag/timeout on loading the json.

**Comment by stephanebruckert** [comment]
I get the full json successfully when I do `sp.album("48euqmOgRT2WyZ2Cc51ygX")`. Closing this for now, please re-open with more details if needed
