### ISSUE TITLE
URI redirect not working

### ISSUE THREAD

**Issue by swesko** [plamere/spotipy#374]
hi, i have set variables to my credentials on my environements also used the util var to get the token yet i keep getting either invalid client or error something went wrong.

i set url to localhost:8888

**Comment by Ezri-Mudde** [comment]
You could try to add a made up url to your hosts file and use that for the redirect url. You'll also have to white list the redirect url on the Spotify application dashboard.

**Comment by stephanebruckert** [comment]
There was a bug in the doc, it's all fixed now. Check these 3 things to bypass the problem https://github.com/plamere/spotipy/issues/402#issuecomment-573890067
