### ISSUE TITLE
Unable to search artists (Hebrew language)

### ISSUE THREAD

**Issue by dorsht** [plamere/spotipy#376]
Hello,

I'm trying to use spotipy in order to find some data about songs.
It works flawlessly with English, but when I'm trying to work with Hebrew, there are no results.
I tried to search the problem in Google, but I couldn't find anything relevant.
Code example:
    client_credentials_manager = SpotifyClientCredentials(Some user info...)
    spotify = spotipy.Spotify(client_credentials_manager=client_credentials_manager)
    name = 'שלמה ארצי'
    results = spotify.search(q='artist:'+name, type='artist') 
    print(results)

When I tried to search the artist with English name, It worked also.

Thank You.

**Comment by stephanebruckert** [comment]
Hi, this works:

    spotify.search(q='שלמה ארצי', type='artist')

No need for `artist:` because you already specify `type='artist'`. Read more about `query` here https://developer.spotify.com/documentation/web-api/reference-beta/#writing-a-query---guidelines. 

We will try to include this "how-to" in the spotipy doc and as part of https://github.com/plamere/spotipy/issues/268

**Comment by stephanebruckert** [comment]
You were correct, I just found that [`"artist:'שלמה ארצי'"`](https://developer.spotify.com/console/get-search-item/?q=%22artist%3A%27%D7%A9%D7%9C%D7%9E%D7%94%20%D7%90%D7%A8%D7%A6%D7%99%27%22&type=artist&market=&limit=&offset=) does not work while [`"artist:'Eminem'"`](https://developer.spotify.com/console/get-search-item/?q=%22artist:%27Eminem%27%22&type=artist&market=&limit=&offset=).

This issue can be created in https://github.com/spotify/web-api/ as it's not related to the library
