### ISSUE TITLE
Unfollow Artists/Users Not supported?

### ISSUE THREAD

**Issue by KilometersFan** [plamere/spotipy#377]
On the Spotify Web API Reference, there is an endpoint for unfollowing artists/users but I don't see a corresponding method in Spotipy.

**Comment by Garana400** [comment]
I've created a pull request to add the endpoints, you would just need to change the http method in following artists/users from PUT to DELETE. Here's the commit https://github.com/plamere/spotipy/pull/379/commits/9f650ba8700cdd71d48fc1fd374a4f6381d32f78 .

**Comment by Garana400** [comment]
I've created a pull request to add the methods, you would just need to change the http method in following artists/users from PUT to DELETE. Here's the commit 9f650ba .

**Comment by stephanebruckert** [comment]
Fixed as part of https://github.com/plamere/spotipy/pull/414
