### ISSUE TITLE
Connect server-sided without webpage

### ISSUE THREAD

**Issue by dicecko** [plamere/spotipy#384]
Hi I looked through a lot of documentation and issues, but I cannot find how I can just login through a python script and request my own data.

So I don't want to create a public app or something through the web. I just simply want to get my data back. Everything server-sided in a single py script without a frontend. 

When I try this:
```
scope = 'user-library-read'

sp = spotipy.oauth2.SpotifyOAuth(client_id=client_id, client_secret=client_secret,scope=scope, 
          redirect_uri='')
print(sp)
token = sp.get_access_token()
print(token)
if token:
       sp = spotipy.Spotify(auth=token)
       results = sp.current_user_saved_tracks()
       for item in results['items']:
            track = item['track']
            print(track['name'] + ' - ' + track['artists'][0]['name'])
else:
         print("Can't get token for " + client_id)
```

I get the error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-f05d69aac870> in <module>()
      3 sp = spotipy.oauth2.SpotifyOAuth(client_id=client_id, client_secret=client_secret,scope=scope, redirect_uri='')
      4 print(sp)
----> 5 token = sp.get_access_token()
      6 print(token)
      7 if token:

TypeError: get_access_token() missing 1 required positional argument: 'code'

I also just tried it directly with the requests module:

```
grant_type = 'client_credentials'

#Request based on Client Credentials Flow from https://developer.spotify.com/web-api/authorization-guide/

#Request body parameter: grant_type Value: Required. Set it to client_credentials
body_params = {'grant_type' : grant_type}

url='https://accounts.spotify.com/api/token'

response=requests.post(url, data=body_params, auth = (client_id, client_secret)) 

token = response.json()['access_token']
```

but then I get the error:
SpotifyException: http status: 403, code:-1 - https://api.spotify.com/v1/me/tracks?offset=0&limit=20:
 Insufficient client scope

But I have no idea where to add the scopes. I tried adding it in grant_type and as a seperate key-value pair in body_params, but that doesn't work.

**Comment by sibo7851** [comment]
I'm under the impression that this plugin is not actively developed, and I don't think it even works if you have a website setup (since I tried it using my sites working redirect URI and it did not give me python access).

**Comment by felix-hilden** [comment]
It most certainly does work for a website setup! And maintenance is being continued. Have a look at #406.

For local use, you probably want to use `util.promp_for_user_token` to retrieve a token. That's very handy for single-user situations and small scripts. Have a look at the documentation for more information!

**Comment by stephanebruckert** [comment]
Answered by @felix-hilden, closing
