### ISSUE TITLE
How to get all tracks of playlist without user id

### ISSUE THREAD

**Issue by maltejur** [plamere/spotipy#390]
Is there a alternative function to `user_playlist_tracks(user, playlist_id)` where you just have the playlist id? The new spotify playlist-links aren't giving the user-id anymore.

**Comment by ritiek** [comment]
Passing `user` as `None` seems to work:

```python
>>> playlist_id = "blabla"
>>> sp.user_playlist_tracks(user=None, playlist_id=playlist_id)
```

**Comment by mw1213** [comment]
If you want to get another users' `playlist`,  servers won't let you do that, giving you The `HTTP 403 Forbidden` error. 

![Error](https://user-images.githubusercontent.com/33518737/64112459-c15eb800-cd87-11e9-8ac1-9354a41411d8.png)

Function code (`playlist` argument is uri to playlist):
```
def get_a_list_of_tracks(playlist):
    scope='playlist-read-collaborative'
    token = get_token(scope)
    sp = spotipy.Spotify(auth=token)
    result = sp.user_playlist(user=None, playlist_id=playlist)
    ...

def get_token(scope=''):
    token = util.prompt_for_user_token(username, scope, SPOTIPY_CLIENT_ID,
                                       SPOTIPY_CLIENT_SECRET,
                                       SPOTIPY_REDIRECT_URI)
    return token
```

**Comment by ritiek** [comment]
@mw1213 Are you trying to fetch user's starred playlist? That is what it seems like to me from the screenshot. I think Spotify removed starred playlists quite a while ago so I don't know if those are still a thing.

Anyway, I can confirm that passing `user=None` for usual Spotify playlists works fine. For example, you could pick any spotify playlist from [r/spotify](https://www.reddit.com/r/spotify/) and pass the playlist ID to `sp.user_playlist` or `sp.user_playlist_tracks` and it works fine. Such as this playlist:
https://open.spotify.com/playlist/3REbQZU8WKDD0h4riXklug?si=ZXm1M-_wSJyyQYKSlufU6Q could be fetched as:

```python
sp.user_playlist(user=None, playlist_id="3REbQZU8WKDD0h4riXklug")
```
