### ISSUE TITLE
405 error when creating playlists

### ISSUE THREAD

**Issue by tmni** [plamere/spotipy#397]
Even with a scope of 'playlist-modify-public', I'm still receiving a `http status: 405, code:-1` error when calling:

`sp.user_playlist_create(user=username,name = name, public=True)`, 

which I'm assuming means I am still not granted access to create a playlist. I'm able to read playlists and all of my other permissions, though. Let me know if I'm completely missing something!

**Comment by felix-hilden** [comment]
HTTP 405 is "Method not allowed". Is the access token you are using in your client the user's token?

**Comment by stephanebruckert** [comment]
Possible duplicate https://github.com/plamere/spotipy/issues/380
