### ISSUE TITLE
Spotipy freezes on large requests using next

### ISSUE THREAD

**Issue by shillshocked** [plamere/spotipy#398]
After several minutes it will eventually freeze. No errors, just no further progress in retrieving a list of artists' albums. Anyway to bypass this?

I've tried retry libraries but still the same result.

**Comment by felix-hilden** [comment]
Could you provide any additional information, like Artist ID?

**Comment by shillshocked** [comment]
it's not specific to any URIs, it's just the way Spotipy is handling the connection.

I'm in an area with connectivity issues, so this is more of a problem for me than perhaps others. Nonetheless, the sessions code is not robust. I find that using a retrying (tenacity) decorator is the only way to handle this smoothly. I can also disable sessions in Spotipy but it still locks up on individual requests sometimes.

If I can implement a way to reset the adaptor in Python, that would be the fastest way to address this. Connection resets when coupled with a retrying decorator will make it get over the hump without data loss.

**Comment by shillshocked** [comment]
Ah! This seems to help:

sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager, requests_timeout=10)
