### ISSUE TITLE
issue with getting playlist using just playlist id

### ISSUE THREAD

**Issue by tank113** [plamere/spotipy#401]
It seems client.py still uses old end-point for user_playlist function

`https://api.spotify.com/v1/users/%s/playlists/%s`

Where as spotify API for getting the playlist just needs playlist id and not users.

`GET https://api.spotify.com/v1/playlists/{playlist_id}`

Could anyone shade a light on this issue?

**Comment by ritiek** [comment]
Check out if #390 helps.

**Comment by stephanebruckert** [comment]
Good point @tank113 

`sp.playlist(id)` has been added in https://github.com/plamere/spotipy/pull/414 and will be released soon
