### ISSUE TITLE
Bad request when using token prompt

### ISSUE THREAD

**Issue by gmbroadbent** [plamere/spotipy#402]
```
import spotipy as sp
import spotipy.util as util
import credentials as c

token = util.prompt_for_user_token(c.sp_username, 'playlist-modify-private', c.sp_client_id, c.sp_client_secret, 'http://localhost:8888/callback/', None)

```

I have tried a redirect url of `http://google.com/` as well, which didn't change anything
I do get successfully redirected

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\User1\Desktop\Rand\Github\Project\Lab\SE_Prog.py", line 26, in <module>
    token = util.prompt_for_user_token(c.sp_username, 'playlist-modify-private', c.sp_client_id, c.sp_client_secret, 'http://localhost:8888/callback/')
  File "C:\Users\User1\Desktop\Rand\Github\Project\Lab\venv\lib\site-packages\spotipy\util.py", line 86, in prompt_for_user_token
    token_info = sp_oauth.get_access_token(code)
  File "C:\Users\User1\Desktop\Rand\Github\Project\Lab\venv\lib\site-packages\spotipy\oauth2.py", line 217, in get_access_token
    raise SpotifyOauthError(response.reason)
spotipy.oauth2.SpotifyOauthError: Bad Request
```

Not sure what the "Bad request" is about

Also tried it using using the Idle IDE, same result

**Comment by rashad** [comment]
Big plus one here i've tried almost every possible combination (except the right one apparently) and I keep getting a 
```
line 217, in get_access_token
    raise SpotifyOauthError(response.reason)
spotipy.oauth2.SpotifyOauthError: Bad Request

**Comment by stephanebruckert** [comment]
3 things to verify to fix this issue:

- there was a documentation typo https://github.com/plamere/spotipy/issues/232, make sure you call the method this way;

   > util.prompt_for_user_token(username,scope,client_id='your-app-client-id',client_secret='your-app-client-secret',redirect_uri='your-app-redirect-url')
 
- make this your redirect URI: `SPOTIPY_REDIRECT_URI='http://localhost:8888/callback/'`
- add it to your redirect URI whitelist in http://developers.spotify.com > app > edit settings > whitelist
