### ISSUE TITLE
start_playback(deviceID) returns "Player command failed: Restriction violated"

### ISSUE THREAD

**Issue by jpringle1** [plamere/spotipy#408]
When using spotipy to start_playback on my phone, music resumes as expected. However, when i input the ID of my Amazon echo, it returns the error "Player command failed: Restriction violated". 

Any idea what's causing this?

**Comment by felix-hilden** [comment]
Could you please provide some more information? Were you already playing on the Echo, but then paused, or were you playing on your phone and tried to resume on the Echo, or what was the exact situation?

Perhaps you could try [transferring](https://github.com/plamere/spotipy/blob/master/spotipy/client.py#L901) the playback.

**Comment by stephanebruckert** [comment]
Definitely this error is coming from the web API. Look at this thread https://github.com/spotify/web-api/issues/1205

**Comment by d00mfish** [comment]
So I have the same behaviour:

1. Play music on spotify connect device, e.g. Echo Dot.
2. Switch playback to pc in the spotify desktop app.
3. Close the desktop app
4. Start playback on spotify connect device (Echo) through python
5. -> Restriction violated, even though the device id shows up in sp.devices().

You think this is a web api issue?
If so, I will go there with my problem.

**Comment by d00mfish** [comment]
Alright so I worked around this with transferring the playback before if a device is currently playing or if no device is playing at all.
Seems to work for now but but is not that pretty. Alse I need to pause the playback, otherwise the currently playing song will shortly play on the echo:

```py
def play_context_URI(uri: str):
    current = current_device()
    if current == -1:
        sp.transfer_playback(config['AUTH']['device_id'], force_play=False)        #Workaround for permission problems when old playback was on other device
        time.sleep(0.5)
        sp.pause_playback()
    elif current[0] != config['AUTH']['device_id']:
        sp.transfer_playback(config['AUTH']['device_id'], force_play=False)        #Workaround for permission problems when other device is currently in playback
        time.sleep(0.5)
        sp.pause_playback()
    if check_available(config['AUTH']['device_id']):         #check if device is even online for playback
        shuffle_on()
        sp.start_playback(device_id=config['AUTH']['device_id'], context_uri=uri)
        return 1
    else:
        return -1
```
