### ISSUE TITLE
Is there a way to get a list of all the playlists a user is following?

### ISSUE THREAD

**Issue by Peter-Schorn** [plamere/spotipy#409]
I see in the documentation that `user_playlist_is_following` can be used to check if a user is following a given playlist, but this isn't what I'm looking for. How do I retrieve a list of all the playlists that a user is following? Did I miss this in the docs or does this feature not exist?

**Comment by Peter-Schorn** [comment]
I should also add that user_playlists only returns playlists that the user created, not followed playlists

**Comment by ritiek** [comment]
You can fetch all playlists for a user and then check what all playlists are actually owned by that user. If a playlist isn't owned by that user that means the user is probably following this playlist:
```python
# Displays all public playlists that the user follows
user = "ritiek"
playlists = spotify.user_playlists(user)

for playlist in playlists["items"]:
    if not playlist["owner"]["id"] == user:
        print(playlist["name"])
```

**Comment by Peter-Schorn** [comment]
I've tried using `user_playlists(user)` and `current_user_playlists`. Both of these functions only returned playlists that I created. Also, I only have a total of 20 playlists, including both created and followed playlists, so it's not like the results are being paginated . Here's the relevant section of my code. Maybe you can figure out why I'm only getting the playlists I created.
```
username      = 'myUsername'

client_id         = os.environ.get('CLIENT_ID')
client_secret = os.environ.get('CLIENT_SECRET')
redirect_uri    = 'http://localhost/'
scope             = 'user-library-read'


token = util.prompt_for_user_token(username, scope, client_id, client_secret, redirect_uri)

if token:
    sp = spotipy.Spotify(auth=token)

    playlists = sp.user_playlists(username)

    # I've also tried this:
    # playlists = sp.current_user_playlists()

    for playlist in playlists['items']:
        plistName = playlist['name']
        plistURI  = playlist['uri']
        tTracks   = playlist['tracks']['total']
        if tTracks == 0: continue

        for offset in range(0, 10000, 100):
            tracks = sp.user_playlist_tracks(username, plistURI, limit=100, offset=offset)
            if len(tracks['items']) == 0: print(''); break
         
            # Do a bunch of things for all of the tracks
            download_tracks(tracks)

**Comment by Peter-Schorn** [comment]
Could it be something to do with the scope I'm using?

**Comment by ritiek** [comment]
> Could it be something to do with the scope I'm using?

That's what it seems like! Try using `playlist-read-private` as the scope.

**Comment by Peter-Schorn** [comment]
Could you do me a favor and give me a list of all the different scopes that can be used? I didn't find that on the docs.

**Comment by ritiek** [comment]
Does it work for you with changing the scope as I mentioned in previous comment? The scope list can found at https://beta.developer.spotify.com/documentation/general/guides/scopes/.

**Comment by Peter-Schorn** [comment]
When I used `playlist-read-private` it retrieved *all* of my playlists! Thanks!

**Comment by stephanebruckert** [comment]
Looks answered by @ritiek, thanks & closing!
