### ISSUE TITLE
A lot of attributes are not working for me

### ISSUE THREAD

**Issue by RANKKY-YT** [plamere/spotipy#410]
Hey guys,
so I tried to get the `current_playback()` do see what is playing right now. That doesnt work. Neither does `current_user_playing_track()` nor `currently_playing()`. It always troughts me the same error:

Traceback (most recent call last):
  File "spoti.py", line 27, in <module>
    track = spotifyObject.currently_playing()
AttributeError: 'Spotify' object has no attribute 'currently_playing'

Thats the important part of my code:

`spotifyObject = spotipy.Spotify(auth=token)`

`track = spotifyObject.currently_playing()`
`artist = track['item']['artist'][0]['name']`
`track = track['item']['name']`

Moreover, there are other things that doesnt seem to be working for me:

`spotifyObject.devices()`
`spotifyObject.start_playback`

I got the device ID on the official Spotify developer page (https://developer.spotify.com/console/get-users-available-devices/), but its now hardcoded.

I hope someone can help me?!
Thanks

**Comment by ritiek** [comment]
Might be related to #337.

**Comment by stephanebruckert** [comment]
Most likely @ritiek is right. Please upgrade your version of spotipy and it should work:

    pip install spotipy --upgrade
