### ISSUE TITLE
Downloadable link for a track

### ISSUE THREAD

**Issue by aminhyper** [plamere/spotipy#425]
I'm new in spotify.
I want to make a program that the user send `spotify uri` to the program and  my app download it using the download link
Can this library or `spotify web api` be extracted downloadable link  from `spotify uri?`

**Comment by stephanebruckert** [comment]
Hey @aminhyper, I know you can get 30s preview mp3s https://github.com/plamere/spotipy/issues/165#issuecomment-281955164

**Comment by MaZderMind** [comment]
Just to make this clear: It is not possible to download complete Songs from Spotify via the API.

**Comment by stephanebruckert** [comment]
More info about this on https://developer.spotify.com/documentation/web-playback-sdk/
