### ISSUE TITLE
Search query for a specific genre from a specific year?

### ISSUE THREAD

**Issue by fortyTwo102** [plamere/spotipy#426]
Pretty much what the title said. Kudos for the module!

**Comment by stephanebruckert** [comment]
It might work but you need to build your own query and pass it to `sp.search(query)`. 

Look for "year" on this page https://developer.spotify.com/documentation/web-api/reference/search/search

**Comment by fortyTwo102** [comment]
@stephanebruckert I tried it but what basically happens is that I can either only search using the genre or the year but not those two together. Adding a '+' between them does not work.

**Comment by stephanebruckert** [comment]
> For example: The query q=album:gold%20artist:abba&type=album returns only albums with the text “gold” in the album name and the text “abba” in the artist name.

this example looks promising, what does it give with `genre` and `year`?

Let me know if it works, but if it doesn't, you should post an issue in https://github.com/spotify/web-api/ instead, because this is related to what you receive from the API directly.

**Comment by fortyTwo102** [comment]
hey I managed to get it done. What I did was give a whitespace between the two params.
The query is something like sp.search("genre:avant-garde year:1966", type=artist)
