### ISSUE TITLE
Documentation Issue: API Cannot be used without Client-Token (anymore?)

### ISSUE THREAD

**Issue by MaZderMind** [plamere/spotipy#427]
The first Example in the Documentation – "Here's a quick example of using Spotipy to list the names of all the albums released by the artist 'Birdy':" – does not work, because it seems that Spotify does not allow Unauthorized Requests anymore.

Either one of the Authorization Flows seem to be required.

**Comment by MaZderMind** [comment]
It seems that #244 fixed the Documentation below "Getting Started" but missed the initial Example under "Welcome to Spotipy!", which still remains invalid.

**Comment by stephanebruckert** [comment]
Nice catch, fixed in latest https://spotipy.readthedocs.io/en/latest/
