### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get_cached_token'

### ISSUE THREAD

**Issue by ritiek** [plamere/spotipy#430]
The recent merge of #428 (87a72a060fa82153f1995c9f9e563baf1aca3282) seems to be breaking this example code:
```python
import spotipy
import spotipy.oauth2 as oauth2

CLIENT_ID = 'client_id'
CLIENT_SECRET = 'client_secret'

credentials = oauth2.SpotifyClientCredentials(
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET)

token = credentials.get_access_token()
spotify = spotipy.Spotify(auth=token)

playlist_url = "https://open.spotify.com/playlist/3Fm8szwHhMSQHQNxc4u22x"
playlist = spotify.playlist(playlist_url)
```
with this error:
```python
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    playlist = spotify.playlist(playlist_url)
  File "/home/ritiek/Downloads/spotipy/spotipy/client.py", line 393, in playlist
    return self._get("playlists/%s" % (plid), fields=fields, market=market)
  File "/home/ritiek/Downloads/spotipy/spotipy/client.py", line 166, in _get
    return self._internal_call('GET', url, payload, kwargs)
  File "/home/ritiek/Downloads/spotipy/spotipy/client.py", line 111, in _internal_call
    headers = self._auth_headers()
  File "/home/ritiek/Downloads/spotipy/spotipy/client.py", line 97, in _auth_headers
    token_info = self._auth.get_cached_token()
AttributeError: 'str' object has no attribute 'get_cached_token'
```

The code works OK for commits earlier than 87a72a060fa82153f1995c9f9e563baf1aca3282.

This needs to be checked.

**Comment by stephanebruckert** [comment]
Sorry about this, I've temporarily reverted that PR https://github.com/plamere/spotipy/commit/26db832e24637f91411bb92bb031b41c54676e6d and will have a better look at it tonight

**Comment by ritiek** [comment]
Our test suite should've caught this one. I'll also take a look right now what went wrong in #428. Adding automated tests for this later should be a good idea too!

**Comment by stephanebruckert** [comment]
@ritiek I found what went wrong. Before merging, the tests were passing locally but I ran them from the `/tests` folder rather than the project folder, which would have used my pip-installed version of spotipy (2.7.1) instead of the project code. Will add a github action for tests as soon as this is fixed

**Comment by MaZderMind** [comment]
A way to still allow this kind of api usage might be, to check the type of the `auth=` property and use it als-is when it is string.

**Comment by stephanebruckert** [comment]
@MaZderMind, @ritiek please let me know what you think of https://github.com/plamere/spotipy/issues/263#issuecomment-578539713

I'm closing the current issue since the breaking PR was reverted
