### ISSUE TITLE
Track object does not report popularity

### ISSUE THREAD

**Issue by mnburkle** [plamere/spotipy#434]
Spotify's track object has a popularity field, which is not available on spotipy

**Comment by stephanebruckert** [comment]
I can see it according to this test: https://github.com/plamere/spotipy/blob/51637d7b2c3f7ebcf12b94fd22d6fb21048949bc/tests/tests.py#L101

Spotipy should just return what Spotify returns https://github.com/spotify/web-api/, perhaps the track you are looking for doesn't have a popularity yet?

Closing for now but feel free to re-open with more information
