### ISSUE TITLE
unable to create playlist

### ISSUE THREAD

**Issue by krishangpatney** [plamere/spotipy#444]
So I've authenticated my user however I'm still getting the error where it says I'm unable to create a playlist for another user : 
spotipy.client.SpotifyException: http status: 403, code:-1 - https://api.spotify.com/v1/users/krishangpatney/playlists:
 You cannot create a playlist for another user.

any help would be appreciated. 
Thanks :)

**Comment by stephanebruckert** [comment]
Can you please share a minimal working code

**Comment by krishangpatney** [comment]
`
playlist_name = "TrialOne"
playlist_description = 'this is me first trial lmao'
scope = "playlist-modify-public"
token = util.prompt_for_user_token(username, scope, client_id=SPOTIPY_CLIENT_ID, client_secret=SPOTIPY_CLIENT_SECRET, redirect_uri=SPOTIPY_REDIRECT_URI)

if token:
    sp = spotipy.Spotify(auth=token)
    sp.trace = False
    playlists = sp.user_playlist_create(username, playlist_name,
                                        description=playlist_description)
    pprint.pprint(playlists)
else:
    print("Can't get token for", username)`

So looking at the tokens created when I add tracks to an already created playlist its making two, one with the wrong name and one with the correct name spelling, which is confusing and thats my code, technically should work.

**Comment by stephanebruckert** [comment]
When using `user_playlist_create` can you make sure that you are passing your user ID? 

> Spotify user ID. The unique string identifying the Spotify user that you can find at the end of the Spotify URI for the user. The ID of the current user can be obtained via the Web API endpoint.

A convenient way to find the URI is to go to your spotify profile, click share and "copy spotify:uri"

**Comment by krishangpatney** [comment]
just tried that and it's still not letting me use it. `
Traceback (most recent call last):
  File "C:\Users\krish\Anaconda3\envs\spotify\lib\site-packages\spotipy\client.py", line 163, in _internal_call
    r.raise_for_status()
  File "C:\Users\krish\Anaconda3\envs\spotify\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.spotify.com/v1/users/krishangpatney/playlists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "createplaylist.py", line 50, in <module>
    description=playlist_description)
  File "C:\Users\krish\Anaconda3\envs\spotify\lib\site-packages\spotipy\client.py", line 549, in user_playlist_create
    return self._post("users/%s/playlists" % (user,), payload=data)
  File "C:\Users\krish\Anaconda3\envs\spotify\lib\site-packages\spotipy\client.py", line 227, in _post
    return self._internal_call("POST", url, payload, kwargs)
  File "C:\Users\krish\Anaconda3\envs\spotify\lib\site-packages\spotipy\client.py", line 173, in _internal_call
    headers=r.headers,
spotipy.client.SpotifyException: http status: 403, code:-1 - https://api.spotify.com/v1/users/krishangpatney/playlists:
 You cannot create a playlist for another user.`

**Comment by stephanebruckert** [comment]
Did you sign in with a different user previously? I suspect you are not signed in under the correct user.

Can you try to add `show_dialog=True` to `util.prompt_for_user_token`, like this:

    token = util.prompt_for_user_token(username, scope, 
                                       show_dialog=True, 
                                       client_id=SPOTIPY_CLIENT_ID,
                                       client_secret=SPOTIPY_CLIENT_SECRET,
                                       redirect_uri=SPOTIPY_REDIRECT_URI)

**Comment by krishangpatney** [comment]
Well, I only have one user account and with the show_dialog enabled it's still giving me the same error. :/ 

```
spotipy.client.SpotifyException: http status: 403, code:-1 - https://api.spotify.com/v1/users/krishangpatney/playlists:
 You cannot create a playlist for another user.
```

**Comment by stephanebruckert** [comment]
That's weird, I'm running out of ideas.

Are you running the latest version of spotipy (2.9.0)?

**Comment by krishangpatney** [comment]
Yep. The other functions work except this one which is weird.

**Comment by stephanebruckert** [comment]
Does it work from https://developer.spotify.com/console/post-playlists/ ?

**Comment by krishangpatney** [comment]
Nope, getting the authentication code doesnt work.

**Comment by stephanebruckert** [comment]
How, is there an error message? What browser are you using? Can you try to clear your cache or just try in a different browser?

If this still doesn't work, you should absolutely post that issue in https://github.com/spotify/web-api/

**Comment by krishangpatney** [comment]
I tried it out with firefox and chrome, going to post the issue since it's still not working. Thank you for you help.

**Comment by stephanebruckert** [comment]
Hey @krishangpatney, 

Previously you said that even from https://developer.spotify.com/console/post-playlists/ you couldn't post a playlist. Now it looks like you can according to https://github.com/spotify/web-api/issues/1486, is this right?

Now to make it work from Python I suggest that you start from a clean environment. Did you already delete the token from your project folder? There should be a hidden file that sits close to your code, it should be named `.cache-{username}`. Please confirm you managed to delete it and try again.

Then there is something else we haven't tried: make sure you use the same `username` variable for both calls:

```
     util.prompt_for_user_token(username, ...
```
```
     sp.user_playlist_create(username, ...
```

The username is your ID and it is probably not `krishangpatney`, instead it should look like either a number 12345678 or a weird sequence of characters xlq3jsovp49eg9go8ifd

**Comment by stephanebruckert** [comment]
Closing this for now as it's hard to define what the issue really is but please feel free to reopen with more details
