### ISSUE TITLE
[help] Don't know how to use proxy

### ISSUE THREAD

**Issue by matze19999** [plamere/spotipy#449]
Hey guys,

I read the documentation, but I haven't found a tutorial on how to use a proxy... Can someone please help me or write some short lines on how to get spotipy to use a proxy?

Thank you!!

**Comment by stephanebruckert** [comment]
Hey,

`proxies` that you pass to spotipy will be passed directly to `request.Session()`, see here:

https://github.com/plamere/spotipy/blob/13109c1613594e098f5ecddc64edbf465306052b/spotipy/client.py#L150

See if structuring your `proxies` as showed in the following references helps:
 - https://2.python-requests.org/en/master/user/advanced/#id1
 - https://stackoverflow.com/questions/30837839/how-can-i-set-a-single-proxy-for-a-requests-session-object 
 - https://blog.scrapinghub.com/python-requests-proxy

Please let us know how it goes and we can then improve the docs

**Comment by matze19999** [comment]
Thanks, this worked like a charm!

Maybe you can add this code example to the folder examples on GitHub or add a code snipped on the readthedocs page :)
