### ISSUE TITLE
Add support for podcasts/ shows/ episodes

### ISSUE THREAD

**Issue by Ollewa123** [plamere/spotipy#450]
Hi,

in the official spotify dev documentation so far there is no information about podcast support. On spotifys github page however i found [this](https://github.com/spotify/web-api/issues/551#issuecomment-583748908) overview of undocumented podcast functionality.
Are there any plans for adding these functions to spotipy?

**Comment by stephanebruckert** [comment]
Definitely accepting any PR that implements this!
