### ISSUE TITLE
ImportError: No module named oauth2

### ISSUE THREAD

**Issue by tgraf2** [plamere/spotipy#455]
I recently installed spotipy using:
**python -m pip install spotipy --user**
which installed without errors.  I then setup my spotify client ID and secret, and when I try to run the example given under "create a Spotify object and call methods" I get the following error:
**ImportError: No module named oauth2**
Any help on why I am getting this error?  I am assuming the oauth2 module should have been installed when I installed spotipy.

**Comment by stephanebruckert** [comment]
hmm oauth is part of spotipy so it shouldn't be missing.

If from your command line you run `python` alone, what do you get when you type the following?

```
>>> import spotipy
>>> spotipy.oauth2
```

Also please share the full stack traces (the one from the README example as well)

**Comment by tgraf2** [comment]
Hi Stéphane,

Thanks for getting back to me.  I found the problem (my python script was named spotipy.py).  When I renamed it everything worked.
Thanks again.

Terry
