### ISSUE TITLE
how to get a list of of track ID's from the object returned by current_user_top_tracks?

### ISSUE THREAD

**Issue by abby-ebrown** [plamere/spotipy#458]
So that's basically my question. I'm trying to get a list of just the track ID's from the blob that's returned by the current_user_top_tracks method.

**Comment by ritiek** [comment]
You mean something like this?
```python
tracks = sp.current_user_top_tracks()
for item in tracks["items"]:
    print(item["id"])
```

**Comment by abby-ebrown** [comment]
holy shite thank you so much!
