### ISSUE TITLE
Spotipy Delete Track, "No token provided" even though should be provided #1

### ISSUE THREAD

**Issue by MatthiasHerp** [plamere/spotipy#464]
I'm currently writing a code to delete specific tracks out of a Spotify Playlist I created, and thus that I own. But somehow I am having Issues with the token, although I am using the 'playlist-modify-public' token which should allow me to delete tracks in my own playlists.
And I checked that the playlist is publicly seen since it is available under public playlists of my account.
Would greatly appreciate your help :)

I get this error message by the link in the error code:
{
"error": {
"status": 401,
"message": "No token provided"
}
}

My Code:
[Spotipy_delete_tracks.txt](https://github.com/plamere/spotipy/files/4431202/Spotipy_delete_tracks.txt)

Spotipy Authorization Scopes overview:
https://developer.spotify.com/documentation/general/guides/scopes/#playlist-modify-public

**Comment by stephanebruckert** [comment]
```
SpotifyException: http status: 403, code:-1 - https://api.spotify.com/v1/users/11136043288/playlists/7LRXlpc7nL7yVF6oVTv8tH/tracks:
 You cannot remove tracks from a playlist you don't own.
```
In the code file I can see a 403 not a 401, which error do you actually have? 

-------------

Then can you print the result of `sp.me()` and confirm your user ID is `11136043288`?

**Comment by MatthiasHerp** [comment]
@stephanebruckert thanks for the advice. I tried the sp.me() and realized that it was an issue with my account. I used to have the account with my brother and we split it up somehow. 
So I made a new account and a new application and now it works :)
Thanks for the quick help 👍

**Comment by jboss10** [comment]
Yes, 100% that's what it was. Looks like I was trying to connect to my personal account and not my test environment. DUH!

This is a project so could someone run into this issue when running/testing my script? If so, how to avoid from them using their own personal sign-in?

Thanks!
