### ISSUE TITLE
Adding Podcasts Episodes into Playlists

### ISSUE THREAD

**Issue by pedronaresi** [plamere/spotipy#465]
As the launch of the new Episodes API, is it possible to get the Episodes added through `user_playlist_add_tracks`? Have been trying this afternoon and getting `400 - Payload contains a non-existing ID`

**Comment by stephanebruckert** [comment]
This was added in  https://github.com/plamere/spotipy/pull/456 and just needs to be released. You can already use it by doing:

    pip install git+https://github.com/plamere/spotipy.git --upgrade

**Comment by stephanebruckert** [comment]
Just released in [2.11.0](https://github.com/plamere/spotipy/releases/tag/2.11.0), feel free to upgrade with `pip install spotipy --upgrade` and to share any feedback!
