### ISSUE TITLE
Return a list containing the user's currently queued tracks.

### ISSUE THREAD

**Issue by zacharyvincze** [plamere/spotipy#466]
As of now, there does not seem to be any way to get information on a user's currently queued tracks. Is this a limitation of the Spotify API or am I just not seeing a method that does this?

**Comment by ritiek** [comment]
Nope, not possible at the moment. Spotify's web-api does not currently provide this endpoint.

Also see: https://github.com/spotify/web-api/issues/462.

**Comment by JobDoesburg** [comment]
https://developer.spotify.com/console/get-queue/ as of very recently, this is possible (https://community.spotify.com/t5/Live-Ideas/Developer-Web-API-playback-queue-route/idi-p/5202433/page/3#comments)
