### ISSUE TITLE
audio_features maximum = 100 

### ISSUE THREAD

**Issue by MatsErdkamp** [plamere/spotipy#468]
The maximum for requesting audio features is 100, the docs currently suggest that it is 50.

**Comment by stephanebruckert** [comment]
@MatsErdkamp feel free to edit this line https://github.com/plamere/spotipy/blob/c6de8dc7131e5165b5d9cf2c266444a6f2b6c68d/spotipy/client.py#L1235 and open a quick pull request. It could be done from the UI directly! Cheers for the report

**Comment by MatsErdkamp** [comment]
Will do! thanks
