### ISSUE TITLE
Charts API

### ISSUE THREAD

**Issue by pa12** [plamere/spotipy#47]
Spotify recently made an update to their Spotify Viral Charts, which used to be available here: http://charts.spotify.com/.

They are now available only via the web player itself: https://play.spotify.com/chart/6o9o1UphRtyv10VPuDT80D and I was wondering if there is a Spotipy solution to grab the songs from the Viral charts into Python.

As an example, here is the Global Viral 50 chart I would like to pull data on: spotify:app:chart:6o9o1UphRtyv10VPuDT80D

Any help would be greatly appreciated.

**Comment by thelinmichael** [comment]
Long time since this was opened, but in case you're still interested - Spotify is working on a new Charts page that'll replace the existing charts.spotify.com page, but it's not available yet.

**Comment by drs-m** [comment]
there's spotifycharts.com which offers a download option of current and historical chart position data as csv

**Comment by thelinmichael** [comment]
@drs-m, can confirm that it's official. There are however no public API endpoints to retrieve the charts data yet.

**Comment by thelinmichael** [comment]
Related to https://github.com/spotify/web-api/issues/33. (Spotify's repository for tracking feature requests and bug tickets for its [Web API](https://developer.spotify.com/web-api/.)

**Comment by stephanebruckert** [comment]
Closing for now as it's still not implemented by the web API
