### ISSUE TITLE
Authentication Process is missing "Enter the URL you were redirected to:" part 

### ISSUE THREAD

**Issue by AnySomebody1** [plamere/spotipy#474]
Hi,
in the recent git version (as well as in the 2.11 release) the part of the authentication process is missing where one has to enter the URL Spotify redirected to and thus it seems not possible to authenticate the app anymore.

**Comment by jonascj** [comment]
I think it is this issue https://github.com/plamere/spotipy/issues/471

Use `http://localhost:8080` or instead of just `http://localhost` as your redirect url (in both code/envvars and in spotify app settings).

**Comment by AnySomebody1** [comment]
Indeed, it is. With a port it works just fine. I suggest to change the docs accordingly and to modify "The URL doesn’t need to be publicly accessible, so you can specify “http://localhost/”."

**Comment by jonascj** [comment]
I've created PR #477 which deals with this issue.
