### ISSUE TITLE
'User_Playlist_Create' is throwing the '403' error

### ISSUE THREAD

**Issue by jboss10** [plamere/spotipy#484]
Hi Guys - 

Maybe I'm doing something wrong but I successfully created authorization/authentication and can pull and parse songs/album from (2) test playlists I created. However, I'm not able to create a playlist?
Error I'm seeing:
ERROR:spotipy.client:HTTP Error for POST to https://api.spotify.com/v1/users/MYUSRNAME/playlists returned 403 due to You cannot create a playlist for another user.
Traceback (most recent call last):
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.spotify.com/v1/users/MYUSRNAME/playlists

Why is it telling me I'm attempting to create a playlist for another user?

Here is my authorization routine. Also note, I've changed the scope to 'private' and 'public' with no success. I added the 'user_playlist_create' routine in this method just as a test and still fails.

```python
def executeAuthorization(self):
        # Attempt authorization and store our token
        try:
            self.token = util.prompt_for_user_token(self.usrName,
                                                    scope='user-library-read playlist-modify-private',
                                                    client_id = self.clientID,
                                                    client_secret = self.clientSecret,
                                                    redirect_uri = self.redirectURI)

        except:
            os.remove(f".cache-{'username'}")   
            self.token = util.prompt_for_user_token(self.usrName,
                                                    scope='user-library-read playlist-modify-private',
                                                    client_id = self.clientID ,
                                                    client_secret = self.clientSecret,
                                                    redirect_uri = self.redirectURI)

        # Create/store the 'sp' object
        self.sp = spotipy.Spotify(auth = self.token)
        self.sp.user_playlist_create(self.usrName, "Test", public = False)
```

**Comment by stephanebruckert** [comment]
In your browser, your connected spotify user is probably not the same one as `self.usrName`. To change user, add `show_dialog=True` as suggested here https://github.com/plamere/spotipy/issues/451#issuecomment-597794047.

Then, check that `sp.me()` returns the correct user, see https://github.com/plamere/spotipy/issues/464#issuecomment-609411128

**Comment by jboss10** [comment]
Great, I’ll give it a shot and report back. Thanks a bunch!

Why does the ``self.usrName`` work when getting the songs from my playlist? Just curious.

**Comment by ritiek** [comment]
> Why does the ``self.usrName`` work when getting the songs from my playlist? Just curious.

I'm assuming you're using the methods [`Spotify.user_playlist`](https://spotipy.readthedocs.io/en/2.12.0/#spotipy.client.Spotify.user_playlist) or [`Spotify.user_playlist_tracks`](https://spotipy.readthedocs.io/en/2.12.0/#spotipy.client.Spotify.user_playlist_tracks). That's probably because Spotify removed the necessity of passing the username for [fetching playlists](https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlist/) some time ago. See #335. You could pass any username (or `None`) and it should still work.

spotipy hasn't omitted the `user` parameter from existing methods yet since this change wouldn't be backwards compatible with older spotipy versions. You could however use the newer methods [`Spotify.playlist`](https://spotipy.readthedocs.io/en/2.12.0/#spotipy.client.Spotify.playlist) and [`Spotify.playlist_tracks`](https://spotipy.readthedocs.io/en/2.12.0/#spotipy.client.Spotify.playlist_tracks) which do not require the `user` parameter.

**Comment by jboss10** [comment]
Yes, 100% that's what it was. Looks like I was trying to connect to my personal account and not my test environment. DUH!

This is a project so could someone run into this issue when running/testing my script? If so, how to avoid from them using their own personal sign-in?

Thanks!

**Comment by jboss10** [comment]
> > Why does the `self.usrName` work when getting the songs from my playlist? Just curious.
> 
> I'm assuming you're using the methods [`Spotify.user_playlist`](https://spotipy.readthedocs.io/en/2.12.0/#spotipy.client.Spotify.user_playlist) or [`Spotify.user_playlist_tracks`](https://spotipy.readthedocs.io/en/2.12.0/#spotipy.client.Spotify.user_playlist_tracks). That's probably because Spotify removed the necessity of passing the username for [fetching playlists](https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlist/) some time ago. See #335. You could pass any username (or `None`) and it should still work.
> 
> spotipy hasn't omitted the `user` parameter from existing methods yet since this change wouldn't be backwards compatible with older spotipy versions. You could however use the newer methods [`Spotify.playlist`](https://spotipy.readthedocs.io/en/2.12.0/#spotipy.client.Spotify.playlist) and [`Spotify.playlist_tracks`](https://spotipy.readthedocs.io/en/2.12.0/#spotipy.client.Spotify.playlist_tracks) which do not require the `user` parameter.

Ah, OK - great! Thanks so much!
