### ISSUE TITLE
What is wrong with this exact playlist?

### ISSUE THREAD

**Issue by eliasbenb** [plamere/spotipy#486]
I'm trying to get the artist names of tracks in a playlist. [This](https://open.spotify.com/playlist/37i9dQZF1DWSfMe9z89s9B?si=5an1d4msSwOSSWR7LWsF2g) is the playlist link, it is owned by Spotify and has no local tracks. The issue is when I try to get the name I get this error:
```
Traceback (most recent call last):
  File "c:/Users/user/Downloads/test.py", line 21, in <module>
    print(track['track']['artists'][0]['name'])
TypeError: 'NoneType' object is not subscriptable
```
So obviously Spotipy thinks that the artist name doesn't exist, but if you go on the playlist and trace it back to the song you get [this](https://open.spotify.com/artist/20PdOyVym0ZZrOB1rfcvCR?si=gKbHIb_SSb6JUkDz1RIPEQ) profile and it obviously exists. Any ideas why? This is the code:
```
import spotipy
import spotipy.util as util

SPOTIFY_CLIENT_ID = "..."
SPOTIFY_CLIENT_SECRET = "..."
SCOPE = 'playlist-read-collaborative,playlist-read-private,playlist-modify-public,playlist-modify-private'
SPOTIFY_REDIRECT_URI = "http://127.0.0.1:5000/callback"

token = util.prompt_for_user_token("spotify", SCOPE, SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET, SPOTIFY_REDIRECT_URI)

if token:
    sp = spotipy.Spotify(auth=token)
    sp.trace = False
    playlists_soup = sp.current_user_playlists()
    playlist = playlists_soup['items'][4] # 4 is just the playlist index on my profile
    playlist_id = playlist['id']

    tracks = sp.playlist_tracks(playlist_id)
    
    for track in tracks['items']:
        print(track['track']['artists'][0]['name'])
```

**Comment by stephanebruckert** [comment]
To debug your code you should follow my previous advice https://github.com/plamere/spotipy/issues/472#issuecomment-613593131

**Comment by eliasbenb** [comment]
> To debug your code you should follow my previous advice [#472 (comment)](https://github.com/plamere/spotipy/issues/472#issuecomment-613593131)

OK. Thank you, I just did that and it turns out that it isn't the artist that doesn't work, but it's the [track](https://open.spotify.com/track/2OvuQMxW5b0VT8btiNugfL?si=hpwX3WX7Tz2PP3t5oYifww) this is the output I get after printing the track with `pprint(tracks['items'][26])`
```
{'added_at': '2020-04-24T14:14:39Z',
 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/'},
              'href': 'https://api.spotify.com/v1/users/',
              'id': '',
              'type': 'user',
              'uri': 'spotify:user:'},
 'is_local': False,
 'primary_color': None,
 'track': None,
 'video_thumbnail': {'url': None}}
```
So is this an issue on Spotify's side?

**Comment by FOREVEREALIZE** [comment]
Since it's owned by Spotify, they might just have messed something up doing a Database edit.
