### ISSUE TITLE
How to run entirely in a script? (no redirect url)

### ISSUE THREAD

**Issue by PAK90** [plamere/spotipy#488]
I'm trying to use this library to get recently played information from the API, and I will want this script to run automatically without any user intervention. Is it possible to do that with this library? Right now this is my code:
	
    from spotipy.oauth2 import SpotifyOAuth
    token = SpotifyOAuth(
		SPOTIFY_CLIENT_ID,
		SPOTIFY_CLIENT_SECRET,
		'localhost:8000',
		scope='user-read-recently-played',
		username='vacd7qnn09sx0dtj56qtwmix7'
		)

However when I run this it tries to open a window in my browser to get authentication working. The `localhost:8000` url is fake, I don't actually have anything there, I just put it in so it would stop complaining about not receiving a redirect url.

What's the way to have this run without requiring manual intervention? I need this script to run by itself entirely. It seems that having the ID and secret should be enough...

**Comment by stephanebruckert** [comment]
As opposed to the [authorization code flow](https://spotipy.readthedocs.io/en/2.12.0/#authorization-code-flow), you want the [client credentials flow](https://spotipy.readthedocs.io/en/2.12.0/#client-credentials-flow)

**Comment by PAK90** [comment]
The docs tell me that `Only endpoints that do not access user information can be accessed.` I specifically want to access my user details, specifically which songs have been played. Is the documentation wrong and I will be able to access this info?

**Comment by stephanebruckert** [comment]
Sorry I didn't see you needed user info. In that case you have to let the script prompt for sign in at least once so it can retrieve the token. The script should then be able to use the cached token and run without human intervention. 

Currently the token is cached in a file. Different ways of persisting this token are discussed here https://github.com/plamere/spotipy/issues/51

**Comment by busybox11** [comment]
Hey,
I'm using the same method on my daily driver.
I'm using spotipy to get the currently playing track and to control it on a polybar module that I created myself.
However, when I log on my computer, a browser window is always appearing with the `localhost` url and Spotify's code.
How to stop this behaviour ?

**Comment by stephanebruckert** [comment]
@busybox11 interesting, do you have the code under hand? what exact URL does it open (do you have a screenshot)?

I assume that it's opening a browser window because it doesn't have a token, and your script needs a token to run. Do you know where the token is kept? Is it not persisted between computer sessions?

**Comment by busybox11** [comment]
Yes, it's opening a browser window. (Like, with the Spotify login thing).
I used a workaround that someone posted on Mano other issues (I use crontab to copy the cache file)
I can't send a screenshot since it's an almost-headless script (it can run apps tho, but it doesn't have an output)

**Comment by stephanebruckert** [comment]
You shouldn't need crontab. A same token, once generated, can be refreshed an unlimited amount of time.

So just run your script outside of polybar once and you should be good after signing in

**Comment by busybox11** [comment]
Yeah, I did it.
But after each reboot (I don't really know but it's something like this) the cache file isn't being used anymore

**Comment by stephanebruckert** [comment]
Cache file not there means you will have to go through the sign in process again one way or the other.

You need to figure out why this cached file disappears but it's unlikely to be spotipy's fault. Maybe it is in a temporary folder that gets cleared when the system reboots?

**Comment by busybox11** [comment]
Nope, it's in the "polybar scripts" directory

**Comment by stephanebruckert** [comment]
Can you please check if the cached file is still there?

**Comment by stephanebruckert** [comment]
Do you have the code for this polybar script?

**Comment by busybox11** [comment]
Actually, I have two of them. But the login procedure used is the exact same.
This is the script to display the song currently being played.
```PYTHON

import sys
import spotipy
import spotipy.util as util

client_id = 'a636c41f7a2d4436b063807fa746407d'
client_secret = '9c66994e15744b419662a746143fe8a0'
redirect_uri = 'http://localhost/'
scope = 'user-read-currently-playing user-modify-playback-state'

token = spotipy.util.prompt_for_user_token(
    'yha0gdu9143vclyk0cuqoro0m', scope, client_id, client_secret, redirect_uri)

def return_song():
    if current_song != None and current_song != "Spotify":
        print(current_song['item']['name'] + ' - ' + current_song['item']['artists'][0]['name'])
    else:
        if current_song == None:
            print('No song currently playing')
        else:
            print(current_song)

if token:
    sp = spotipy.Spotify(auth=token)
    try:
        current_song = sp.currently_playing()
    except:
        current_song = "Spotify"
    return_song()
else:
    print("Can't get token for", username)
```

**Comment by busybox11** [comment]
Actually, I have two of them.
This is the script used to display the song currently being played.
```PYTHON

import sys
import spotipy
import spotipy.util as util

client_id = 'CLIENT_ID'
client_secret = 'CLIENT_SECRET'
redirect_uri = 'http://localhost/'
scope = 'user-read-currently-playing user-modify-playback-state'

token = spotipy.util.prompt_for_user_token(
    'yha0gdu9143vclyk0cuqoro0m', scope, client_id, client_secret, redirect_uri)

def return_song():
    if current_song != None and current_song != "Spotify":
        print(current_song['item']['name'] + ' - ' + current_song['item']['artists'][0]['name'])
    else:
        if current_song == None:
            print('No song currently playing')
        else:
            print(current_song)

if token:
    sp = spotipy.Spotify(auth=token)
    try:
        current_song = sp.currently_playing()
    except:
        current_song = "Spotify"
    return_song()
else:
    print("Can't get token for", username)
```

**Comment by stephanebruckert** [comment]
util.prompt_for_user_token(
        'yha0gdu9143vclyk0cuqoro0m', scope, client_id, client_secret, redirect_uri)

this is a util that should not be used "in production". It should be ran "locally" only and can only be ran once.

Instead of:

    token = spotipy.util.prompt_for_user_token(
       'yha0gdu9143vclyk0cuqoro0m', scope, client_id, client_secret, redirect_uri)
    sp = spotipy.Spotify(auth=token)

Do this instead:

    creds = SpotifyOAuth(scope=scope, client_id=client_id, client_secret=client_secret, redirect_uri=redirect_uri)
    sp = spotipy.Spotify(client_credentials_manager=creds)

Hope that fixes it

**Comment by PAK90** [comment]
So I ran this:

    token = util.prompt_for_user_token(
		'userstring'
		'user-read-recently-played',
		client_id=SPOTIFY_CLIENT_ID,
		client_secret=SPOTIFY_CLIENT_SECRET,
		redirect_uri='http://localhost:8080',
		)

After doing this successfully, I got a local .cache file. However, I don't know how to use this and refresh it accordingly? The docs also don't say. From your response above, I tried doing this:

    creds = SpotifyOAuth(
		client_id=SPOTIFY_CLIENT_ID,
		client_secret=SPOTIFY_CLIENT_SECRET,
		redirect_uri='http://localhost:8080',
		scope='user-read-recently-played',
		)
	sp = spotipy.Spotify(creds)
	user = sp.user('userstring')
	print(sp.current_user_recently_played())

However I get a 400 Client Error: Bad Request for url: https://api.spotify.com/v1/users/userstring, Only valid bearer authentication supported. How do I do this properly?

**Comment by stephanebruckert** [comment]
@PAK90 the token is refreshed automatically, so you don't need: 

    token = creds.get_cached_token()
    
Also you don't need `util.prompt_for_user_token` anymore, just do `spotipy.Spotify(client_credentials_manager=creds)`.

Lately there has been a lot of changes around how we get the first token and refresh it. The doc might still need a round of updates to reflect that by deprecating `util.prompt_for_user_token`

**Comment by varna9000** [comment]
H @stephanebruckert , do you know why the current playing song method hangs ( `sp.currently_playing()` ) ? Basically I'm using the `spotipy.Spotify(client_credentials_manager=creds) ` auth method you recommend here.

**Comment by stephanebruckert** [comment]
Make sure you use the latest version of spotipy: `pip install spotipy --upgrade`. If the problem persists, please create a new issue with a minimal working example

**Comment by varna9000** [comment]
Ok, thanks. I've got the latest release. I'll open new issue.

**Comment by stephanebruckert** [comment]
`util.prompt_for_user_token` is now deprecated and the docs now suggest to use the auth manager instead. Closing as all questions here should be answered
