### ISSUE TITLE
Exact search for artist name possible? 

### ISSUE THREAD

**Issue by Musikfreitag** [plamere/spotipy#489]
When I use "sp.search()", then I get results that contain the string anywhere in the hit result. Is it possible to do an exact search?

**Example for the query "LEA"**
results = sp.search(q='artist:' +'LEA', type='artist')
items = results['artists']['items']
for i in range(len(items)):
      print(items[i]['name']+"\t"+str(items[i]['followers']['total']))

**Current Results:** 
League of Legends       621187
Lea Salonga     118225
Christian Leave 178686
Yung Lean       418445
Leavv   13121
LeAnn Rimes     715975
The Human League        597907
Lea Michele     429499
Pure Prairie League     116541
Leah Maur       141

**Expected Result:** 
LEA     446601

The current results are not sorted and the expected hit is not in the top 50 results, so adding "limit = 50" does not help. I am happy about any help for this issue, even it is a link to a part of the documentation that I missed.

**Comment by ritiek** [comment]
Doesn't seem like Spotify offers making proper exact searches as of yet. Spotify includes a section on advanced search but none of them help with your example use-case:

https://developer.spotify.com/documentation/web-api/reference/search/search/
https://community.spotify.com/t5/Social/Is-there-a-n-extended-Spotify-search-syntax/td-p/1014655

-----------

The link https://support.spotify.com/us/using_spotify/features/search/ mentions:
> Enter your search term in quotation marks “” to narrow results to exact matches, e.g. “Let’s Dance”.

But it doesn't seem to be working for your example artist search.

There has also been a support question asked on https://community.spotify.com/t5/iOS-iPhone-iPad/Search-need-an-quot-exact-match-quot/td-p/1116711 but doesn't have a satisfactory answer that works for your example use-case.

Hard luck I guess. :(
