### ISSUE TITLE
Is it possible to create a new device?

### ISSUE THREAD

**Issue by bar513** [plamere/spotipy#490]
I couldn't find any documentation for it but it seems very possible - Is Spotipy support making the device that runs the script as a spotify device? or I can just control existing devices?

If this option is not available through Spotipy, is this option available through the spotify API without too much trouble?

**Comment by stephanebruckert** [comment]
spotipy can only do what the spotify web API can do. 

This question seems better suited for https://github.com/spotify/web-api/
