### ISSUE TITLE
Authentication hangs when ran in headless mode

### ISSUE THREAD

**Issue by varna9000** [plamere/spotipy#492]
Hi, I've got the latest release 2.12.0. My simple code is the following:

```
import spotipy
from spotipy import SpotifyOAuth

client_id = 'xxxxxxxxx'
client_secret = 'xxxxxxxxx'
redirect_uri = 'http://127.0.0.1:8081/'
scope = 'user-read-currently-playing'
username='xxxxxxx'

creds = SpotifyOAuth(username=username, scope=scope, client_id=client_id, client_secret=client_secret, redirect_uri=redirect_uri)
sp = spotipy.Spotify(client_credentials_manager=creds)

print(dir(sp))

try:
    current_song = sp.currently_playing()
    print(current_song)
except:
    raise
```

It seems the line `current_song = sp.currently_playing()` hangs the code as it doesn't even raise an exception. I've tried calling other methods but it's the same result. Am I doing something wrong?

**Comment by stephanebruckert** [comment]
Since you need to sign in with your own spotify account via the browser, spotipy should have opened a browser window. So, bunch of questions:

 - did a browser window open?
 - did it automatically close (success)?
 - or did it fail and there is an error message on that web page?

spotipy currently hangs if the authentication response is not successful, which is something we might want to fix! But first let's try to make it for you

**Comment by varna9000** [comment]
Trouble is, I'm using headless Raspbian Lite install, so there's no browser and GUI. I thought that if all credentials match, including the redirect UTI, all would be done automatically. Isn't that the case?

**Comment by varna9000** [comment]
Ok, I installed Links and now it's automatically opened. The page is not showing correctly only in console, so I copied the url to my GUI browser and I saw the Spotify permission dialog. When I clicked "Agree" it redirects me to 127.0.0.1 (i.e. my Redirect URI), but naturally there is nothing there, since I opened it in another computer (with GUI). I thought that if you set localhost and 127.0.0.1 this Agree process is handled automatically. This was my impression from the docs,  but apparently this is not the case.

**Comment by varna9000** [comment]
Phew, managed to do it, but it shouldn't be that hard. I set 127.0.0.1 as call-back URL (no port). "Links" browser automatically opened, I copied the URL  (from processes list "ps ax") and pasted in GUI browser on another computer, clicked "Agree", then copied the full 127.0.0.1 redirect url, quit "Links" and pasted the url in the dialog prompt ("Enter the URL you were redirected to:") . Done. Quite a workaround.

**Comment by stephanebruckert** [comment]
- another possibility is to run the script on a different computer and copy the cache file to the raspbian
 - in the future to avoid copying the file from one machine to the other, the token could be stored in the cloud https://github.com/plamere/spotipy/issues/51
 - from your experience, what's currently missing to better help future users? do you think we need a headless mode that prints the URL? in case you would like to open a PR that'd be very welcome!  🙏

**Comment by NLeRoy917** [comment]
If you need a 100% headless mode, I've actually done this before with Spotify's client credentials flow. It uses selenium to drive a headless browser, insert the client credentials, and write the tokens to the environment, so you don't ever have to deal with typing in your credentials when running scripts.

I wrote it awhile ago - so it isn't the cleanest code, but it actually worked extremely well. It's [here](https://github.com/NLeRoy917/spotify-playlist-analyzer/blob/master/lib/authorize.py).

**Comment by varna9000** [comment]
@stephanebruckert 

> from your experience, what's currently missing to better help future users? do you think we need a headless mode that prints the URL? in case you would like to open a PR that'd be very welcome!

I would imagine, most people don't use headless installs but printing of the url would be of a huge help. Not sure I can contribute with a PR but will try.

@NLeRoy917 nice! I'll look into it.

**Comment by stephanebruckert** [comment]
In fact this is how it was working in version 2.10.0; the URL was printed and it was prompting for the resulting URL. PR https://github.com/plamere/spotipy/pull/243 was merged to make that process automatic 

Now I see 3 solutions for the headless mode:
 
 - use 2.10.0: `pip3 install 'spotipy~=2.10.0'`
 - keep the current version 2.12.0 and set a `REDIRECT_URI` without any port, it will "magically" prompt for the URL (exactly what you need). More info in this PR https://github.com/plamere/spotipy/pull/477 and in the [doc](https://spotipy.readthedocs.io/en/2.12.0/):

    > If your request URI is set to any other URI you will need to manually copy the URI from the browser’s address bar and paste it into the terminal/console where your Spotipy script is running (Spotipy will instruct you to do so).
 - (ideally) we could bring the manual mode back by adding a `headless` parameter (defaults to `False`) in the `SpotifyOAuth` constructor: https://github.com/plamere/spotipy/blob/587baec9b95da6c45e45f0f8e5b2577bda780980/spotipy/oauth2.py#L200

**Comment by smalls12** [comment]
I'm bumping into the same issue now re: headless mode.

Should I make make a separate PR to discuss and possibly implement your ideal solution above?
