### ISSUE TITLE
How to terminate token process if user exits authentication page?

### ISSUE THREAD

**Issue by StephenChou** [plamere/spotipy#495]
So in my web app I'm trying to account for the possibility that a user exits the Spotify authentication page without authenticating. How do I terminate the process? I have an "if token ... else return false" statement for the token but it doesn't seem to get there, it just stays running.

**Comment by ysinjab** [comment]
Assuming you are using authorization code: the user is **unauthorized** until he **login** & and **give** your application the **authorization** to access the scopes. https://tools.ietf.org/html/rfc6749#section-1.3.1

**Comment by stephanebruckert** [comment]
@stephenchou indeed the default is that if you do the following it will prompt and block if the spotipy authentication window is closed:

```
auth_manager = spotipy.oauth2.SpotifyOAuth()
spotify = spotipy.Spotify(auth_manager=auth_manager)

spotify.me()
```

To prevent prompting what you want to do is call `auth_manager.get_access_token(code)` before calling `spotify.me()`. A good example that does this is the API example https://github.com/plamere/spotipy/blob/master/examples/app.py where each action is separate and therefore won't block the main process

**Comment by StephenChou** [comment]
@stephanebruckert Thanks for your response. I forgot to mention that I'm using the "prompt_for_user_token" function and it doesn't seem to be returning false when I exit the authorization webpage without authenticating. Should I avoid using that then?

**Comment by stephanebruckert** [comment]
@StephenChou do you mean that it behaves as expected with `auth_manager` but doesn't with `prompt_for_user_token`?

**Comment by StephenChou** [comment]
@stephanebruckert Haven't tried auth manager yet, was hoping that I could possibly still use prompt_for_user_token, which doesn't seem to be hitting my false condition when I exit the authentication page. I guess I should probably try auth_manager then.

**Comment by stephanebruckert** [comment]
Yeah I doubt it will be any different with the auth_manager. If the authentication page is closed, I can't see how the python app could know about it because nothing is sent to the redirect URI. If this is a problem for you I really suggest you do something similar to the API example

**Comment by stephanebruckert** [comment]
Your solution is [here](https://github.com/plamere/spotipy/blob/master/FAQ.md#how-to-use-spotipy-in-an-api), closing
