### ISSUE TITLE
the results for the method 'search'

### ISSUE THREAD

**Issue by psenoglu** [plamere/spotipy#496]
Hello,

I am trying to get the genres of the artist with the sp **search**. 
Spotify provides this information already with their Search for an Item APIs. Since I have already tried with the following code, there comes no genre in the output. 

The code I used: 
```
from spotipy.oauth2 import SpotifyClientCredentials
import spotipy
import sys
import pprint

if len(sys.argv) > 1:
    search_str = sys.argv[1]
else:
    search_str = 'Weezer'

sp = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials())
result = sp.search(search_str)
pprint.pprint(result)
```

I am really a beginner so I appreciate any help.

Thanks in advance.

**Comment by ritiek** [comment]
Hi! You need to explicitly specify in [`sp.search`](https://spotipy.readthedocs.io/en/2.12.0/#spotipy.client.Spotify.search) that you wish to search for artists (otherwise the search will default to tracks). For example:
```python
# Search "Green Day" in artists and return only the first result
result = sp.search("green day", limit=1, type="artist")
artists = result["artists"]
print(artists["items"][0]["genres"])
```

**Comment by psenoglu** [comment]
thanks a lot @ritiek
