### ISSUE TITLE
to search multiple artist with the sp search

### ISSUE THREAD

**Issue by psenoglu** [plamere/spotipy#498]
Hi,

I am writing a totally basic code to get the genres of the artist. 
but when I try to create the string with more than one artist, it takes only the last one and search with this artist.
I know It is very basic and easy but I can not make it through.
Could someone help me with this problem. I dont even know with which keywords I should try on Google.

Thanks a lot, I appreciate it!

`
```
from spotipy.oauth2 import SpotifyClientCredentials
import spotipy
import sys
import pprint

search_string = "Muse" and "radiohead"
sp = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials())
result = sp.search(search_string, limit=10, type="artist");

print (result)
```
`

**Comment by stephanebruckert** [comment]
search_string = "Muse" and "radiohead"

this is boolean logic and will result in "radiohead" because the first one "muse" is not `True`.

Anyway, you want the whole thing to be a string:

    search_string = '"Muse" and "radiohead"'

**Comment by psenoglu** [comment]
that comes as output... 
`
{u'items': [], u'next': None, u'href': u'https://api.spotify.com/v1/search?query=%22Muse%22+and+%22radiohead%22&type=artist&offset=0&limit=50', u'limit': 50, u'offset': 0, u'total': 0, u'previous': None}`

**Comment by stephanebruckert** [comment]
also try `AND` instead of `and`

please also consult the docs https://developer.spotify.com/documentation/web-api/reference-beta/#writing-a-query---guidelines
