### ISSUE TITLE
Support for Implicit Grant Flow

### ISSUE THREAD

**Issue by IdmFoundInHim** [plamere/spotipy#499]
For an app I am building, [Implicit Grant Flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#implicit-grant-flow) is the ideal authentication method. Using Spotipy would save me a lot of time, so I am willing to do some work to add support. Is there a particular reason that Spotipy skipped support for one authentication method? Also, if I add support in a fork, could I reasonably expect to get it merged here?

**Comment by stephanebruckert** [comment]
> Implicit grant flow is for clients that are implemented entirely using JavaScript and running in the resource owner’s browser.

perhaps you are looking for https://github.com/jmperez/spotify-web-api-js?

**Comment by IdmFoundInHim** [comment]
I would like to stick to Python. I figured that that part was explaining only that no server-side code was needed, so I do not know of any reason that a Python client could not do it (with a browser, of course). Has it been attempted?

**Comment by stephanebruckert** [comment]
Indeed that could be useful in the case of a serverless python client.

Definitely @IdmFoundInHim if you manage to implement this we would merge it!
