### ISSUE TITLE
Weird/intermittent Behaviour: JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by nicolaka** [plamere/spotipy#50]
I had this working for 2+ months but today it was erroring intermittently????
Would appreciate your help!

```
> > > type(user)
> > > <class 'spotipy.client.Spotify'>
> > > user_saved_tracks= user.current_user_saved_tracks(limit=50)
> > > user_saved_tracks= user.current_user_saved_tracks(limit=50)
> > > user_saved_tracks= user.current_user_saved_tracks(limit=50)
> > > user_saved_tracks= user.current_user_saved_tracks(limit=50)
> > > user_saved_tracks= user.current_user_saved_tracks(limit=50)
> > > user_saved_tracks= user.current_user_saved_tracks(limit=50)
> > > Traceback (most recent call last):
> > >   File "<console>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/spotipy/client.py", line 466, in current_user_saved_tracks
> > >     return self._get('me/tracks', limit=limit, offset=offset)
> > >   File "/usr/local/lib/python2.7/dist-packages/spotipy/client.py", line 120, in _get
> > >     return self._internal_call('GET', url, payload, kwargs)
> > >   File "/usr/local/lib/python2.7/dist-packages/spotipy/client.py", line 104, in _internal_call
> > >     -1, u'%s:\n %s' % (r.url, r.json()['error']['message']))
> > >   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 799, in json
> > >     return json.loads(self.text, **kwargs)
> > >   File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 505, in loads
> > >     return _default_decoder.decode(s)
> > >   File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
> > >     obj, end = self.raw_decode(s)
> > >   File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
> > >     return self.scan_once(s, idx=_w(s, idx).end())
> > > JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by stephanebruckert** [comment]
Issue being 5 year old, would need to know if this is still happening. Closing for now

**Comment by tahsinac** [comment]
Have been using the library with no issues daily up until today. Getting this error now all of a sudden.

`  File "C:\projects\nplyrbot\nplyrbotpy.py", line 99, in <module>
    lyrics_current, current = nplyrbot()
  File "C:\projects\nplyrbot\nplyrbotpy.py", line 8, in nplyrbot
    token = util.prompt_for_user_token(username, scope, client_id=client_id, client_secret=client_secret, redirect_uri=redirect_uri)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotipy\util.py", line 88, in prompt_for_user_token
    token_info = sp_oauth.get_cached_token()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotipy\oauth2.py", line 253, in get_cached_token
    token_info = json.loads(token_info_string)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by tahsinac** [comment]
Have been using the library with no issues daily up until today. Getting this error now all of a sudden.

`File "C:\projects\nplyrbot\nplyrbotpy.py", line 99, in <module> lyrics_current, current = nplyrbot() File "C:\projects\nplyrbot\nplyrbotpy.py", line 8, in nplyrbot token = util.prompt_for_user_token(username, scope, client_id=client_id, client_secret=client_secret, redirect_uri=redirect_uri) File "C:\ProgramData\Anaconda3\lib\site-packages\spotipy\util.py", line 88, in prompt_for_user_token token_info = sp_oauth.get_cached_token() File "C:\ProgramData\Anaconda3\lib\site-packages\spotipy\oauth2.py", line 253, in get_cached_token token_info = json.loads(token_info_string) File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 354, in loads return _default_decoder.decode(s) File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 339, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 357, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
