### ISSUE TITLE
Acquiring token but running endlessly on Colab

### ISSUE THREAD

**Issue by QAQOAO** [plamere/spotipy#502]
I use the code below to acquire token on Google Colab.

username = 'username..'

clientID = 'id...'
clientSecret = 'secret..'
redirectURL = 'http://localhost:8888/'

token = spotipy.util.prompt_for_user_token(username, client_id=clientID, client_secret=clientSecret, redirect_uri=redirectURL)

When I execute the code, that cell just running for very long time but still not opening a page

It worked fine several months ago, but what happened?

**Comment by stephanebruckert** [comment]
Can Google Colab open URL and expect an answer? Are you sure this was possible before? Any chance you can try with a previous version and let us know:

```
pip3 install 'spotipy~=2.11.0'
pip3 install 'spotipy~=2.10.0'
pip3 install 'spotipy~=2.9.0'
... 
// stop at 2.5.0
```

**Comment by stephanebruckert** [comment]
@QAQOAO is this still blocking you?

**Comment by stephanebruckert** [comment]
This is what you need https://github.com/plamere/spotipy/blob/master/FAQ.md#how-do-i-obtain-authorization-in-a-headlessbrowserless-environment
