### ISSUE TITLE
Error 401: No token provided

### ISSUE THREAD

**Issue by ElementO2512** [plamere/spotipy#504]
Hey,
Basically when ever I try to run this script I get a 'No token provided' error.
Heres my code:

`import spotipy
#import python-util
import os
from spotipy.oauth2 import SpotifyClientCredentials

os.environ["SPOTIPY_CLIENT_ID"] = "(my client id)"
os.environ["SPOTIPY_CLIENT_SECRET"] = "(my client secret)"
client_credentials_manager = SpotifyClientCredentials()
sp = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials())

spotipy.prompt_for_user_token(username='', scope='', client_id='(my client id)', client_secret='(my client secret)', redirect_uri='http://localhost:9090')

spp = spotipy.Spotify()

songinfo = spp.current_playback(market=None)
print('songinfo')`

What code do I need to add to make this work?

**Comment by anpanval** [comment]
I have the same issue today, everything worked well yesterday with the same code.

**Comment by ElementO2512** [comment]
Hey,
Thanks for the answer
Are you able to provide an example of the code I should add
I'm quite new to python and don't know a whole lot

**Comment by ElementO2512** [comment]
Hey Thanks for the Answer
Realised Im really retarded and already had the right thing but wasn't using it
My code now looks like this:
`import spotipy
import os
from spotipy.oauth2 import SpotifyClientCredentials

os.environ["SPOTIPY_CLIENT_ID"] = "688545512c0941e0be43e0ca840bd116"
os.environ["SPOTIPY_CLIENT_SECRET"] = "49205b6a5f8946e8835d2596d5d7418c"
client_credentials_manager = SpotifyClientCredentials()
sp = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials())

spotipy.prompt_for_user_token(username='', scope='user-read-currently-playing', client_id='688545512c0941e0be43e0ca840bd116', client_secret='49205b6a5f8946e8835d2596d5d7418c', redirect_uri='http://localhost:9090')

songinfo = sp.current_playback(market=None)
print('songinfo')`

I'm now getting a 404 Invalid username error. I'm guessing this is because `username=''` is blank. What should I put here?

**Comment by ElementO2512** [comment]
`test`

**Comment by stephanebruckert** [comment]
We just deprecated `prompt_for_user_token`, check out this example https://github.com/plamere/spotipy#with-user-authentication, this is all you need:

    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=scope))
