### ISSUE TITLE
Spotify Playlist, auto rewrite title and description

### ISSUE THREAD

**Issue by Benjii1993** [plamere/spotipy#506]
Hi everyone,

first of all I must say I'm NOT a Python expert. In reality, I've never even used Python, but I know that it is a super powerful tool, useful in many contexts, also in Spotify.

2nd disclaimer: English is not my first language so I'll try to explain what I want to ask in the best way possible.

So, this is my problem:

I am a playlist curator on Spotify, with more than 50.000 followers over all through out all my playlist.

Lately, people started falsely reporting playlists on Spotify to gain a better rank in Spotify search algorithm. (if you search on the web, you will find that is becoming more and more common)

Each time a playlist is reported, the title, description and image disappear BEFORE the Spotify team check if the report is actually true or not. You will understand that this leads to a MASSIVE abuse of this tool, you just need to fill a form with name, telephone number and email and you can make this report. Obviously, people are filling this form with fake mails and identities.

This means that a fraudulent user can report your playlist 10000000 times a day, and there is nothing you can do against it, because if Spotify bans his fake "mail" he will fill the form with another fake email. This also means that if the reporter flag my playlist 10.000 times, I have to rewrite title, caption and upload user 10.000 times, and it is absolutely absurd. I sent hundreds of mail to the spotify team, they told me they are working to fix it, but currently there is no way to stop this (THIS IS CRAZY!)

So my question is: is there a way to create a code with Python, that auto rewrite the title of a playlist each time Python sees the title has disappeared?

For example:

The reporter reports my playlist --> Title, Description and Image are gone (until I don't rewrite them again)

Python notices that the title is gone and automatically rewrite the title and caption

Do you think this is possible?

I am willing to pay for someone making this code for me, because these fake reports are becoming more and more frequent, and as a music blogger, Spotify Playlists are a part of my income. I can't stay 24/7 at home rewriting the titles of my falsely reported playlist (with no reason)

Hope this was clear enough, thank you!

**Comment by stephanebruckert** [comment]
It is possible and you can certainly do that with spotipy, however this repo is not the place to find contractors, so I'm closing this
