### ISSUE TITLE
Abstraction of caching code

### ISSUE THREAD

**Issue by mikejewell** [plamere/spotipy#51]
I'm using spotipy on Heroku as a Slack bot - which works awesomely, but I've had to store the cached token on S3. I've extended SpotifyOAuth and overridden get_cached_token and _save_token_info to do this, but it'd be useful if it was possible to do this without extensio?. This would also allow for storing the token in a DB rather than in a file.

Maybe the simplest approach could be load_cached_token and save_cached_token methods, which can be overridden to cater for different storage approaches?

**Comment by arska** [comment]
I had the same problem, see #61 for my workaround

**Comment by markuman** [comment]
redis as caching engine would be nice

**Comment by theTechGuyy** [comment]
Has there been any update on this so it is possible to use a different matter of saving sessions but file system?
Cannot seem to find any, but I might be blind / not understand well enough
