### ISSUE TITLE
Client side app, getting users to make developer accounts

### ISSUE THREAD

**Issue by thomasfdm** [plamere/spotipy#510]
Hi,

I'm looking to make a mod for a game which allows you to, in limited ways, control your local Spotify Desktop application (so not actually streaming just sending playback commands).

The issue I'm facing is this: 
I'd need to authenticate the user somehow and I plan on bascially running spotipy as an install script outside the game to authenticate the user then grabbing the tokens and putting them somewhere the mod's code can get to.

Since this will obviously be a client side program if I used my developer secret token anyone could grab it from the source code. So my question was if it's possible under Spotify's terms to get users to generate their own developer accounts and use their client secret which they paste in as part of the install script? Is this unfairly circumventing rate limiting?

**Comment by stephanebruckert** [comment]
Hey @thomasfdm,

My guess is that asking users to create their own app wouldn't be a problem but this is something you should confirm by asking on https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer

The [Implicit Grant Flow](https://github.com/plamere/spotipy/issues/499) can be another possibility for you. It would let users use your Spotify app without sharing the secret. However this has yet to be implemented

**Comment by thomasfdm** [comment]
Cool, I'll drop them as ask. and I'll have a look at implicit granting. Also, is there any general recommendations for how to store user tockens on disk that's accessible by multiple programs?

**Comment by DJSdev** [comment]
If pull request #542 is accepted, using the SpotifyPCKE auth-manager, users will be able to authorize your app without needing to reveal/store your client secret within the app. This is the Spotify's preferred method for authorization.

**Comment by stephanebruckert** [comment]
Going to close this as you can now use the PKCE auth manager as explained by @DJSdev
