### ISSUE TITLE
AttributeError: module 'spotipy' has no attribute 'spotify'

### ISSUE THREAD

**Issue by Soheab** [plamere/spotipy#511]
i keep getting this error 

```py
Traceback (most recent call last):
  File "C:\Users\yes\OneDrive\Documents\bots\Sparkly\Sparkly3.0\cogs\owner.py", line 608, in eval
    ret = await func()
  File "<string>", line 3, in func
AttributeError: module 'spotipy' has no attribute 'spotify'
```

with this code:

```py
import spotipy
sp = spotipy.Spotify(auth="Client Secret here, yes")
return sp
```

**Comment by stephanebruckert** [comment]
Check if you already have a file called spotipy.py in your folder/project

**Comment by Soheab** [comment]
> Check if you already have a file called spotipy.py in your folder/project

i don't. even dir() shows it has it soo idk 
![image](https://user-images.githubusercontent.com/33902984/84525004-32e67200-acdb-11ea-9138-71648fec9eb2.png)

**Comment by Soheab** [comment]
ahh i see why, it's a issue with my bot, sorry.

**Comment by stephanebruckert** [comment]
@Soheab great but what was it? might be useful for someone else

**Comment by Soheab** [comment]
> @Soheab great but what was it? might be useful for someone else

oh it's 100% my mistake, i overwrote something called "get_context" so it lowers everything, that's what i did in the eval command.
