### ISSUE TITLE
Headless mode support

### ISSUE THREAD

**Issue by smalls12** [plamere/spotipy#519]
Continuing on from Issue https://github.com/plamere/spotipy/issues/492
Support for a headless parameter

https://github.com/plamere/spotipy/issues/492 described a few possible scenarios.

The ideal implementation involved adding a headless parameter in the SpotifyOAuth constructor.

Just restarting the conversation, if there is any appetite for it.

For context, I'm running spotipy on my raspberry pi without any frontend GUI. The OS was built from scratch with buildroot.

The rpi is operating as a wireless node that can connect to spotify and play music over a connected speaker.

Disclaimer, I could implement what @stephanebruckert noted but I'm hoping for some support as I'm not really sure about the internals of connecting with spotify via the web API.

**Comment by stephanebruckert** [comment]
Sorry didn't see your comment here https://github.com/plamere/spotipy/issues/492

Sure feel free to create a PR. Basically the PR is about skipping this bit:

https://github.com/plamere/spotipy/blob/587baec9b95da6c45e45f0f8e5b2577bda780980/spotipy/oauth2.py#L374..L383

if the new headless option is set to True
