### ISSUE TITLE
How to get the redirect URL from SSH ?

### ISSUE THREAD

**Issue by 20100times** [plamere/spotipy#520]
Hello,

First of all thank you for your work, that's awesome !
I'm facing an issue which is probably pretty simple but I don't see any solution.

I'm running a python script on a raspberry pi via SSH so no webbrowser will open. How can I get the redirect url when the program asks me `Enter the URL you were redirected to: ` ?
If anyone has an idea about that it would be nice.

Thank you !

**Comment by stephanebruckert** [comment]
You are not the only one who needs this, see other open issues https://github.com/plamere/spotipy/issues/492, https://github.com/plamere/spotipy/issues/519
