### ISSUE TITLE
Be able to run my .py without SPOTIPY_CLIENT_ID & SPOTIPY_CLIENT_SECRET 

### ISSUE THREAD

**Issue by AZELLAX** [plamere/spotipy#521]
Hello, 
I think that it could be good that we can run our .py file without SPOTIPY_CLIENT_ID & SPOTIPY_CLIENT_SECRET in the console 
Because we should do that in our code  spotipy.util.prompt_for_user_token(username, scope=None, client_id=None, client_secret=None, redirect_uri=None, cache_path=None, oauth_manager=None, show_dialog=False) and I don't want to use redirect_uri

**Comment by stephanebruckert** [comment]
You already can by using `SpotifyClientCredentials`, see parameters from https://spotipy.readthedocs.io/en/2.13.0/#spotipy.oauth2.SpotifyClientCredentials
