### ISSUE TITLE
Python how to play songs without redirect uri (only using IDLE)

### ISSUE THREAD

**Issue by Raj-Dave368** [plamere/spotipy#523]
This is my Code:

import spotipy
from spotipy.oauth2 import SpotifyOAuth
from pprint import pprint
from time import sleep

scope = "user-read-playback-state,user-modify-playback-state"
sp = spotipy.Spotify(client_credentials_manager=SpotifyOAuth(scope=scope))

res = sp.devices()
pprint(res)

sp.start_playback(uris=['spotify:track:6gdLoMygLsgktydTQ71b15'])

sp.volume(100)
sleep(2)
sp.volume(50)
sleep(2)
sp.volume(100)

I just want to play this song in my device using only python IDLE 
how can i do it 

If I specify localhost as a redirect uri then i got error that   "specify some port"
if i specify port then i got error  that is "code is not provided"
spotipy.oauth2.SpotifyOauthError: error: invalid_request, error_description: code must be supplied

what should i do

**Comment by stephanebruckert** [comment]
Does IDLE open your web browser at any point?

**Comment by Raj-Dave368** [comment]
Yes for sure, i have enter passwords but after that console produces an error

**Comment by Raj-Dave368** [comment]
I was a beginner and was doing the wrong things, there was no issue.
