### ISSUE TITLE
Search through all markets at once

### ISSUE THREAD

**Issue by stephanebruckert** [plamere/spotipy#525]
**Is your feature request related to a problem? Please describe.**

 - currently searches default to the US market and need separate requests for other markets (CA, GB, FR, DE...) 
 - is an issue when building playlists for anyone in the world
 - https://github.com/spotify/web-api/issues/194

**Describe the solution you'd like**
Add options to the `search` function to allow searching multiple markets at once:

 - allow passing an array of country codes 
 - allow passing "ALL"
 - have an option to return as soon as `n` results are found

**Additional context**
This will not be performant due to the amount of requests, appropriate warnings should be given

**Comment by NLeRoy917** [comment]
I can give this a shot - I agree this might make a lot of requests, but in my experience, Spotify is pretty generous with API rate limiting

**Comment by shillshocked** [comment]
How do we use this experimental functionality to search through all markets at once? I tried:
sp.search(search_str, offset=off, limit=50, type='album', market='ALL')

And got:
HTTP Error for GET to https://api.spotify.com/v1/search returned 400 due to Invalid market code

**Comment by stephanebruckert** [comment]
@shillshocked https://spotipy.readthedocs.io/en/2.16.0/#spotipy.client.Spotify.search_markets

**Comment by shillshocked** [comment]
OK, I try sp.search_markets(search_str, offset=off, limit=50, type='album') and get the same error. Also same results with:
sp.search_markets(search_str, offset=off, limit=50, type='album', market='ALL')

**Comment by shillshocked** [comment]
I noticed that there are only 60 markets in client.py, but Spotify actually has at least 92 country codes. It should be updated to include them all, or you can just specify markets=['AL','DZ','AD','AR','AU','AT','BH','BY','BE','BO','BA','BR','BG','CA','CL','CO','CR','HR','CY','CZ','DK','DO','EC','EG','SV','EE','FI','FR','DE','GR','GT','HN','HK','HU','IS','IN','ID','IE','IL','IT','JP','JO','KZ','XK','KW','LV','LB','LI','LT','LU','MY','MT','MX','MD','MC','ME','MA','NL','NZ','NI','MK','NO','OM','PS','PA','PY','PE','PH','PL','PT','QA','RO','RU','SA','RS','SG','SK','SI','ZA','ES','SE','CH','TW','TH','TN','TR','UA','AE','GB','US','UY','VN'] in the search.

**Comment by shillshocked** [comment]
Weird, if I restrict it to just one country, like albums = {**results['SA']['albums']}, I get more results. Which doesn't make sense, because Saudi Arabia should have fewer releases. Maybe using just one country somehow merges them all, or perhaps my merging is just erasing previous matches.

**Comment by NLeRoy917** [comment]
[Here](https://github.com/plamere/spotipy/pull/526#discussion_r449566091) is conversation I had with @stephanebruckert about which market codes to include. Spotify (to my knowledge) doesn't say which market codes they support and that was the most reliable and recent list I could find.

**Comment by shillshocked** [comment]
I got those country codes directly from http://everynoise.com/new_releases_by_genre.cgi which is run by a Spotify employee. They should be the most recent.

**Comment by shillshocked** [comment]
Interestingly, I tried using the Spotify API directly, and then compared the results to a Spotipy search with a default installation (it normally has 60 countries in client.py):

it's the same track, the difference is spotify api checking all 250 markets one at a time, and spotipy checking all at once.

With spotipy checking available markets, it found Ed Sheeran's "Shape of You" available in 184 markets. With the web api checking 250 markets individually, it found it available in each.

Spotify API with Spotipy (available_markets() all at once): This method gives you a list of available markets for a specific track in a single request, but it may return fewer markets due to specific track availability data that includes licensing restrictions, regional differences, or a limited set of markets.

Spotify API Checking All 250 Markets Individually: This approach checks each of the 250 markets individually, which might not be restricted by licensing agreements and could show more markets where the track is available.

The key reason for the difference is that when checking markets one by one, you're likely querying availability for the track in all Spotify markets, without the restrictions that available_markets() imposes. On the other hand, when you use available_markets(), the response is limited to those markets where the track is explicitly available, which reflects licensing and distribution rights.

And an update for client.py:
(copy client.py to client.bak first)

    def search_markets(self, q, limit=10, offset=0, type="track", markets=None, total=None):

for 184 markets, change to:

    def search_markets(self, q, limit=10, offset=0, type="track", markets=['AR','AU','AT','BE','BO','BR','BG','CA','CL','CO','CR','CY','CZ','DK','DO','DE','EC','EE','SV','FI','FR','GR','GT','HN','HK','HU','IS','IE','IT','LV','LT','LU','MY','MT','MX','NL','NZ','NI','NO','PA','PY','PE','PH','PL','PT','SG','SK','ES','SE','CH','TW','TR','UY','US','GB','AD','LI','MC','ID','JP','TH','VN','RO','IL','ZA','SA','AE','BH','QA','OM','KW','EG','MA','DZ','TN','LB','JO','PS','IN','BY','KZ','MD','UA','AL','BA','HR','ME','MK','RS','SI','KR','BD','PK','LK','GH','KE','NG','TZ','UG','AG','AM','BS','BB','BZ','BT','BW','BF','CV','CW','DM','FJ','GM','GE','GD','GW','GY','HT','JM','KI','LS','LR','MW','MV','ML','MH','FM','NA','NR','NE','PW','PG','WS','SM','ST','SN','SC','SL','SB','KN','LC','VC','SR','TL','TO','TT','TV','VU','AZ','BN','BI','KH','CM','TD','KM','GQ','SZ','GA','GN','KG','LA','MO','MR','MN','NP','RW','TG','UZ','ZW','BJ','MG','MU','MZ','AO','CI','DJ','ZM','CD','CG','IQ','LY','TJ','VE','ET','XK'], total=None):

or for all 250 markets, change to:

    def search_markets(self, q, limit=10, offset=0, type="track", markets=['AD','AE','AF','AG','AI','AL','AM','AO','AQ','AR','AS','AT','AU','AW','AX','AZ','BA','BB','BD','BE','BF','BG','BH','BI','BJ','BL','BM','BN','BO','BQ','BR','BS','BT','BV','BW','BY','BZ','CA','CC','CD','CF','CG','CH','CI','CK','CL','CM','CN','CO','CR','CU','CV','CW','CX','CY','CZ','DE','DJ','DK','DM','DO','DZ','EC','EE','EG','EH','ER','ES','ET','FI','FJ','FK','FM','FO','FR','GA','GB','GD','GE','GF','GG','GH','GI','GL','GM','GN','GP','GQ','GR','GS','GT','GU','GW','GY','HK','HM','HN','HR','HT','HU','ID','IE','IL','IM','IN','IO','IQ','IR','IS','IT','JE','JM','JO','JP','KE','KG','KH','KI','KM','KN','KP','KR','KW','KY','KZ','LA','LB','LC','LI','LK','LR','LS','LT','LU','LV','LY','MA','MC','MD','ME','MF','MG','MH','MK','ML','MM','MN','MO','MP','MQ','MR','MS','MT','MU','MV','MW','MX','MY','MZ','NA','NC','NE','NF','NG','NI','NL','NO','NP','NR','NU','NZ','OM','PA','PE','PF','PG','PH','PK','PL','PM','PN','PR','PS','PT','PW','PY','QA','RE','RO','RS','RU','RW','SA','SB','SC','SD','SE','SG','SH','SI','SJ','SK','SL','SM','SN','SO','SR','SS','ST','SV','SX','SY','SZ','TC','TD','TF','TG','TH','TJ','TK','TL','TM','TN','TO','TR','TT','TV','TW','TZ','UA','UG','UM','US','UY','UZ','VA','VC','VE','VG','VI','VN','VU','WF','WS','XK','YE','YT','ZA','ZM','ZW'], total=None):

**Comment by shillshocked** [comment]
By the way, in the experiments I have done, I found Spotify seems to be using these particular 185 country regions regularly (different from the previous 184 list by some). The other ones are probably unnecessary.

Here is the updated list:

First change:
`def search_markets(self, q, limit=10, offset=0, type="track", markets=['AD','AE','AG','AL','AM','AO','AR','AT','AU','AZ','BA','BB','BD','BE','BF','BG','BH','BI','BJ','BN','BO','BR','BS','BT','BW','BY','BZ','CA','CD','CG','CH','CI','CL','CM','CO','CR','CV','CW','CY','CZ','DE','DJ','DK','DM','DO','DZ','EC','EE','EG','ES','ET','FI','FJ','FM','FR','GA','GB','GD','GE','GH','GM','GN','GQ','GR','GT','GW','GY','HK','HN','HR','HT','HU','ID','IE','IL','IN','IQ','IS','IT','JM','JO','JP','KE','KG','KH','KI','KM','KN','KR','KW','KZ','LA','LB','LC','LI','LK','LR','LS','LT','LU','LV','LY','MA','MC','MD','ME','MG','MH','MK','ML','MN','MO','MR','MT','MU','MV','MW','MX','MY','MZ','NA','NE','NG','NI','NL','NO','NP','NR','NZ','OM','PA','PE','PG','PH','PK','PL','PR','PS','PT','PW','PY','QA','RO','RS','RW','SA','SB','SC','SE','SG','SI','SK','SL','SM','SN','SR','ST','SV','SZ','TD','TG','TH','TJ','TL','TN','TO','TR','TT','TV','TW','TZ','UA','UG','US','UY','UZ','VC','VE','VN','VU','WS','XK','ZA','ZM','ZW'], total=None):`

Second change:
```
country_codes = [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "ET",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PR",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW"]
```
