### ISSUE TITLE
Is there any way we can find the id of a playlist without searching for it manually?

### ISSUE THREAD

**Issue by ctran7** [plamere/spotipy#536]
Seeing as there are a lot of functions requiring the id of a playlist, the only way I can see how is using the user_playlists function, loop through the results and match it by the desired name, and get the id there. I think there would be a benefit with adding this functionality with the get go, unless there is some easier way I could not find.

Additionally, I am creating the playlist and immediately adding tracks to it. It would be nice to have the playlist id as a returned value to the user_playlist_create function. Unless this is already a thing, and it's not in the documentation.

**Comment by a-camarillo** [comment]
I haven't used the spotipy `user_playlist_create` function but I would think it returns the playlist object from Spotify's playlist endpoint. [Create a playlist](https://developer.spotify.com/documentation/web-api/reference/playlists/create-playlist/) documentation shows the playlist id is returned as part of the playlist object so it should be an easy value to get.

Hope this helps

**Comment by ctran7** [comment]
Thanks so much!
