### ISSUE TITLE
Implement Authorization Code Flow with Proof Key for Code Exchange (PKCE)

### ISSUE THREAD

**Issue by laymonage** [plamere/spotipy#538]
**Is your feature request related to a problem? Please describe.**
The implicit grant flow is no longer a recommended option for client-side authentication.

**Describe the solution you'd like**
[Spotify now supports PKCE](https://developer.spotify.com/community/news/2020/06/18/pkce-oauth/), so I think this library should implement it.

**Describe alternatives you've considered**
None.

**Additional context**
[Spotify PKCE auth flow guide](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow-with-proof-key-for-code-exchange-pkce).

**Comment by stephanebruckert** [comment]
Closed by https://github.com/plamere/spotipy/pull/542

**Comment by IdmFoundInHim** [comment]
@stephanebruckert
Could we get this in a release soon? Unless you're waiting for something specific, it seems like 2.15 has plenty of changes to warrant a release.
