### ISSUE TITLE
403 error Restriction Violated but I have Premium

### ISSUE THREAD

**Issue by Esamanoaz** [plamere/spotipy#541]
**Describe the bug**
I am getting the 403 error whenever I try to start playback on a Spotify device. This is usually when the user does not have Premium (I think). I have Premium and have double-checked multiple times. The authorization works fine.

**Your code**
https://pastebin.com/fha4Rbdh

**Expected behavior**
- Read Spotify album URI from an NFC tag
- Start playback of that album on a Spotify device (my Google Home Mini)

**Actual behavior**
- Reads Spotify album URI from an NFC tag
- Attempts to start playback on Spotify device
- Fails with 403 error

**Output**
https://pastebin.com/Ejizn084

**Environment:**
 - OS: Raspberry Pi 3
 - Python version 3.5.3
 - spotipy version 2.13.0

**Additional context**
My code worked on Windows 10, then after being transferred to my pi it has no longer worked.
I thought it was not authorizing correctly (it wasn't) so I fixed that, but I am still getting this same error.

I think this error might have something to do with the scope I am using, which is:
`_scope = 'streaming user-read-playback-state user-modify-playback-state'`

Please help!

**Comment by Esamanoaz** [comment]
I printed the reason (Spotify's reasons for player errors here: [link](https://developer.spotify.com/documentation/web-api/reference/object-model/#player-error-reasons)), but it is `UNKNOWN`. I don't know where to go from here.

**Comment by stephanebruckert** [comment]
Strange that you get `UNKNOWN`.

Did you also double-check that you are running the correct user (with premium)? using `sp.me()`. Sometimes it can use a pre-existing token and even if you specify a different `username`, it won't open the sign in page again. Also make sure you explicitely request to open the sign in page again, by adding `show_dialog=True` to `SpotifyOAuth`.

If you still have problems, would be good to get a minimal working example so that we can test this more easily on our side, cheers.

**Comment by Esamanoaz** [comment]
I have done lots of tinkering in the past few months and today I found a solution. I was able to play songs via the `uris` parameter, but not the `context_uri` parameter. This means I can create a list of the track uris from the album and play that, but I would still like to use the `context_uri` parameter for the sake of convenience. I haven't tested yet, but I am going to assume that since albums don't work for playback, playlists won't either since they both use `context_uri`. Doing the same for playlists that have 100+ songs and have songs added and removed often will quickly become an annoyance.

I am very sure that this issue is on Spotify's end. Do you have any ides on how to submit a bug report or fix this?

**Comment by stephanebruckert** [comment]
> I am very sure that this issue is on Spotify's end. Do you have any ides on how to submit a bug report or fix this?

https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
