### ISSUE TITLE
Set open_browser on creation of auth_manager (SpotifyOAuth/SpotifyPKCE)

### ISSUE THREAD

**Issue by SaraBee** [plamere/spotipy#560]
I use Spotipy in some scripts that I am running remotely ssh'd into servers where I don't have access to a browser. It looks like the auth flow is attempting to auto-open a browser, but nothing happens. My current workaround is to run the script and complete the auth flow locally and paste the resulting url + code back into the terminal.

Since I know ahead of time that I won't have access to a browser, and because there's already an `open_browser` variable passed around during the auth flow, I'd love to be able to set this up front when instantiating the auth_manager so that instead of it trying to open a browser and failing, it would just give me the auth url so I could open it myself.

**Comment by stephanebruckert** [comment]
Yep we need this. This is the continuation of https://github.com/plamere/spotipy/pull/528
