### ISSUE TITLE
No way to get currently playing podcast episode

### ISSUE THREAD

**Issue by the-lay** [plamere/spotipy#562]
**Describe the bug**
If you are playing a podcast episode and try to run `current_playback`, you will not get currently playing podcast episode.

According to the [me/player docs](https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-get-information-about-the-users-current-playback), you also need to pass `additional_types=episode` to get podcast data.

current_playback calls `me/player` endpoint without additional_types and there is no way to pass it (only by manually building your own `_internal_call`).

Here's an example API response to `me/player` when playing podcast:

```python
{
   "device":{
      "id":"REDACTED",
      "is_active":True,
      "is_private_session":False,
      "is_restricted":False,
      "name":"REDACTED",
      "type":"Computer",
      "volume_percent":100
   },
   "shuffle_state":False,
   "repeat_state":"off",
   "timestamp":1598641972668,
   "context":"None",
   "progress_ms":543215,
   "item":"None",
   "currently_playing_type":"episode",
   "actions":{
      "disallows":{
         "resuming":True
      }
   },
   "is_playing":True
}
```

**Environment:**
Spotipy 2.13.0

**Comment by the-lay** [comment]
P.S. Manually calling `_get("me/player", market=None, additional_types='episode')` works fine, so the fix for this is to just add `additional_types` keyword to `current_playback(market=None)`

**Comment by naiadbaksh** [comment]
Hi,

I'm having this problem too.  Here's my function that tries to call this.

`def execute_spotify_api_request_current(session_id, endpoint, post_=False, put_=False, ):
    tokens = get_user_tokens(session_id)
    headers = {'Content-Type': 'application/json',
               'Authorization': "Bearer " + tokens.access_token}

    if post_:
        post(BASE_URL + endpoint, headers=headers)
    if put_:
        put(BASE_URL + endpoint, headers=headers)

    response = get(BASE_URL + endpoint, {}, headers=headers, additional_types='episode')
    try:
        return response.json()
    except:
        return {'Error': 'Issue with request'}`

**Comment by naiadbaksh** [comment]
Hi I'm having trouble with this also. I'm working in Python, and I'm trying to add the additonal_types keyword but I can't get the syntax right.

`def execute_spotify_api_request_current(session_id, endpoint, post_=False, put_=False, ):
    tokens = get_user_tokens(session_id)
    headers = {'Content-Type': 'application/json',
               'Authorization': "Bearer " + tokens.access_token}
    # types = "track, episode"

    if post_:
        post(BASE_URL + endpoint, headers=headers)
    if put_:
        put(BASE_URL + endpoint, headers=headers)

    response = get(BASE_URL + endpoint, {}, headers=headers, params={"additional_types":'episode'})
    try:
        return response.json()
    except:
        return {'Error': 'Issue with request'}`

Anyone know where I'm going wrong?

**Comment by naiadbaksh** [comment]
` def execute_spotify_api_request_current(session_id, endpoint, post_=False, put_=False, ):
    tokens = get_user_tokens(session_id)
    headers = {'Content-Type': 'application/json',
               'Authorization': "Bearer " + tokens.access_token}
    # types = "track, episode"

    if post_:
        post(BASE_URL + endpoint, headers=headers)
    if put_:
        put(BASE_URL + endpoint, headers=headers)

    response = get(BASE_URL + endpoint, {}, headers=headers, params={"additional_types":'episode'})
    try:
        return response.json()
    except:
        return {'Error': 'Issue with request'}`

**Comment by naiadbaksh** [comment]
Hi Ilja, I'm having trouble with this working in Python. I'm trying to add the addtional_types keyword, but I can't get the syntax right on the request call. I get a response, but this is the response. Notice the item is null.

`HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "timestamp": 1641845238003,
    "context": null,
    "progress_ms": 2961089,
    "item": null,
    "currently_playing_type": "episode",
    "actions": {
        "disallows": {
            "resuming": true
        }
    },
    "is_playing": true
}`

Here is my function call. 

`def execute_spotify_api_request_current(session_id, endpoint, post_=False, put_=False, ):
    tokens = get_user_tokens(session_id)
    headers = {'Content-Type': 'application/json',
               'Authorization': "Bearer " + tokens.access_token}
    # types = "track, episode"

    if post_:
        post(BASE_URL + endpoint, headers=headers)
    if put_:
        put(BASE_URL + endpoint, headers=headers)

    response = get(BASE_URL + endpoint, {}, headers=headers)
    try:
        return response.json()
    except:
        return {'Error': 'Issue with request'}`

**Comment by stephanebruckert** [comment]
@naiadbaksh you don't seem to be using spotipy here?

**Comment by stephanebruckert** [comment]
So, all fixed?

Should be, as `additional_types` has been added since the issue was raised https://spotipy.readthedocs.io/en/2.19.0/#spotipy.client.Spotify.currently_playing
