### ISSUE TITLE
Error/bug when searching for specific artist's albums

### ISSUE THREAD

**Issue by deniseismo** [plamere/spotipy#569]
A search for an album seems to malfunction a little:
the bug that I've found so far is when you search for any Kraftwerk's album other than _Autobahn_ you get nothing.

```
query = 'album:Computerwelt artist:Kraftwerk'
spotify.search(q=query, type="album", limit=20)
```

**JSON response:**
```
{
    "albums": {
        "href": "https://api.spotify.com/v1/search?query=album%3AComputerwelt+artist%3AKraftwerk&type=album&offset=0&limit=20",
        "items": [],
        "limit": 20,
        "next": null,
        "offset": 0,
        "previous": null,
        "total": 0
    }
}
```
Same for any of these albums : _Kraftwerk, Kraftwerk 2, Ralf und Florian, Radio-Aktivität, The Man-Machine_. Oddly enough, searching for _Autobahn_ **does** work.

A GET request with the same query (as well as [the search via Spotify's console](https://developer.spotify.com/console/get-search-item/?q=album%3AComputerwelt%20artist%3AKraftwerk&type=album&market=&limit=&offset=)) return the correct response.

**Comment by stephanebruckert** [comment]
See https://github.com/plamere/spotipy/blob/master/FAQ.md#search-doesnt-find-some-tracks

**Comment by stephanebruckert** [comment]
let us know if this works:

    spotify.search(q=query, type="album", limit=20, market="DE")
