### ISSUE TITLE
Add market as keyword to search

### ISSUE THREAD

**Issue by robroc** [plamere/spotipy#57]
The Spotify API allows you to specify the market in the search function, and to specify if the market should be inferred from the auth token:
https://developer.spotify.com/web-api/search-item/

It would be nice to have this feature in Spotipy.

**Comment by guspersson** [comment]
Until the feature is added, you can modify `client.py` and add market to the search function on row 324:
`return self._get('search', q=q, limit=limit, offset=offset, type=type, market='SE')`

**Comment by jscholes** [comment]
Why is this ticket still open almost one year later?  It seems like this is a pretty simple change, with a pull request to boot.

**Comment by brki** [comment]
I would also find this useful.
