### ISSUE TITLE
UnboundLocalError: local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by peterbe** [plamere/spotipy#571]
**Describe the bug**
If something goes wrong in `self._session.request()` the variable `response` will never be set. Leading to a 
`UnboundLocalError: local variable 'response' referenced before assignment`

**Your code**
Sorry.
Error from my Rollbar:
<img width="1159" alt="Screen Shot 2020-09-05 at 9 51 41 AM" src="https://user-images.githubusercontent.com/26739/92306493-71e43680-ef5d-11ea-93a5-54f275cbc12d.png">

**Expected behavior**
Requests fail and that's fine. Judging from skimming the code, it's trying to package a message to go with raising a `SpotifyException` but it's failing to do so. 

**Output**
Paste and format errors (with complete stacktrace) or logs. Make sure to remove sensitive information.

**Environment:**
 - spotipy version: `spotipy==2.13.0`

**Additional context**
Relying on `UnboundLocalError` from a caller isn't nice. If it was `SpotifyException` I could do something like this:

```python
from spotipy.exceptions import SpotifyException

try:
    something_that_calls_spotipy(...)
except SpotifyException as err:
    logger.warning("Oh no. Spotify exception...")
```

**Comment by stephanebruckert** [comment]
Should be fixed by https://github.com/plamere/spotipy/pull/580
