### ISSUE TITLE
500 internal error using PaaS, working fine on local

### ISSUE THREAD

**Issue by fullfine909** [plamere/spotipy#584]
Hi!

I am developing a tool that takes songs of Youtube and creates a playlists in Spotify. I have run the application succesfully in local, but I get an error when I try it in Elastic Beanstalk, the PaaS of Amazon. 

I am using a Flask server and the Spotipy python library. I think that the problem is related with the redirect_uri, but I have no idea of what I should do. I create two spotipy objects in my code. The first one, using Client Credentials Flow, works perfectly online. However, when I try to use another one with Authorization Code Flow, I get the error. I can even create it, but when I call to any function, even to search tracks, I get the 500 internal server error. I assume that the redirect_uri has to be the same url where the app is launched. 

Thanks in advance!

**Comment by stephanebruckert** [comment]
Hi, does this help?  https://github.com/plamere/spotipy/blob/master/FAQ.md#how-do-i-obtain-authorization-in-a-headlessbrowserless-environment

**Comment by fullfine909** [comment]
Not really. I think that now it works locally because it has the token in the cache. Do you know how can I force to delete it?

**Comment by stephanebruckert** [comment]
TTthere should be a hidden file starting with `.cache` in your project folder. You can delete it using `rm`

**Comment by fullfine909** [comment]
Okay, I've gotten it to work in a bit of a "dirty" way. Calling SpotifyOAuth () I pass the variable cache_path = '. Mycache' to it, then I upload it to aws and it works, but I think this is just a temporary solution. I attach the link so you can see the work:
http://ys5-env.eba-mjmi37yf.eu-west-1.elasticbeanstalk.com/
Example videos that work:
https://www.youtube.com/watch?v=5lthiQoQiRA&t=2953s&ab_channel=H%C3%96RBERLIN
https://www.youtube.com/watch?v=4utKO75DtBE&t=637s&ab_channel=BE-AT.TV
You can click the title and you will find a playlist with all the songs, you can click a song and the spotify link will open, you can move the mouse over the covers and it will be heard.

**Comment by stephanebruckert** [comment]
I'm not sure what bug you are describing. You should provide the code for a minimal reproducible example, current behaviour with a full stack trace of the 500 you get and behaviour you would expect.

**Comment by stephanebruckert** [comment]
> I pass the variable cache_path = '. Mycache' to it, then I upload it to aws and it works, but I think this is just a temporary solution

I think you are right, it's not a good solution and could be improved.

What I've been doing in my own app is to persist new tokens into a DB and then read from that DB every time I need the token. See https://github.com/resident-archive/resident-archive/blob/a869b73f1f64538343be1604d43693b6165cc58a/functions/to-spotify/main.py#L129..L157

I'm going to close your issue as you found a temporary solution, and the improvement above can be discussed here https://github.com/plamere/spotipy/issues/51
