### ISSUE TITLE
Playlist items always showing 7 items

### ISSUE THREAD

**Issue by IamCLY** [plamere/spotipy#585]
**Describe the bug**
Everytime I tried to pull tracks from playlist its always give me up to 7 instead of the limit (100). I did check all playlist and give me 7 too. Any idea what I missed? I check the limit and it is 100.

**Your code**
```
result = sp.playlist_items(playlistID, additional_types=['track'])
                available_tracks = len(result)
```

**Expected behavior**
Give me more than 7

**Comment by Quizz1Cal** [comment]
This is definitely strange! Can you confirm that you are checking different playlists i.e. that `playlistID` is not always set to the same playlist, or perhaps check this with `print([item['track']['name'] for item in result])`. Some replicable code would be appreciated as well - currently, I'm fetching up to the specified limit.

**Comment by IamCLY** [comment]
I did check it and I try all of the available playlist and give me same results which 7 tracks only per playlist.

**Comment by Quizz1Cal** [comment]
I'm not entirely sure, though I'll keep investigating for you - in the meantime, note that results are buffered based on the limit, try the following:
1. Explicitly set `limit=100` e.g. `spotify.playlist_items(playlistID, additional_types=['track'], limit=100)`
2. Use the below code to fetch ALL the tracks.

As an example:

```python
data_stream = spotify.playlist_items(playlistID, additional_types=['track'], limit=100)
all_tracks = []

while data_stream:
    all_tracks.extend(data_stream['items'])
    data_stream = spotify.next(data_stream)

available_tracks = len(result)
```
This code is necessary for long playlists above the set limit as multiple requests are necessary.

Let us know if doing either 1) or 2) yields any difference!

**Comment by stephanebruckert** [comment]
`result` does not directly contain the items, try `len(result['items'])` instead

**Comment by IamCLY** [comment]
@stephanebruckert yes that solved the issue. Sorry my bad and thanks @Quizz1Cal too!
