### ISSUE TITLE
How to resume playback after pause_playback()?

### ISSUE THREAD

**Issue by jainal09** [plamere/spotipy#586]
```python
@app.route('/pause')
def pause():
    auth_manager = spotipy.oauth2.SpotifyOAuth(cache_path=session_cache_path())
    if not auth_manager.get_cached_token():
        return redirect('/')
    spotify = spotipy.Spotify(auth_manager=auth_manager)
    spotify.pause_playback()
    return redirect('/')
```
I have the following code that pause the current song.
But how do i resume the song after pause_playback()
or already paused song.

**Comment by stephanebruckert** [comment]
https://spotipy.readthedocs.io/en/2.16.0/#spotipy.client.Spotify.start_playback

**Comment by jainal09** [comment]
```python
@app.route('/play')
def play():
    auth_manager = spotipy.oauth2.SpotifyOAuth(cache_path=session_cache_path())
    if not auth_manager.get_cached_token():
        return redirect('/')
    spotify = spotipy.Spotify(auth_manager=auth_manager)
    spotify.start_playback()
    return redirect('/')
```
So when i tried the above code I got the following error
`Player command failed: No active device found, reason: NO_ACTIVE_DEVICE`

**Comment by jainal09** [comment]
Okay its very odd when I do first
`pause_playback()`
and then `start_playback()`
It runs fine!
But if i restart the flask app and directly try to call `start_playback()` i get the same error 
`Player command failed: No active device found, reason: NO_ACTIVE_DEVICE`

**Comment by Peter-Schorn** [comment]
@jainal09 I've found that devices can become inactive very quickly. Try accessing using the `devices` method to get the user's available devices, and ensure that at least one is active.

**Comment by stephanebruckert** [comment]
@jainal09 can you confirm whether you see any device using `Spotify.devices()` before attempting `Spotify.start_playback()`?

**Comment by jainal09** [comment]
Yeh i solved the issue. What is interesting is @Peter-Schorn 's suggestion was right sometimes `Spotify.devices()` would not show device even if my spotify app is open in background in Windows 10 in paused mode.

**Comment by Peter-Schorn** [comment]
The fact that a Spotify client is running doesn't necessarily mean it's active.
