### ISSUE TITLE
How do i get the owner of a playlist

### ISSUE THREAD

**Issue by BananaDrum** [plamere/spotipy#587]
for example on this playlist: https://open.spotify.com/playlist/6p21dRudS9FmcyGvKWPq2R

who can i extract the owner (machinebrother)

thanks :)

**Comment by Peter-Schorn** [comment]
The `Spotify.playlist(self, playlist_id, fields=None, market=None, additional_types=("track",)):` method contains an `owner` property in the top-level of the JSON response.

**Comment by Peter-Schorn** [comment]
```python
sp = spotipy.Spotify(
    auth_manager=spotipy.SpotifyOAuth(
        client_id, client_secret, redirect_uri,
	scope=scope, cache_path=cachePath
    )
)

playlist = sp.playlist("6p21dRudS9FmcyGvKWPq2R")

print(playlist["owner"])
```

**Comment by BananaDrum** [comment]
perfect answer. thanks alot
