### ISSUE TITLE
Finding an album object's record label

### ISSUE THREAD

**Issue by denn9s** [plamere/spotipy#588]
Hi everyone, I've been trying to access the record label of an album object, but I can only access these bits of info:

album_type
artists
available_markets
external_urls
href
id
images
name
release_date
release_date_precision
total_tracks
type
uri

I figured there would be a 'label' key for that, but I can't seem to access it through spotipy.

**Comment by stephanebruckert** [comment]
what album ID are you using? I think not all albums have a label. Can you try with `0sNOF9WDwhWunNAHPD3Baj`?

**Comment by denn9s** [comment]
Hmmm, I'm currently trying it for `7e7t0MCrNDcJZsPwUKjmOc` and I see the label as `Victor Victor Worldwide` in the developer console on Spotify's website, but don't see `label` in the spotipy object keys.

**Comment by stephanebruckert** [comment]
what method are you using? (code)

**Comment by denn9s** [comment]
(I understand it's a bit shoddy, just messing around with the API for now) but I'm accessing a playlist through its `uri` and I'm just testing it with the first track's album. Am I accessing it correctly?

```
client_credentials_manager = SpotifyClientCredentials(client_id=cid, client_secret=secret)
sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager)
playlist_id = 'spotify:playlist:37i9dQZF1DX0XUsuxWHRQd'

results = sp.playlist(playlist_id)
tracks = results['tracks']['items']
for track in tracks:
	track = track['track']
	track_name = track['name']
	track_artist = track['artists']
	track_album = track['album'] # using this as the album object I need to get label from
	track_id = track['id']
	break
```

**Comment by stephanebruckert** [comment]
> I see the label as Victor Victor Worldwide in the developer console on Spotify's website

that's because you are looking at the get-album endpoint https://developer.spotify.com/documentation/web-api/reference/albums/get-album/

whereas you are using a python method for the get-playlist endpoint:

https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlist/

To get the label, you will need to do a another query just for the album: `sp.album(album_id)`

**Comment by denn9s** [comment]
Ah, I see where I got it mixed up. I just made a query for the album itself and it worked as intended. Thank you so much for the help, I really appreciate it! 👍
