### ISSUE TITLE
obeservation spotipy user_playlists.py example

### ISSUE THREAD

**Issue by lfg6000** [plamere/spotipy#591]
First i want to say thanks for contributing to Spotipy, it is really awesome.

Observation
-------------------
- I took this example for a spin:   user_playlists.py   (https://github.com/plamere/spotipy/blob/master/examples/user_playlists.py)
but received an empty list so i added a scope param to the oAuth call and was able to get my playlists.
- admittedly all my playlists are private
- below i have the original example code and the modified example code with a scope param

Question
------------
- so i am wondering if it would be helpful to have the user_playlists.py  example include the scope param?

Hopefully i have not wasted your time with by asking a question that has a really obvious answer,
Louie

original example code - the returned playlists is empty
-------------------------------------------------------------------------------------------------
```
import spotipy
from spotipy.oauth2 import SpotifyOAuth
sp = spotipy.Spotify(auth_manager=SpotifyOAuth())
playlists = sp.current_user_playlists()
for playlist in playlists['items']:
    print(playlist['name'])
```
-------------------------------------------------------------------------------------------------

modified example code - the returned playlists is populated
-------------------------------------------------------------------------------------------------
```
import spotipy
from spotipy.oauth2 import SpotifyOAuth
scope = 'playlist-read-private '
sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=scope))
playlists = sp.current_user_playlists()
for playlist in playlists['items']:
    print(playlist['name'])
```
-------------------------------------------------------------------------------------------------

**Comment by stephanebruckert** [comment]
@lfg6000 nice catch, that makes sense. If you know how to, it would be highly appreciated if you could open a pull request to update the example accordingly 🙏

**Comment by lfg6000** [comment]
ok, i will open a pull request (it will be my first so it may be a few days
as work thru it).
