### ISSUE TITLE
No longer fetching track preview URLs

### ISSUE THREAD

**Issue by Babelfish112** [plamere/spotipy#592]
Hello! I'd like to thank everyone who has worked on spotipy, it helped me get a personal application up and running quickly with a great Python library.

In the last day or two, something has broken the track "preview_url" from being returned as part of an album query.
Running:
`results = sp.album(spotify:album:3obToaukLcPbCLPPmWFzQi)`
which is the album "[12:00]" by LOONA, I get the result (showing only the relevant parts for the first track):

```
    'tracks': {
        'items': [{
                'external_urls': {
                    'spotify': 'https://open.spotify.com/track/2iv1U6ulyjUIWJPSlrawHN'
                },
                'available_markets': ['CA', 'HK', 'ID', 'MX', 'TW', 'US'],
                'id': '2iv1U6ulyjUIWJPSlrawHN',
                'artists': [{
                        'external_urls': {
                            'spotify': 'https://open.spotify.com/artist/52zMTJCKluDlFwMQWmccY7'
                        },
                        'type': 'artist',
                        'name': 'LOONA',
                        'id': '52zMTJCKluDlFwMQWmccY7',
                        'href': 'https://api.spotify.com/v1/artists/52zMTJCKluDlFwMQWmccY7',
                        'uri': 'spotify:artist:52zMTJCKluDlFwMQWmccY7'
                    }
                ],
                'uri': 'spotify:track:2iv1U6ulyjUIWJPSlrawHN',
                'href': 'https://api.spotify.com/v1/tracks/2iv1U6ulyjUIWJPSlrawHN',
                'is_local': False,
                'duration_ms': 73720,
                'preview_url': None,
                'explicit': False,
                'disc_number': 1,
                'name': '12:00',
                'track_number': 1,
                'type': 'track'
            }

```

As you can see, preview_url is None. I fetched this same album a couple of days ago and had the track data stored in my database, which gave the following data (I don't store all data fields):

```
	"uri": "spotify:track:2iv1U6ulyjUIWJPSlrawHN",
	"name": "12:00",
	"preview": "https://p.scdn.co/mp3-preview/a372096964b3d11c2e87958abe76eacca2421c44?cid=22a8c6beeef14b2db604c5de8f80227c",
	"duration": "1:13",
	"track_no": 1,
	"available": false
```

You can see that this first album track with the same URI used to have a preview_url, which still works fine in a browser.

I have been running my Python scripts off a Raspberry Pi with spotipy version 2.12.0 for the last couple of years. Just wondering if anyone else has noticed this issue, and whether the issue can be replicated on newer versions of spotipy.

Thanks!

**Comment by Peter-Schorn** [comment]
Try specifying a value for the market parameter when retrieving the album. See https://github.com/spotify/web-api/issues/148

**Comment by Peter-Schorn** [comment]
preview URLs also don't seem to be returned when you use the Client Credentials Flow.

**Comment by Babelfish112** [comment]
Seems like this is working again without having to modify my app - something must have been broken temporarily. Thanks @Peter-Schorn for the suggestions!
