### ISSUE TITLE
'Address already in use' error when using 'user-top-read' scope

### ISSUE THREAD

**Issue by alansberman** [plamere/spotipy#600]
I'm using the latest version of spotipy. With a normal scope, e.g. 

```
sp = spotipy.Spotify(auth_manager=SpotifyOAuth(client_id="my_id",client_secret="my_secret",
redirect_uri = "http://localhost:8000/callback/", scope="user-library-read"))
```

I'm able to make API calls just fine. However, if I add the 'user-top-read' scope (which I'd like to do to get the current_user_top_tracks() etc.), I get the following error for _any_ API call e.g current_user_playlists() on my Flask backend:

```
OSError: [Errno 48] Address already in use
```

Obviously, without the 'user-top-read' scope I get a 403. Is there a workaround for this?

**Comment by Peter-Schorn** [comment]
This has nothing to do with spotipy. There is another process already using port 8000. You need to find it and kill it. See https://stackoverflow.com/a/19071568

**Comment by alansberman** [comment]
> This has nothing to do with spotipy. There is another process already using port 8000. You need to find it and kill it. See https://stackoverflow.com/a/19071568

Thanks. I'm not sure why this is only the case when I add the 'user-top-read' scope (as with other scopes I don't have this issue), but have made a workaround.

**Comment by Peter-Schorn** [comment]
When you add another authorization scope, you have to go through the authorization process again. It has nothing to do with the "user-top-read" scope specifically.

**Comment by alansberman** [comment]
Ah okay I see. Thanks again @Peter-Schorn .
