### ISSUE TITLE
Spotipy/Flask

### ISSUE THREAD

**Issue by Sticks111** [plamere/spotipy#611]
I hope all is well. I am currently self-studying Python and am working on a Spotify web app using Spotipy, but am having a bit of trouble setting everything up. I was wondering if you might have any tips on how to set up app.py with Spotipy so that it includes @app.route('/'), requests.get, and return render_template, in a way where Flask Run can run successfully? Do Spotipy and Flask work well together? I am a beginner so would appreciate any advice. Thank you!

**Comment by Peter-Schorn** [comment]
See https://github.com/plamere/spotipy/blob/master/examples/app.py

**Comment by Sticks111** [comment]
Thank you Peter! Checking out the link right now. Much appreciated

**Comment by Sticks111** [comment]
Hi Peter,

I've checked out the document and everything has been going smoothly except upon clicking http://127.0.0.1:8888/  or http://127.0.0.1:8080/ subsequent to  python3 -m flask run --port=8888 or  python3 -m flask run --port=8080, I get a "This site can’t be reached 127.0.0.1 refused to connect" message on Chrome. Would appreciate any thoughts on how this issue can be resolved. 

Thanks so much

**Comment by Peter-Schorn** [comment]
@Sticks111 Sorry, but I've actually never used flask. I just knew that example existed. ask @stephanebruckert .

**Comment by Sticks111** [comment]
Thanks, will do!

**Comment by stephanebruckert** [comment]
@Sticks111 check what's outputted in the console, it should give you the correct URL for the flask app. In my case it is http://127.0.0.1:5000/, and not 8080 or 8888

**Comment by Sticks111** [comment]
Indeed, I just resubmitted the steps and what I see in my console is the output: Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)  However when I click on it, I am led to this message: 

This site can’t be reached 127.0.0.1 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

I tried adjusting my internet settings with the exception of firewalls; should I be removing any firewalls?

Thank you

**Comment by Sticks111** [comment]
Looks like there has been a breakthrough; am now on the Sign In page after experimenting in the console and adding two redirect URIs in my Spotify settings. May have to come back later with a quick question but am progressing 
Thanks!

**Comment by stephanebruckert** [comment]
@Sticks111 glad you're progressing. I'm closing this for now but feel free to reopen it with further questions
