### ISSUE TITLE
Oauth __del__ TypeError ? 

### ISSUE THREAD

**Issue by MatsErdkamp** [plamere/spotipy#613]
**Issue**
My Django web server terminal raises the following error sometimes: 

```
Exception ignored in: <bound method SpotifyAuthBase.__del__ of <spotipy.oauth2.SpotifyOAuth object at 0x7f7b906bc320>>
Traceback (most recent call last):
  File "xxxxxxx/env/lib/python3.6/site-packages/spotipy/oauth2.py", line 136, in __del__
TypeError: isinstance() arg 2 must be a type or tuple of types
```
I would not expect it to throw that error every time I do someting.

**Fix**
I am honestly no expert by any means; but changing the oauth __del__ code to include **type()** around the second parameter seems to help.

so the resulting snippet of code would be: 

```
def __del__(self):
    """Make sure the connection (pool) gets closed"""
        if isinstance(self._session, type(requests.Session)):
           self._session.close()

```

While the mistake might be in another part of my programming, this does seemingly solve my problems (for now). I can't tell if this addition breaks anything else,  so some input from someone more experienced might be helpful.

**Environment:**
 - OS: Linux server (Ubuntu 18.04.5)
 - Python version: 3.6.9
 - spotipy version: 2.16.1

**Comment by MatsErdkamp** [comment]
I created a pull request (#615) with this change introduced.

**Comment by Peter-Schorn** [comment]
I don't know exactly what is causing this error, but I don't think your solution makes sense. `requests.Session` is already a type—more specifically, It's a class. `type(requests.Session)` returns the metatype `type`, which is probably not what you want.

**Comment by ThishanD** [comment]
worked for me!
