### ISSUE TITLE
artist_discography parameter question

### ISSUE THREAD

**Issue by robertb141** [plamere/spotipy#616]
In the Example > artist_discography > def get_args function.

- The "parser.add_argument('-a', '--artist', required=True..."

- What should I put here ('-a', '--artist') if I want to see an artist like Drake for
![parameters](https://user-images.githubusercontent.com/61035696/99920260-4bc66b00-2cf0-11eb-9e43-1ff6a3b1b711.png)

**Comment by robertb141** [comment]
solved it!

**Comment by stephanebruckert** [comment]
> solved it!

@robertb141 how? 😃  it might help others

**Comment by robertb141** [comment]
It was not supposed to be changed in the actual code. It was simply a command line parameter:
Example in the terminal writing: python3 artist_discography.py -a "drake"
