### ISSUE TITLE
unable to download 2.16.1

### ISSUE THREAD

**Issue by gchenra** [plamere/spotipy#620]
**Describe the bug**
Hi, 
I run ```pip install spotify``` in my python virtual environment and is only able to get version 0.10.2. 
Can anyone help? Thanks!

**Environment:**
 - OS: Mac
 - Python version 3.7.0
 - spotipy version: N/A
 - your IDE: PyCharm

**Comment by ichard26** [comment]
You meant to run `pip install spotipy`, notice how the last two letters of `spotify` are replaced with `py`.

**Comment by stephanebruckert** [comment]
Hope @ichard26's answer helped @gchenra :-)
