### ISSUE TITLE
delete_a_saved_track example fails

### ISSUE THREAD

**Issue by t0000** [plamere/spotipy#622]
Hello

When executing the script, the track is not deleted from the saved tracks

https://github.com/plamere/spotipy/blob/2.16.1/examples/delete_a_saved_track.py

no error is output -> Process finished with exit code 0

Environment:
Python version [3.9.0]
spotipy version [2.16.1]

**Comment by stephanebruckert** [comment]
Yes the file has an indent problem, just unindent the last 3 lines

**Comment by t0000** [comment]
with this code: https://pastebin.com/qCqC29M4

i get this error: https://pastebin.com/NhQQj58a

can you check that please? Regards

**Comment by t0000** [comment]
the solution is:
results = sp.current_user_saved_tracks_delete(tracks=[tids])

**Comment by stephanebruckert** [comment]
@t0000 nice catch, thanks for the solution.

Just reopening this until we fix it through a PR
