### ISSUE TITLE
encode error

### ISSUE THREAD

**Issue by blackjack4494** [plamere/spotipy#63]
Traceback (most recent call last):
  File "playlist.py", line 30, in <module>
    print playlist['name']
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2013' in position
 11: character maps to <undefined>

so u'\u2013' is a dash "-"

**Comment by CDeLeon94** [comment]
Same issue: 
`UnicodeEncodeError: 'charmap' codec can't encode character '\u0131' in position 2: character maps to <undefined>`

Particularly in my case when I try printing out a json response that contains this artist:

`spotify:artist:1tcqeQAROtzEdmsNer8YXM`

**Comment by stephanebruckert** [comment]
I couldn't reproduce it with the given output. Please let me know if it happens again and share your code, not just the error. Also make sure you upgrade:

    pip install spotipy --upgrade

**Comment by bjobo** [comment]
I get the same error, when I tried to fetch songs with a German 'Umlaut' (äöü). I'm using Python 3.4.2 (can't upgrade because it's bundeld with volumio).

`
Traceback (most recent call last):
  File "spotify_helper3.py", line 23, in <module>
    print(playlist['name'])
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 2: ordinal not in range(128)
`

I used a code example from the documentation

`
import sys
import spotipy
import spotipy.util as util

if len(sys.argv) > 1:
    username = sys.argv[1]
else:
    print("Whoops, need your username!")
    print("usage: python user_playlists.py [username]")
    sys.exit()

token = util.prompt_for_user_token(username)

if token:
    sp = spotipy.Spotify(auth=token)
    playlists = sp.user_playlists(username)
    for playlist in playlists['items']:
        print(playlist['name'])
else:
    print("Can't get token for", username)
`

**Comment by stephanebruckert** [comment]
Hey @bjobo can you please provide an artist ID or public playlist ID? thx

**Comment by bjobo** [comment]
Example Track-ID: spotify:track:1dbd8HmdfD4BSIkIMoom3l

I tried it successfully on a different Raspberry Pi with Python 3.7.3 (default, Dec 20 2019, 18:57:59).
I don't know if the error results from using Python 3.4.2 (can't upgrade) or a wrong encoding. Any ideas?

**Comment by bjobo** [comment]
After some testing I found out the problem is caused by the file system encoding:
```
Python 3.4.2 (default, Sep 26 2018, 07:16:01)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> sys.getfilesystemencoding()
'ascii'
```

If I set the env `export PYTHONIOENCODING=utf-8` everything works fine. (However I don't know which other consequences it does have).

Long story short: Ticket can be closed. It's not caused by Spotipy.
