### ISSUE TITLE
Urllib3 method_whitelist deprecated

### ISSUE THREAD

**Issue by ReneNulschDE** [plamere/spotipy#637]
**Describe the bug**
In Urllib3 version >= 1.26.0 `Retry(method_whitelist=...)` is deprecated. Your component is using method_whitelist [here](https://github.com/plamere/spotipy/blob/44970c3348f4242be4dbadadf1d08ff5242918da/spotipy/client.py#L197)

**Your code**
None. Your lib is used in the Home-Assistant Spotify component.

**Expected behavior**
No deprecation warnings. Check if a replacement with `allowed_methods` is possible. Tested this with a local code change and works good.

**Output**
/home/rene/repos/core/venv/lib/python3.8/site-packages/urllib3/util/retry.py:252: DeprecationWarning: Using 'method_whitelist' with Retry is deprecated and will be removed in v2.0. Use 'allowed_methods' instead

**Environment:**
 - OS: Linux Ubuntu 20.04
 - Python version: 3.8.6
 - spotipy version: 2.16.1

**Additional context**

**Comment by stephanebruckert** [comment]
Released in 2.17.1
