### ISSUE TITLE
Couldn't read cache at: .cache

### ISSUE THREAD

**Issue by ty-on-h12** [plamere/spotipy#642]
Hello

I want to authenticate users with Spotify in order to access their saved tracks. I've been following example form this repo README, I got the authentication process to run on a localhost Flask server. However every time I run the app my console throws me this warning :  "Couldn't read cache at: .cache" \n "Enter the URL you were redirected to:"
If I copy and paste the URL from browser I can get this working and it does actually create .cache file in my directory. In production users won't be able to copy and paste a URL into console, this has to happen automatically.
I am running on Ubuntu 20.04, Python3.7 and latest Spotipy. My Spotify developer credentials are all set up.

Help greatly appreciated :)

**Comment by stephanebruckert** [comment]
You want to handle any amount of user on a server, so you are looking to [integrate Spotipy in an API](https://github.com/plamere/spotipy/blob/master/FAQ.md#how-to-use-spotipy-in-an-api)
