### ISSUE TITLE
Problems with recent changes to client.py

### ISSUE THREAD

**Issue by jrauvola** [plamere/spotipy#654]
**Describe the bug**

I am developing an application that takes in user Spotify data. The change made a few days ago from method_whitelist to allowed_methods is throwing errors for some but not all of my group members 

**Your code**
Share a complete minimal working example.

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(client_id='e2d254e0598f4ff49c5ce98717d35334',
                                               client_secret='db0d037ea3fe46d4b62c205ce5208d63',
                                               redirect_uri='http://localhost:8888/callback',
                                               scope="user-library-read",
                                               open_browser = False))

**Expected behavior**

All I want is to gain access to the mock user account - so I should receive the typical output for this line of code as explained in the documentation  

**Output**
Paste and format errors (with complete stacktrace) or logs. Make sure to remove sensitive information.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-a039bb6c9698> in <module>()
      3                                                redirect_uri='http://localhost:8888/callback',
      4                                                scope="user-library-read",
----> 5                                                open_browser = False))

1 frames
/usr/local/lib/python3.7/dist-packages/spotipy/client.py in _build_session(self)
    198             status=self.status_retries,
    199             backoff_factor=self.backoff_factor,
--> 200             status_forcelist=self.status_forcelist)
    201 
    202         adapter = requests.adapters.HTTPAdapter(max_retries=retry)

TypeError: __init__() got an unexpected keyword argument 'allowed_methods'

**Environment:**
 - OS: [e.g. Windows, Mac]
 - Python version [e.g. 3.7.0]
 - spotipy version [e.g. 2.12.0]
 - your IDE (if using any) [e.g. PyCharm, Jupyter Notebook IDE, Google Colab]

Google Colab

**Additional context**

**Comment by stephanebruckert** [comment]
Do you have spotipy 2.17.1?

    pip list | grep spotipy

**Comment by jrauvola** [comment]
Yes I do 

Command ran:

pip list | grep spotipy:

Output:

spotipy                       2.17.1

**Comment by stephanebruckert** [comment]
Strange, 2.17.1 aimed to fix that. Could you also please check the version you have for `urllib3` and `requests?

**Comment by jrauvola** [comment]
Updated urllib3 & requests - works now - thank you for your time
