### ISSUE TITLE
Add a Social Sessions Support

### ISSUE THREAD

**Issue by fuccsoc** [plamere/spotipy#656]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add methods to use social session

**Describe alternatives you've considered**
-

**Additional context**
[Here's](https://del.dog/lopihyfilu.txt) some usefull stuff, that will help you yo do this

**Comment by stephanebruckert** [comment]
Please add more context - what part of the existing Spotify API would this implement?

**Comment by fuccsoc** [comment]
This feature's API isn't docummented oficially. 
Official description: https://support.spotify.com/us/article/group-session/
If you follow the link in issue, you'll see requests, that official Spotify Android client send to API server when you create (delete) session.

**Comment by fuccsoc** [comment]
> [Here's](https://del.dog/lopihyfilu.txt) some usefull stuff, that will help you yo do this
To make requests more readable, here's MD version: https://del.dog/lopihyfilu.md

**Comment by stephanebruckert** [comment]
Just because android devices are using that endpoint doesn't mean it will also be available on the public API. 

Can these endpoints be used through `api.spotify.com` and have you tried it?

**Comment by fuccsoc** [comment]
No, they can't. 
I wrote, that this API method doesn't docummented officially, but can be useful in some cases.

**Comment by stephanebruckert** [comment]
Yeah I don't see how this could be integrated into the current library as it works with api.spotify.com endpoints only.

**Comment by fuccsoc** [comment]
Uhh, sorry, I lost sight of it.

**Comment by stephanebruckert** [comment]
np, thanks for sharing though!
