### ISSUE TITLE
Spotipy can no longer find devices

### ISSUE THREAD

**Issue by Octacon100** [plamere/spotipy#659]
So I've had some code running for weeks and it's been able to find my chromecasts/google homes pretty well, but last night it seems to have issues finding any chromecasts/google homes, I'm wondering if a Spotify update might have caused it. Seems like the web interface doesn't list google homes/chromecasts any more, it just lists "Google Cast" and you select your speaker inside of there.

Here's my code I'm using:

```
# Query spotify for active devices
devices_available = client.devices()

# Match active spotify devices with the spotify controller's device id
for device in devices_available["devices"]:
    if device["id"] == sp.device:
        spotify_device_id = device["id"]
        break

if not spotify_device_id:
    print('No device with id "{}" known by Spotify'.format(sp.device))
    print("Known devices: {}".format(devices_available["devices"]))
    sys.exit(1)
```

Here's the output:

```
No device with id "4862a56929200af9e9485aae060e7724" known by Spotify
Known devices: []
```
Looks like it can't find anything at all even if the google home is assigned to the spotify controller.

**Comment by provinzio** [comment]
I have the same problem. I can see my devices using the spotify web api console, but `spotipy.Spotify.devices()` is empty.

**Comment by Octacon100** [comment]
Best answer I can find is that the token security needed for this to work now is "user-read-playback-state", which sounds like a new thing from previous, based on this Spotify help chat: https://community.spotify.com/t5/Spotify-for-Developers/get-users-available-devices-return-empty-even-if-I-am-opening/td-p/5172688

Looks like there's a bunch of Spotify tickets around playing on Chromecast. I had this working for weeks, would like to know if there's anything I can do to help with this. https://github.com/spotify/web-api/issues/787

**Comment by jfmennedy** [comment]
Same issue for me since mars 22.. what happened with spotify?

**Comment by fondberg** [comment]
This is a spotify problem

**Comment by provinzio** [comment]
@fondberg do you now a way to fix this? I already renewed my `sp_dc` and `sp_key` cookies without any effect.

**Comment by fondberg** [comment]
Yes and no. Head over to spotcast where I will reveal it soon :-)

**Comment by stephanebruckert** [comment]
Since there is nothing we can do about this on the spotipy side, I'm closing this
