### ISSUE TITLE
How to disable printing/logging errors

### ISSUE THREAD

**Issue by muggleboii** [plamere/spotipy#661]
Hi, I'd like to disable the error being printed when there's any error.
e.g.
`HTTP Error for PUT to https://api.spotify.com/v1/me/player/play returned 403 due to Player command failed: Restriction violated`

I'm not printing any error with my try/except blocks but the example above keeps printing even though I don't wanna. Please help. Thank you in advance :)

**Comment by Peter-Schorn** [comment]
Here's how to suppress log messages:
```python
import logging

logging.disable(logging.CRITICAL)
```

**Comment by muggleboii** [comment]
Thanks Peter! it's not logging anymore.
