### ISSUE TITLE
Is there a way to avoid multiple redirects, when you need to use different scopes in the Authorization Code Flow?

### ISSUE THREAD

**Issue by leej11** [plamere/spotipy#668]
Hi all,

I'm a new user of `spotipy` and have just made a draft script to [organise my saved tracks into YearMonth playlists](https://github.com/leej11/spotify-organisation/blob/main/main.py). 

In my script I'm using the [Authorization Code Flow](https://spotipy.readthedocs.io/en/2.17.1/#authorization-code-flow) since I need to access user specific information. 

The challenge I've encountered is that I end up having to authenticate with the Redirect URLs multiple times. I believe this is because I'm interacting with the API in a few different **scopes**. 

For example the scopes I'm using in the script are:
* `user-library-read` scope is used to get my saved tracks
* `playlist-modify-public` scope is used to create my playlists
* `playlist-read-private` scope is used to read my playlists
* `playlist-modify-public` scope is used to add songs to my playlist(s)

Am I misunderstanding something? Is there a way to avoid having to do multiple Redirect URL authentications if the code I'm running needs to query the API with different scopes along the way?

Thanks in advance, really keen to get advice and learn!

**Comment by stephanebruckert** [comment]
You can request multiple scopes by doing:

    sp = create_spotipy_authed_instance('user-library-read,playlist-modify-public')

and re-use the same `sp` everywhere.

In the next version, we will also be able to pass a list as a scope, thanks to https://github.com/plamere/spotipy/pull/650

**Comment by stephanebruckert** [comment]
@leej11 I just released 2.18.0, so you should be able to pass a list of scopes now

**Comment by stephanebruckert** [comment]
Closing this, let me know if you have any issue with the above answer

**Comment by leej11** [comment]
Hi @stephanebruckert, sorry for my delay in getting back to you, had a busy week 😄 Thanks so much for your response, I've just tried it out using `2.18.0` and supplying a list of scopes, works like a charm!
