### ISSUE TITLE
sp.search() is no longer working...returns JSON error

### ISSUE THREAD

**Issue by srprinz** [plamere/spotipy#676]
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Peter-Schorn** [comment]
You need to post an example that reproduces this error.

**Comment by srprinz** [comment]
artist = sp.search(q="Lady Gaga", type="artist")
print(artist)

@Peter-Schorn

**Comment by Peter-Schorn** [comment]
Can't reproduce. Please provide a fully self-contained example.

> JSONDecodeError: Expecting value: line 1 column 1 (char 0)

This indicates that when attempting to decode the string into a json object, a parsing error occurred at the very beginning of the string. This is likely because the string is completely empty.

**Comment by gustavopcassol** [comment]
Maybe related to #570 (the error is raised in `oauth2.py`).

**Comment by Peter-Schorn** [comment]
Can you reproduce this error reliably in your code?

**Comment by stephanebruckert** [comment]
@srprinz we would need a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) and a full stack trace to understand where the error exactly comes from. Also when creating this bug report you've skipped providing more information such as your environment:

```
**Describe the bug**
A clear and concise description of what the bug is.

**Your code**
Share a complete minimal working example.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Output**
Paste and format errors (with complete stacktrace) or logs. Make sure to remove sensitive information.

**Environment:**
 - OS: [e.g. Windows, Mac]
 - Python version [e.g. 3.7.0]
 - spotipy version [e.g. 2.12.0]
 - your IDE (if using any) [e.g. PyCharm, Jupyter Notebook IDE, Google Colab]

**Additional context**
Add any other context about the problem here.
```

please update your initial post if possible

**Comment by frucci** [comment]
This documentation code doesn't print

```
import spotipy
import sys
from spotipy.oauth2 import SpotifyClientCredentials

spotify = spotipy.Spotify(auth_manager=SpotifyClientCredentials())

if len(sys.argv) > 1:
    name = ' '.join(sys.argv[1:])
else:
    name = 'Radiohead'

results = spotify.search(q='artist:' + name, type='artist')
items = results['artists']['items']
if len(items) > 0:
    artist = items[0]
    print(artist['name'], artist['images'][0]['url'])
```
