### ISSUE TITLE
Spotify occasionally forces me to change my password, which affects all stored spotify tokens. Resetting password and creating new tokens, scripts don't work anymore

### ISSUE THREAD

**Issue by shillshocked** [plamere/spotipy#677]
**Describe the bug**
My Spotify password occasionally doesn't work anymore, which requires a password reset. Doing so invalidates all my old app tokens. I can regenerate those ones (I keep them as local files cached to refresh), but now they aren't working, even with no error message.

**Comment by shillshocked** [comment]
I'm guessing it might possibly have something to do with the new CacheFileHandler(), I haven't used this before and I'm unaware of the syntax.

**Comment by Peter-Schorn** [comment]
It has nothing to do with the `CacheFileHandler ` (what makes you think that?). This class contains the same caching logic as before.  What error do you get when you try to make a request with the invalid token? And why do you have to change your Spotify password? I've never had to change my password.

**Comment by shillshocked** [comment]
Yeah, I don't know, I get that issue once in a while (maybe months, could be more frequently). 

Anyways, I messed around a bit more with the code, and I managed to get the scripts running again.

Just curious, can you give me an example of how to use CacheFileHandler in a code snippet? Because I am still using the username authorization.

**Comment by Peter-Schorn** [comment]
```python
from spotipy import Spotify, SpotifyOAuth, CacheFileHandler

spotify = Spotify(
    auth_manager=SpotifyOAuth(
        client_id=client_id,
        client_secret=client_secret,
        redirect_uri=redirect_uri,
        scope=scope_string,
        cache_handler=CacheFileHandler(username=username)
    )
)
```
Some of these parameters can be set in the environment variables. See the documentation comments for more information.
You may get an extraneous warning message as described in #674

**Comment by Peter-Schorn** [comment]
What error message are you getting when you try to use an invalid token? I'm curious.

**Comment by shillshocked** [comment]
Thanks. Initially the problem was: spotipy "Couldn't refresh token: code:400"

I deleted the cached token. Made a new app. Put the variables in to the .bashrc. That seemed to get things working.

Sometimes you have to reset your client secret or make a new app to get things working again if your account is bugged. I think this happens every time you reset your password (perhaps a security feature of Spotify).

**Comment by Peter-Schorn** [comment]
If you get a "Couldn't refresh token: code:400," error, then you should only need to delete the cached token info. You shouldn't need to create a new developer application. Try only deleting the cached token info next time.
