### ISSUE TITLE
Spotify offset no longer working after 1,000 results?

### ISSUE THREAD

**Issue by shillshocked** [plamere/spotipy#683]
When looking for new albums by alphanumeric search, you hit a limit after 1,000 results. Using offset doesn't work anymore past that.

HTTP Error for GET to https://api.spotify.com/v1/search?query=tag%3Anew+10*&type=album&market=US&offset=1000&limit=50 returned 404 due to Not found

**Comment by stephanebruckert** [comment]
That's expected according to the doc https://developer.spotify.com/documentation/web-api/reference/#category-search 

> offset
> The index of the first result to return.
> Default: 0 (the first result).
> Maximum offset (including limit): 1,000.
> Use with limit to get the next page of search results.

**Comment by stephanebruckert** [comment]
Closing this for now but let us know if you would do anything differently for that case
