### ISSUE TITLE
Remove playlist by name

### ISSUE THREAD

**Issue by 9acca9** [plamere/spotipy#709]
How i can do to delete (or unfollow....) a playlist by his name, or just knowing his name? I mean, i know the playlist is in my playlists and is called "Musicaaaaa"... i imagine that first i have to get the "id". There is a way to make this without "human intervention"?
Thanks.

**Comment by Peter-Schorn** [comment]
Just get a list of all of your playlists and iterate through it until you find one with the correct name. Then, unfollow the playlist using the id.
