### ISSUE TITLE
cannot import spotipy.cache_handler.MemoryCacheHandler

### ISSUE THREAD

**Issue by tridelt** [plamere/spotipy#713]
**Describe the bug**
I am unable to import the MemoryCacheHandler

**Your code**
```from spotipy.cache_handler import MemoryCacheHandler```

**Output**
```---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f656db8af614> in <module>
----> 1 from spotipy.cache_handler import MemoryCacheHandler

ImportError: cannot import name 'MemoryCacheHandler' from 'spotipy.cache_handler' (/Users/luca/anaconda3/lib/python3.8/site-packages/spotipy/cache_handler.py)
```

**Environment:**
 - OS:  Mac
 - Python version python3.8
 - spotipy version 2.18.0
 - IDE: PyCharm and also Google Colab

Would love to get an answer : )
Yours
Tridelt

**Comment by Peter-Schorn** [comment]
That's because `MemoryCacheHandler` doesn't exist in version 2.18.0. You should've looked at the file path in the error message.

**Comment by tridelt** [comment]
@Peter-Schorn thank you!
