### ISSUE TITLE
Writing integration tests for spotipy-based app

### ISSUE THREAD

**Issue by joebonneau** [plamere/spotipy#718]
Hi there,

I'm writing integration tests for a CLI tool and I'm trying to determine the best way to structure my tests. For things like testing whether a search was run successfully, it makes sense to test the response itself. 

But what about testing something like whether `next_track` was successful? I haven't been able to figure out whether I can extract the response code, so I would need to, instead, first make a call to `current_playback` then call it again and test whether the responses differ.

Of course, I could always just test whether something like a `SpotifyException` is raised, but I'm not sure I would encounter this error unless my authentication was unsuccessful. I do hit this error when there is no active device and `device_id` isn't passed in, but I'm thinking I could get some wonky results in my CI builds if there happens to be an active device and I didn't realize before running the build.

So I guess my questions are:
1.  Can I access the response code from the `Spotify` object after making a call?
2. If not, how might you suggest I structure my tests?

Thanks!

**Comment by stephanebruckert** [comment]
> For things like testing whether a search was run successfully, it makes sense to test the response itself.

agree!

> But what about testing something like whether next_track was successful? 

Why would that be different, I believe it would also directly send a response? For example, show playlist tracks, do "next" once, and verify that you get the second page?

You don't want to be testing spotipy, as we can assume it works.

**Comment by Peter-Schorn** [comment]
> But what about testing something like whether next_track was successful? I haven't been able to figure out whether I can extract the response code

spotipy does not always return the response code. If the underlying API request returns a non-successful status code, then the method will raise an exception (which may contain the http status code in it), which you'll probably want to interpret as a test failure. If a successful status code is returned, then an exception will not be raised. For the purposes of your tests, this is all the information you need.

**Comment by joebonneau** [comment]
Thanks for the input @stephanebruckert and @Peter-Schorn ! I think that I've got my head on my shoulders now as far as approaching the problem goes. I am still quite new to the concept of mocking (though it's making more and more sense as I go) and still wrapping my head around when I actually need to use it.  

>  But what about testing something like whether next_track was successful?
>>Why would that be different, I believe it would also directly send a response? For example, show playlist tracks, do "next" once, and verify that you get the second page?

My thought here was that a method like `Spotify.search()` returns data in the response but `Spotify.next_track()` does not and I was unsure how to handle that. But as Peter mentioned, an exception will be raised if the method is unsuccessful and that should be sufficient for my purposes.

**Comment by joebonneau** [comment]
So I was able to write the integration tests but I'm now running into another issue that perhaps one of you has experience with. In CI, my integration tests seem to get held up at the step where the authentication is made and I'm struggling to figure out what's going on.

I see in the integration tests for Spotipy for user endpoints, this is used:
```python
 token = prompt_for_user_token(cls.username, scope=scope)

cls.spotify = Spotify(auth=token)
```

Any thoughts about whether this approach is necessary vs. what works locally?:
```python
auth = sp.Spotify(
            auth_manager=SpotifyOAuth(
                scope=scope,
                client_id=client_id,
                client_secret=client_secret,
                redirect_uri=redirect_uri,
                open_browser=False,
           )
)
```

Thanks in advance.

**Comment by Peter-Schorn** [comment]
Don't test the authorization process. Authorize your app in advance and then save the token info in persistent storage.

**Comment by joebonneau** [comment]
I've already authorized the app on my local machine and the tests run just fine, so I'm trying to work through what this might look like. I assume that you don't mean to commit the `.cache` file that is generated? I'd assume that would be as bad as committing the `CLIENT_SECRET`, but I may be thinking about this incorrectly.

**Comment by Peter-Schorn** [comment]
Yes, committing the cache file to git is as bad as committing the client secret. But there are ways of securely storing the token info. JSON is just a string, so you can store this string as a secret environment variable, just like your client secret. If you're using github actions to run your tests, then you can use a [repository secret](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository).

**Comment by joebonneau** [comment]
Ah, very cool! I'm using Travis CI, but I'm thinking something like this might work:

Define the token info as an environment variable `TOKEN_INFO`, then:

```spotify
auth = sp.Spotify(
               auth_manager=SpotifyOAuth(
                   scope=scope,
                   client_id=client_id,
                   client_secret=client_secret,
                   redirect_uri=redirect_uri,
                   cache_handler=CacheFileHandler(
                       cache_path=TOKEN_INFO
                  )
       )
)
```

I'll give it a go sometime this weekend, but let me know if this seems like a reasonable approach. Thanks again for all of the help, it's really invaluable for a new dev like myself.

**Comment by Peter-Schorn** [comment]
That won't work. `cache_path` should be a file path. `CacheFileHandler` reads and writes to a file. You should use `MemoryCacheHandler` instead. Make sure to convert the JSON string to a python dict before passing it in to `MemoryCacheHandler.__init__`.

**Comment by joebonneau** [comment]
Finally got it! Phew!
