### ISSUE TITLE
Authenticating Spotipy for a single dedicated account

### ISSUE THREAD

**Issue by lucs100** [plamere/spotipy#719]
I apologize in advance because I'm pretty sure this has been sorta asked before but I was having trouble getting started. At the moment my use case for Spotipy only involves interacting with a single dedicated account that I own, and essentially allows (only a few friends can interface with it so I won't be too overrun with requests or anything) multiple people to collaborate on a playlist in a roundabout way (I'm aware that this is a feature in Spotify already, but I wanted to create my own implementation of it). Therefore, I only need to authenticate access to that user account 'permanently' (I'm vaguely aware of tokens expiring after an hour, needing to be refreshed, etc., I should be able to deal with that later). 

However, it seems like I'll have to go through OAuth for this, or generate a token in my program to use later. Having only surface level Python experience, I am thoroughly confused on how I'd go about doing this.

My current code to try and authenticate my account, which is admittedly copy-pasted boilerplate, looks like this:
```python
# get client id, secret, and dedicated account id through .env (above these)

client_credentials_manager = SpotifyClientCredentials(client_id=cid, client_secret=secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)
token = client_credentials_manager.get_access_token()
```

I know this is all-around horrible practice when asking for programming assistance, but I am just absolutely lost on where to go from here. I assume once my `sp` instance is 'authenticated' I'll be able to use it to make requests/posts, but I can't seem to figure out how to either use OAuth to authenticate my dedicated account for use, or how to generate a token through Spotipy. The [relevant documentation](https://spotipy.readthedocs.io/en/2.19.0/#authorization-code-flow) is rather confusing for me as well - I assume I'd have to use authorization code flow, but the implementation doesn't seem to make much sense to me.

Apologies again for taking the lazier way out, but a starting point would be massively appreciated. 😅

**Comment by stephanebruckert** [comment]
Since you plan to do user actions, you will need `SpotifyOAuth` instead of `SpotifyClientCredentials`. Please check the 2 examples in the README to see the difference https://github.com/plamere/spotipy#quick-start

> I'm vaguely aware of tokens expiring after an hour, needing to be refreshed, etc.,

You don't have to worry about that, spotipy takes care of it.

Once you've got the second example in the README working, the rest is not difficult: you will want to replace `sp.current_user_saved_tracks()` by [any other method from the doc](https://spotipy.readthedocs.io/en/2.19.0/#api-reference) that is useful to you.

**Comment by lucs100** [comment]
Seems to be working perfectly. My test method went through once I sorted everything out. Thanks so much for the pointer in the right direction, I'll close the issue now.

**Comment by stephanebruckert** [comment]
'mazing!
