### ISSUE TITLE
Spotipy | Can't see the url needed for token

### ISSUE THREAD

**Issue by Eyfelix** [plamere/spotipy#721]
I want to make my python script run 24/7 in a serveur cause it scrap Spotify info.

I created a serveur, put my python script on it, I can run it using Putty but it cant show me the url or redirect me to the url for the token (see screenshot ).
My project work fine on my computer and I've made a simplify version. 
I've also an error about missing cache file but it dont seem important.
 
![image](https://user-images.githubusercontent.com/79328482/131328713-dce7315b-2527-4912-b59a-f63c71b15c81.png)
What I get when I run my script.

![image](https://user-images.githubusercontent.com/79328482/131328896-6805a338-6221-47ae-a924-a14bcc77ee9d.png)
When I press q.

![image](https://user-images.githubusercontent.com/79328482/131329002-868ee5e6-5fb6-4eca-8f01-742a6f127bf7.png)
Here, they ask me for the url that I don't have.

![image](https://user-images.githubusercontent.com/79328482/131329125-84988cc7-c393-473c-a328-f36f3bd0fcae.png)
When I enter a wrong url or nothing

```
import spotipy
from spotipy.oauth2 import SpotifyOAuth
import os
from  pprint import pprint

##define os variables
os.environ["SPOTIPY_CLIENT_ID"]="client id"
os.environ["SPOTIPY_CLIENT_SECRET"]="client secret"
os.environ["SPOTIPY_REDIRECT_URI"]="localhost:8080"

scope="user-read-recently-played"

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=scope))


historique=sp.current_user_recently_played(limit=50,after=None,before=None) #!THIS LINE BUG
pprint(historique)
```
My code simplifed

Thanks for your help

(ps : it's the first time I post on github)

**Comment by Peter-Schorn** [comment]
Never publicly share your client secret. Go to the Spotify dashboard and change it immediately.

**Comment by stephanebruckert** [comment]
Usually above "Enter the URL..." there should be a link that you can copy from the output  _to_ a browser on a different machine. Here I can't see anything and something tells me that your environment is only displaying the last line. Can you try and see if there are other logs that you didn't copy here?

**Comment by stephanebruckert** [comment]
Ha I think I know, since you are in a headless browser (no UI), you need to set `open_browser=False`, as in this example:

https://github.com/plamere/spotipy/blob/87fe473672be5d61491dcb159c6dd9ec74b1ba85/examples/headless.py#L6

This is explained here in the FAQ https://github.com/plamere/spotipy/blob/master/FAQ.md#how-do-i-obtain-authorization-in-a-headlessbrowserless-environment
