### ISSUE TITLE
KeyError: 'items'

### ISSUE THREAD

**Issue by Ovcheric** [plamere/spotipy#739]
Trying to learn how to use Spotipy to create a text file with all songs and corresponding artist from a playlist. 
When using the example "Playlist Tracks", I copied and pasted the code. When I run it, I get an error: `KeyError: 'items'`
I have the link to the playlist, and I have authorization access. I just dont understand how to pull information from the massive wall of text I get when getting information about songs in a playlist.

**Comment by Peter-Schorn** [comment]
post the stack trace for the code.

**Comment by Ovcheric** [comment]
`Traceback (most recent call last):
  File "C:\Users\ovche\OneDrive\Desktop\Auto Spotify Playlist\AutoSpotifyPlaylist.py", line 49, in <module>
    playlist = sp.playlist_items(playlist_id)["items"]
KeyError: 'items'`

**Comment by Ovcheric** [comment]
If it helps, the error was in the fact that I was looking for 'items' in an array where that attribute did not exist. 

I solved this issue by meticulously following along in the nested dictionary/list that you get when you do `pprint(sp.playlist_items(playlistID))`. 

The CORRECT code if you are looking for the name of the track and artist is:

Name of the track at the top of the playlist:
`sp.playlist_items(playlistID)['tracks']['items'][0]['track']['name']`

Artist of the track at the top of the playlist:
`sp.playlist_items(playlistID)['tracks']['items'][0]['track']['artists'][0]['name']`

And if you want to iterate through the entire playlist, just use a for loop:
```
    for i, item in enumerate(sp.playlist_items(playlistID)['tracks']['items']):
        print(item['track']['name']) #name of the track
        print(item['track']['artists'][0]['name']) #artist of the track
```
