### ISSUE TITLE
HTTP 401 for playlist_upload_cover_image

### ISSUE THREAD

**Issue by valentinfrlch** [plamere/spotipy#749]
So I have a function that takes an image, converts it into base64 and then makes the PUT request through the built in spotify.playlist_upload_cover_image() function. However I always get a 401. I  have already refreshed the token - to no avail. It might also be the scope, but I've tripple-checked `ugc-image-upload` should be right for uploading a custom playlist cover. What am I doing wrong?

Here's the code:

def upload_cover(playlist_id):
    scope = "ugc-image-upload"
    spotify = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=scope, client_id=client_id, client_secret=client_secret, redirect_uri=redirect_uri))
    image = open("dataset/thumbnail.jpg", 'rb')
    image_read = image.read()
    cover_encoded = base64.encodebytes(image_read).strip()
    spotify.playlist_upload_cover_image(playlist_id, cover_encoded)

And here's the output:

headers=response.headers,
spotipy.exceptions.SpotifyException: http status: 401, code:-1 - https://api.spotify.com/v1/playlists/playlist_id/images:
 Unauthorized., reason: None

**Comment by stephanebruckert** [comment]
Check out the tests to see how it can be done 

https://github.com/plamere/spotipy/blob/48d04f343b99014822a87d6ec4965c6c921be8ac/tests/integration/test_user_endpoints.py#L183

I see it's using `base64.b64encode`, not `base64.encodebytes`
https://github.com/plamere/spotipy/blob/48d04f343b99014822a87d6ec4965c6c921be8ac/tests/helpers.py#L15

**Comment by valentinfrlch** [comment]
the .decode("utf-8") at the end did the trick!

**Comment by valentinfrlch** [comment]
For some weird reason the suggested solution has only worked once and never since. I have updated my code to the following:
`    with open("dataset/thumbnail.jpg", 'rb') as image:
        cover_encoded = base64.b64encode(image.read()).decode("utf-8")
        spotify.playlist_upload_cover_image(playlist_id, cover_encoded)`

The only way my code is different from the one in user_endpoint_tests.py is that I read and encode a local file. I don't think the problem is with the way I encode the file, as I have successfully encoded and the decoded the file.
Also I have tried to run the test, and I could get it to pass.
The scope is `"ugc-image-upload"`

**Comment by stephanebruckert** [comment]
Please share a complete minimal example with the image you are using, and I will try to help. Thanks!

**Comment by stephanebruckert** [comment]
By the way, if the issue occurs on the `playlist_upload_cover_image` call, make sure:
 - the image is initially in the JPEG format
 - the image size is maximum 256 KB

**Comment by valentinfrlch** [comment]
Thanks for your reply. The image I‘ve tested this with is 80Kb and in JPEG format. I have attatched it below. Here‘s my code:

def upload_cover(playlist_id):
    scope = "ugc-image-upload"
    spotify = spotipy.Spotify(auth_manager=SpotifyOAuth(
        scope=scope, client_id=client_id, client_secret=client_secret, redirect_uri=redirect_uri))
    # reformat encoding jpg -> base64
    with open("dataset/thumbnail.jpg", 'rb') as image:
        cover_encoded = base64.b64encode(image.read()).decode("utf-8")
        spotify.playlist_upload_cover_image(playlist_id, cover_encoded)

![thumbnail](https://user-images.githubusercontent.com/85313672/145348459-8a014bb2-047d-42a8-a7c5-519e0e45f337.jpg)

**Comment by stephanebruckert** [comment]
I also get 401, it's strange. It could be linked to https://community.spotify.com/t5/Spotify-for-Developers/Bug-Uploading-cover-image-not-working-with-un-refreshed-access/m-p/5156729#M2056 which would be a bug on the Spotify side, but so far I can't reproduce the suggested solution.

**Comment by valentinfrlch** [comment]
Thank you very much for your reply and also for linking the other thread. Yes it is very strange. Let's hope spotify fixes this soon. Am I right that it does work with a refreshed token? If so, how would I implement this?

**Comment by stephanebruckert** [comment]
@valentinfrlch did you fix it?

**Comment by valentinfrlch** [comment]
> @valentinfrlch did you fix it?

No unfortunately not. But I guess all we can really do is to wait for Spotify to fix it, since it's a problem on their end.

**Comment by stephanebruckert** [comment]
I have some live code that is running `playlist_upload_cover_image` smoothly, uploading covers correctly...

It looks identical to the code I tried locally, but what I can do is compare the python/spotipy versions. I'll try to do this ASAP, lacking a bit of time at the moment
