### ISSUE TITLE
albums endpoint should have country/market param

### ISSUE THREAD

**Issue by jadenmazzone** [plamere/spotipy#753]
Very simple but the albums(albums) endpoint should be albums(albums, country). According to Spotify Get Several Albums.

**Comment by jadenmazzone** [comment]
Just "album" is also missing a market/country param.

**Comment by stephanebruckert** [comment]
You probably refer to https://spotipy.readthedocs.io/en/2.19.0/#spotipy.client.Spotify.albums or https://spotipy.readthedocs.io/en/2.19.0/#spotipy.client.Spotify.album which looks for specific album(s) while the `market` parameter already exists on https://spotipy.readthedocs.io/en/2.19.0/#spotipy.client.Spotify.artist_albums, see `country`

**Comment by jadenmazzone** [comment]
Those are different endpoints...Artist_albums does not give any track information while spotify albums / album does, therefore have different responses / data. https://spotipy.readthedocs.io/en/2.19.0/#spotipy.client.Spotify.albums and https://spotipy.readthedocs.io/en/2.19.0/#spotipy.client.Spotify.album should have a "country" param.

**Comment by jadenmazzone** [comment]
Has this been added yet?
