### ISSUE TITLE
Error 400 when trying to add a track to a playlist.

### ISSUE THREAD

**Issue by MarcoMorandin** [plamere/spotipy#771]
I am trying to add tracks into a my own playlist. When I execute the code I get  this error:
`HTTP Error for POST to https://api.spotify.com/v1/playlists/(playlistID)/tracks with Params: {'position': None} returned 400 due to Invalid track uri: spotify:track:3`
I guess it sends only the first character of the id of the song (in this case is 3).
Here is my code:

`
import spotipy
from spotipy.oauth2 import SpotifyOAuth
sp = spotipy.Spotify(auth_manager=SpotifyOAuth(client_id="(client_id)",
                                               client_secret="(client_secret)",
                                               redirect_uri="http://localhost:8080",
                                               scope="user-library-read playlist-modify-public"))

t = '(trackID)'
print(sp.playlist_add_items('(playlistID)', t))
`

Have you got some hint?
Thanks in advice.

**Comment by stephanebruckert** [comment]
> Invalid track uri: spotify:track:3

**Comment by stephanebruckert** [comment]
You need to pass a list to `playlist_add_items`, so `playlist_add_items(["spotify:track:3xxxxxx"])`

**Comment by stephanebruckert** [comment]
TODO: since this issue comes back a lot, let's allow passing a single spotify URI

**Comment by Appolon24800** [comment]
yey no more regex in my code for find the id in the url
