### ISSUE TITLE
Offset in playlist_items not working

### ISSUE THREAD

**Issue by dahunni** [plamere/spotipy#773]
**issue**
No matter what I try, I always get the same tracks in return

```
def listtracks(list):
    for idx, track in enumerate(list):
        print(idx, track)
playlist = 'xxxxxxxxxxxxx(playlist with more than 100 tracks)'
offset = 30
playlist_items = sp.playlist_items(playlist, limit=100, offset=offset)
listtracks(playlist_items['tracks']['items'])

```

**Expected behavior**
incresing the offset should give me a different set of tracks

**Output**
I always get the same output of tracks
**Environment:**

 - OS: Mac OS 12.0 Beta (ARM)
 - Python version [3.9]
 - spotipy version [2.19]
 - your IDE (if using any) [PyCharm]

**Additional context**
Problem does not exist with a direct api call using the Spotify developer console

**Comment by Peter-Schorn** [comment]
The issue is that the identifier you're using for the playlist is malformed. Post the identifier.

**Comment by dahunni** [comment]
The playlist identifier I am using is `1v1rhlhXhgSNkPux9G5qBV?si=066ae87471d945bd`
Correct would be 1v1rhlhXhgSNkPux9G5qBV

Thank you so much this was driving me insane I was troubleshooting for hours now.  That also explains some other problems I was facing but it was a bit strange that I was getting any results at all.

**Comment by Peter-Schorn** [comment]
> but it was a bit strange that I was getting any results at all.
See https://github.com/plamere/spotipy/issues/763#issuecomment-1003441199
