### ISSUE TITLE
Problem to add episode with playlist_add_items

### ISSUE THREAD

**Issue by VeirichR** [plamere/spotipy#775]
Im having trouble with playlist_add_items on spotipy, im trying to add episodes to a new playlist

```
tt = ['https://open.spotify.com/episode/3nwfTNjbhDu8Cnp81TdmGO', 'https://open.spotify.com/episode/3jZ5bleO9SCYZ0akgXhmpX']
sp.playlist_add_items(playlist_id=new_playlist_id_, items=tt)
```
I tryed with episode URLs, IDs and URIs and allways get this error:
`Expected id of type track but found type episode https://open.spotify.com/episode/3nwfTNjbhDu8Cnp81TdmGO`
`Expected id of type track but found type episode https://open.spotify.com/episode/3jZ5bleO9SCYZ0akgXhmpX`

And this is what the documentation say:
```
playlist_add_items(playlist_id, items, position=None)
Adds tracks/episodes to a playlist

Parameters:
playlist_id - the id of the playlist
items - a list of track/episode URIs, URLs or IDs
position - the position to add the tracks
```

I tryed the same code with songs URLs and it works...

**Comment by stephanebruckert** [comment]
@VeirichR what was the fix?
