### ISSUE TITLE
How to check whether client id and client secret are correct before actually calling the API?

### ISSUE THREAD

**Issue by clemwo** [plamere/spotipy#779]
In my program I would like to check whether the supplied client id and client secret are correct before actually using them to add songs to playlists, etc.  
Is there are special function to check whether stuff is correct?  
My issue is that I would like to check the credentials at the start of the program and not when it is running and trying to call the API with incorrect credentials.  

My code looks like this:
```python
auth_manager = spotipy.oauth2.SpotifyOAuth(scope="playlist-modify-public playlist-modify-private "
                                                     "playlist-read-private",
                                               client_id='incorrect_id',
                                               client_secret='false_secret',
                                               redirect_uri='http://localhost:8888/callback')
sp = spotipy.Spotify(auth_manager=auth_manager)

# Here I would like to check whether client_id and client_secret are correct
# my current workaround is to just use me()
    try:
        spotipy_client.me()
    except SpotifyOauthError:
        print('Ya dun goofed')
```
This feels very hacky and I would like to know whether I can simply use a function to check.

**Comment by Peter-Schorn** [comment]
The only way to check if the client id and secret are correct is to attempt to go through the authentication process. The web API is designed with the assumption that the client id and secret are hardcoded into the program (or, at least, they don't change at runtime) by the developer of that program, who knows if the values are correct.

**Comment by clemwo** [comment]
Thanks for the reply. So my somewhat 'hacky' solution is the best one under the circumstances, right?

**Comment by Peter-Schorn** [comment]
Yes.
