### ISSUE TITLE
Playing favorite tracks

### ISSUE THREAD

**Issue by PTka4ev** [plamere/spotipy#786]
How can I play tracks from my 'favorite tracks' playlist?

**Comment by Peter-Schorn** [comment]
These are referred to as "saved tracks" by the web API. See the associated methods on `Spotify`:
* `current_user_saved_tracks`
*  `current_user_saved_tracks_add`
*  `current_user_saved_tracks_delete`
*  `current_user_saved_tracks_contains`

Then use the `start_playback` method to play the tracks.
