### ISSUE TITLE
Trying to get the track id with track name and artist stated, artist name is not the exact same as it actually is

### ISSUE THREAD

**Issue by kingofsquirrel** [plamere/spotipy#788]
Hey, so I hope I'm not bothering you too much here but I've already asked this qestion a few times and nobody was able to provide an answer. So basically whenever I try to get the track id using search is works fine, and it also works when I state an artist like abba, but as soon as I state an artist like Anne-Marie it just doesn't return a track. I think it might be because my input is annemarie instead of Anne-Marie, but basically my question is if there is any way to make the spectrum of answers broader or something like that? Again, I hope I'm not bothering you too much but I can't find a solution  to this.

**Comment by Peter-Schorn** [comment]
Are you trying to get the id for a track given the track name and a slightly-misspelled artist name? Assuming you're using the API correctly, if the expected track is not returned, then there's not much you can do. It would be more helpful if you posted the code you're using.

**Comment by kingofsquirrel** [comment]
`track_id = sp.search(q='track:' + searchOnSpotify[0] + 'artist:' + searchOnSpotify[1], limit=1, type='track')`
That's the code, searchOnSpotify[0] is the track name and searchOnSpotify[1] is the artist name, it does function with non-misspelled artist names, but the weird thing is that it just returns everything like normal but there is nothing inside items. But maybe it's just a problem with the spotify api

**Comment by Peter-Schorn** [comment]
> it does function with non-misspelled artist names, but the weird thing is that it just returns everything like normal but there is nothing inside items.
So you're saying the request returns the expected result when the artist name is spelled correctly, but returns no results when the artist name is misspelled? In that case, there's not much you can do to overcome this issue. It's not a "problem" that the Spotify web API doesn't return any results when you misspell names.
