### ISSUE TITLE
spotipy not working

### ISSUE THREAD

**Issue by user2818427** [plamere/spotipy#794]
This afternoon, my code using the spotipy module worked perfectly, and a few hours ago stopped working. The code stops running as soon as it gets to any spotipy function.

**Comment by RGCTech-Dev** [comment]
Yep, returns None

**Comment by stephanebruckert** [comment]
"Spotipy not working" without providing any other information about your environment or code you are running isn't really helping anyone.

Please fill in a proper bug report

**Comment by stephanebruckert** [comment]
Likely https://github.com/plamere/spotipy/issues/795
