### ISSUE TITLE
Running .search() & .track() methods are stuck running & won't execute

### ISSUE THREAD

**Issue by justingrisanti** [plamere/spotipy#802]
I am creating a project that appends genre data to a pandas DataFrame, my code was working fine until today, it is now stuck in the "running" status & won't finish executing. I'm not sure if it is because I am rate limited. Does anyone know why this is happening?
![Screen Shot 2022-05-03 at 7 26 33 PM](https://user-images.githubusercontent.com/78991453/166590210-24ff8798-6548-4d9c-9d95-f45f4cd1e975.png)

**Comment by justingrisanti** [comment]
It just started working again, strange.

**Comment by danisuba10** [comment]
Same issue here. Sometimes it works, sometimes not.

**Comment by dieser-niko** [comment]
@danisuba10 please check the pinned issue #913. You probably hit a request limit.
