### ISSUE TITLE
Broken link on documentation - 404

### ISSUE THREAD

**Issue by lsouzabr** [plamere/spotipy#807]
**Describe the bug**
I notice a broken link on your documentation:
https://github.com/plamere/spotipy/blob/2.19.0/docs/index.rst#:~:text=See%20Using%20Scopes%20for%20information%20about%20scopes.

**Expected behavior**
I sugest that you change to:

https://developer.spotify.com/documentation/general/guides/authorization/scopes/#:~:text=In%20order%20to%20use%20the,be%20shared%2C%20and%20nothing%20more.

![Captura de Tela 2022-05-13 às 18 43 09](https://user-images.githubusercontent.com/13351966/168398191-ecaae623-8bb8-4579-9791-69c414925144.png)

**Comment by stephanebruckert** [comment]
This seems fixed
