### ISSUE TITLE
Multiple Arguments passed to 'device_id'

### ISSUE THREAD

**Issue by 9u3** [plamere/spotipy#808]
I am trying to start playback on a device using 
```python
current = sp.devices()['devices'][0]['id']
sp.start_playback(track, device_id=current)
````
It errors saying that I passed more than 1 id? How can that be possible.
The ID is '5434252d-e980-4422-9a69-49401104e929_amzn_1'

Full Traceback:
```
Traceback (most recent call last):
  File "main.py", line 57, in getTrackID
    self.playsong(tid)
  File "main.py", line 84, in playsong
    sp.start_playback(track, device_id=current)
TypeError: start_playback() got multiple values for argument 'device_id'
```

**Comment by Peter-Schorn** [comment]
Look closely at the parameters for `start_playback`:

https://github.com/plamere/spotipy/blob/9a627e88f422927822ce39ae9919cc7ab9813dde/spotipy/client.py#L1728-1770

**Comment by 9u3** [comment]
> Look closely at the parameters for `start_playback`:
> 
> https://github.com/plamere/spotipy/blob/9a627e88f422927822ce39ae9919cc7ab9813dde/spotipy/client.py#L1728-L1770

Ah. I really should have read that better. Thanks for helping. ^^
