### ISSUE TITLE
flask session cache handler in 2.20.0

### ISSUE THREAD

**Issue by gabylorenzi** [plamere/spotipy#836]
**code i am running**
python3 auth-test.py  (a renamed version of app.py from the 2.20.0 version of spotipy)

**environment:**
python3 
pip3
spotipy=2.20.0

**error message:**
`python3 auth-test.py
 * Serving Flask app 'auth-test' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
[2022-07-06 20:08:26,738] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "auth-test.py", line 41, in index
    cache_handler = spotipy.cache_handler.FlaskSessionCacheHandler(session)
AttributeError: module 'spotipy.cache_handler' has no attribute 'FlaskSessionCacheHandler'`

I can see that there is a newly added flask session cache handler in the version 2.20.0, but despite having the latest version of spottily installed, i am getting an error. would love any help! thanks in advance!

**Comment by seangui** [comment]
Hi so I believe it's because the changes haven't been released yet. 

So the latest release is 2.20.0 like you said which was released 21 days ago here: 
https://github.com/plamere/spotipy/releases/tag/2.20.0 

But the FlaskSessionCacheHandler was added 14 days ago: 
https://github.com/plamere/spotipy/pull/833 

I think this is probably the issue you're running into.

**Comment by stephanebruckert** [comment]
I need to release 2.21.0 for it to be available. For now you can use master or a specific commit.

**Comment by ckahle33** [comment]
would love to use this with flask as well.

**Comment by stephanebruckert** [comment]
Done, please upgrade :-) https://pypi.org/project/spotipy/2.21.0/

**Comment by ckahle33** [comment]
Thank you so much Stephane and team for your work on spotipy!
