### ISSUE TITLE
Statistics for musicians 

### ISSUE THREAD

**Issue by eliassz** [plamere/spotipy#846]
Hi! Great work! I haven't found in the suggested materials about getting statistics for musicians (for instance, 
daily auditions, average duration of audition and so on). Is it possible to get such information from musician account? Something like [this (Youtube api)](https://developers.google.com/youtube/analytics/reference/reports/query?apix_params=%7B%22metrics%22%3A%22views%2CestimatedMinutesWatched%22%2C%22dimensions%22%3A%22day%2CinsightTrafficSourceType%22%2C%22sort%22%3A%22day%2C-views%22%2C%22startDate%22%3A%222014-05-01%22%2C%22endDate%22%3A%222014-06-30%22%2C%22ids%22%3A%22channel%3D%3DMINE%22%7D)?

**Comment by Peter-Schorn** [comment]
No. Everything possible with the Web API is already implemented.
