### ISSUE TITLE
How many days is long_term / medium_term / short_term?

### ISSUE THREAD

**Issue by ferkrodriguez98** [plamere/spotipy#857]
Hey guys, really cool project!

I was just wondering since I couldn't find it anywhere what does exactly long_term, medium_term and short_term mean when fetching user's top tracks for example. Is it all-time, one year and 30 days?

Thanks!

**Comment by dpnem** [comment]
I found this at https://developer.spotify.com/documentation/web-api/reference/#/operations/get-users-top-artists-and-tracks

> Over what time frame the affinities are computed. Valid values: long_term (calculated from several years of data and including all new data as it becomes available), medium_term (approximately last 6 months), short_term (approximately last 4 weeks). Default: medium_term

**Comment by ferkrodriguez98** [comment]
Thanks you!
