### ISSUE TITLE
Unable to catch Spotify Exception using spotipy.SpotifyException

### ISSUE THREAD

**Issue by Chaitanya98** [plamere/spotipy#861]
**Describe the bug**
I am unable to catch the exception thrown by Spotify using spotipy's SpotifyException objection or with generic error handling.

**Your code**

    songURIList = []
    for idx,_ in tqdm(dfBillboards[5660:5670].iterrows()):
        artist = dfBillboards['Artist'][idx]
        track = dfBillboards['Song'][idx]
        year = dfBillboards['Year'][idx]
    
        try:
            searchResults = sp.search(q=f"{artist}, {track}, {year}",type='track')
            if len(searchResults['tracks']['items'])>0:
                songURI = searchResults['tracks']['items'][0]['uri']
            else:
                songURI = 'Unavailable'
        except spotipy.SpotifyException:
            songURI = 'Unavailable'
        songURIList.append(songURI)

**Expected behavior**
I would normally expect the error to be caught and excepted. But that doesn't seem to be the case and I am unable to catch it with any method.

**Output**
    
![image](https://user-images.githubusercontent.com/51097058/192309779-25627765-7ca0-4439-95f3-5a5ac3920e65.png)

**Environment:**
 - OS: Windows 11
- Python version: 3.8.8
- spotipy version: 2.2
- IDE : Jupyter Notebook IDE

**Comment by Libroru** [comment]
So what was the error? Because I am running into the same issue...
