### ISSUE TITLE
Support refreshing token

### ISSUE THREAD

**Issue by wannabeCitizen** [plamere/spotipy#87]
What is the recommendation of this team for how people should refresh tokens? As it stands all examples are written as though you've just gotten your tokens from a prompt. If I go deep into oauth2.py I can find a private method to refresh tokens however, that requires a whole different object that the standard spotipy instance does not need.

This is a critical part of the library. How do you anticipate this flow working?

**Comment by eugenio412** [comment]
same for me, it should work change _refresh_access_token() to refresh_access_token in the library

**Comment by jeremygrieshop** [comment]
I'd like to know this as well.  I have a long-running app, it needs to refresh the tokens periodically, and I'd like to know how that should be handled in the main control loop.  Try/Catch/login?  Timer-based?  This isn't very clear.

**Comment by eugenio412** [comment]
Usually Whwnever I need a token I first check if it's not expired (I saved the expire time together with the token and refresh token), if it's expired I proceed to renew it using the refresh function. You can find it in my fork of Spotipy http://GitHub.com/eugenio412/Spotipy

**Comment by jeremygrieshop** [comment]
Thanks for the followup.

Are you referring to:  https://github.com/eugenio412/spotipy/blob/master/examples/client_credentials_flow.py

Where you use the SpotifyClientCredentials object to manage this?  If so, that looks like it manages unauthorized logins.  If I want to make authorized API calls, I need a way to pass in the redirect url for authentication.

**Comment by eugenio412** [comment]
Nope, i war referring to the file https://github.com/eugenio412/spotipy/blob/master/spotipy/oauth2.py where refresh_access_token is declared, you can then use it, but there is no example, just read the code and try to make it work, I use it for my project, so it's working

**Comment by stephanebruckert** [comment]
This is how we can currently refresh the token:

```
token = util.prompt_for_user_token(os.getenv('SPOTIPY_USERNAME'), scope=SCOPE)
sp_oauth = oauth2.SpotifyOAuth(
    os.getenv('SPOTIPY_CLIENT_ID'),
    os.getenv('SPOTIPY_CLIENT_SECRET'),
    os.getenv('SPOTIPY_REDIRECT_URI'),
    scope=SCOPE,
    cache_path='.cache-'+os.getenv('SPOTIPY_USERNAME')
)
token_info = sp_oauth.get_cached_token()

sp = spotipy.Spotify(auth=token_info['access_token'])

while True:
    if sp_oauth.is_token_expired:
        token_info = sp_oauth.get_cached_token()
        sp = spotipy.Spotify(auth=token_info['access_token'])
    sp.do_something()
    time.sleep(60)
```

However this looks very messy and we are discussing about a way to improve it here https://github.com/plamere/spotipy/issues/263#issuecomment-578539713. I'm closing this issue in favor of the other one. Please let us know what you think of the suggested improvement
