### ISSUE TITLE
Show tracks from playlists returned by search()?

### ISSUE THREAD

**Issue by jkvlevin** [plamere/spotipy#89]
Can't figure out how to show the tracks from playlists returned by the search function.

**Comment by dabcoder** [comment]
Do you have any code snippets you could show? Can you be more specific wrt what the issue is exactly?

**Comment by jkvlevin** [comment]
I was able to figure it out. Thanks though for the response!

Jake

**Comment by nyboer** [comment]
please post your solution! I am having the same problem.

**Comment by jkvlevin** [comment]
Hi there,

I'm not entirely sure I remember correctly, but I believe the issue was
rooted in the fact that I had incorrectly intialized my spotipy object.
Make sure your sequence looks something along the lines of:



sp = spotipy.Spotify(auth=token)
results = sp.search(q=query, limit=limit, type='playlist')

for playlist in results['playlists']['items']:
results = sp.user_playlist(playlist['owner']['id'], playlist['id'], fields="
tracks,next")
tracks = results['tracks']

Hope this helps!

**Comment by nyboer** [comment]
yes, thanks. I figured out what I was doing wrong, too - I was calling user_playlist with a variable that stored the logged-in name. once I replaced that with the playlist.owner.id , it worked.

**Comment by jkvlevin** [comment]
Glad to hear. Best of luck!
