### ISSUE TITLE
Spotipy Object is not threadsafe with respect to request sessions and connection pools

### ISSUE THREAD

**Issue by jdwilkin** [plamere/spotipy#90]
When a single Spotipy object is used in multiple threads talking to the same endpoint, depending on timing, connection pool closed errors can occur.  This happens because after every request made in _internal_call  "close" is called on the request connection which in turn closes the session's pool for that end point.  If another thread has already come in and been given a reference to that pool then tries to use it later, it will get this pool closed exception

**Comment by jdwilkin** [comment]
after going through the pull requests it seems there is already one that addresses this, (at least it appears to) #68

**Comment by shillshocked** [comment]
Yeah, it's still an issue. This repo doesn't seem to be properly maintained any more as pull requests aren't being honored.

**Comment by stephanebruckert** [comment]
Hey @shillshocked, @jdwilkin, thanks for reporting this. The package is maintained again, any chance you can create a new PR?
