### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by freiermuth** [plamere/spotipy#92]
I've been trying countless different methods, and getting the code and callback, but my application keeps saying "bad request". See below:

`# set environment variables`
`os.environ["SPOTIPY_CLIENT_ID"] = c_id`
`os.environ["SPOTIPY_CLIENT_SECRET"] = c_secret`
`os.environ["SPOTIPY_REDIRECT_URI"] = callback_uri`
`token = util.prompt_for_user_token(username, scope)`

and the output:

Opening https://accounts.spotify.com/...output_omitted...

Enter the URL you were redirected to: http://localhost:8888/...output_omitted...

Traceback (most recent call last):
  File "./HotUnity.py", line 24, in <module>
    token = util.prompt_for_user_token(username, scope)
  File "build/bdist.macosx-10.11-intel/egg/spotipy/util.py", line 86, in prompt_for_user_token
  File "build/bdist.macosx-10.11-intel/egg/spotipy/oauth2.py", line 210, in get_access_token
spotipy.oauth2.SpotifyOauthError: Bad Request

**Comment by jdwilkin** [comment]
I was also just having this problem and in my case I discovered after some inspection that my callback url had a "#" at the end followed by "_=_".  When pasting the callback url into the console I omitted that portion of the url and it worked!  Spotipy needs to be able to properly parse out the code from the callback url

**Comment by stephanebruckert** [comment]
Yes check the `redirect_uri` is correct
