### ISSUE TITLE
Problem running sample code 

### ISSUE THREAD

**Issue by kakyoism** [plamere/spotipy#99]
I ran the sample code "Shows the contents of every playlist owned by a user:" from here:
http://spotipy.readthedocs.io/en/latest/#examples

and got this Terminal sequence:

```
$ python /Users/me/Documents/test/python/hello_spotipy.py myuseracount


            User authentication requires interaction with your
            web browser. Once you enter your credentials and
            give authorization, you will be redirected to
            a url.  Paste that url you were directed to to
            complete the authorization.


Opening https://accounts.spotify.com/authorize?redirect_uri=<some url> in your browser

Enter the URL you were redirected to: 
```

I've white-listed my redirect_uri, exported id/secret/redirect_uri (double-checked that all changes are in effect), and ran the code as is. But the URL opened in my browser says:

```
Error
Oops! Something went wrong, please try again or check out our help area.
```

The same happened after I removed the "remembered" Spotify credential from my browsers (Safari, Chrome).

**Comment by stephanebruckert** [comment]
It's ok to get an error message when the browser opens. What you need to get is the URL itself, copy it and paste it into your terminal.

I'm closing as this issue is old and has been working for others. Feel free to reopen if needed. Cheers
